### ISSUE TITLE
Publications

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#1011]
**Dev**
- [ ] Leverage authors component - all contributors or manual addition. Authors is written in mdx not frontmatter. so `time and date` would make more sense in frontmatter. contributors would go into large author pool on the whole site. 
- [ ] Individual contributors array. <= displaying the data would help

---
[Wireframes](https://www.figma.com/file/3Igwq7iPakOznIVpwwH1AA/SF_Maker-Comm-Dev?node-id=2851%3A6210) from @shea-fitz - used for initial vote

[Mockups](https://www.figma.com/file/7aKYK8Z5dzL7WN6PJYsmwV/Maker-Comm-Dev-%E2%80%93-Blog?node-id=2815%3A1) from @shea-fitz 

**Vote**
- [x] By EOD Nov 30

- [x] blog landing Page would be written as .js not an mdx file
- [x] "Learn more" at the bottom of blog.js will take some research. 
- [x] blog would exist outside /content folder. will need some workarounds/research in build.

Issues to make: 
- [x] Blog.js page (w/Filtering topics)
- [x] Article pages
- [x] Authors component
- [x] Search results (w/YAML tags )

**Comment by twblack88** [comment]
@annaalexakr @TomDeMichele @lesa @seamoon 
Tag any other community blog stakeholder and vote as a comment on this issue

E.g. my vote:
"landing page variation number: 3 
mobile landing variation number: 2 "

If you have any comments please do add them to that Figma!

**Comment by MaximumCrash** [comment]
My vote:

landing page variation: 1
Mobile landing variation: 3

Article Variation: 2
Mobile Article Variation: 3

**Comment by annaalexakr** [comment]
I vote for:

Landing Variation: 1
Mobile Variation: 1

Article Variation: 2
Mobile Article Variation: 3

**Comment by lesamone** [comment]
I vote for:

Landing Variation: 1
Mobile Variation: 3

Article Variation: 2
Mobile Article Variation: 3

**Comment by jerrygoldfarb** [comment]
I vote for:

Landing Variation: 3
Mobile Landing Variation: 1

Article Variation: 2
Mobile Article Variation: 1

**Comment by twblack88** [comment]
Votes are in! Consensus:
Landing: 1
Mobile: 1

Article: 2
Mobile: 3

**Comment by twblack88** [comment]
converting this to an epic since it breaks down into more than just one thing. Updating in the first comment.

**Comment by MaximumCrash** [comment]
Closed by #1172
