### ISSUE TITLE
Blog.js

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#1047]
## Description

To get the blog/publications up and running we'll need to build a JavaScript page that serves as the landing. It has a few moving parts.

[Figma mock](https://www.figma.com/file/7aKYK8Z5dzL7WN6PJYsmwV/Maker-Comm-Dev-%E2%80%93-Blog?node-id=3054%3A6374)

### Pieces

- [ ] Header and section tags beneath it
- [ ] Grid of three selected articles 
- [ ] language selector column on right
- [ ] column of next article types with author display, date, and one liner
- [ ] reads YAML key for `date and time` 
- [ ] applies YAML key for `hidesidenav: true`
- [ ] checks YAML key for article `section tags`
- [ ] Authors component styling (see #1046 )

**Comment by MaximumCrash** [comment]
@allcontributors add @goldfarbas for content

**Comment by MaximumCrash** [comment]
@allcontributors add @goldfarbas for content

**Comment by MaximumCrash** [comment]
One more time? 

@allcontributors add @goldfarbas for content

**Comment by MaximumCrash** [comment]
Trying again

@allcontributors add @goldfarbas for content

**Comment by MaximumCrash** [comment]
Trying again

@allcontributors add @goldfarbas for content

**Comment by MaximumCrash** [comment]
Trying again

@allcontributors  please add @goldfarbas for content

**Comment by MaximumCrash** [comment]
Trying again

@all-contributors add @goldfarbas for content

**Comment by MaximumCrash** [comment]
Trying a different person 

@all-contributors please add @shea-fitz for design

**Comment by MaximumCrash** [comment]
@all-contributors please @MaximumCrash for design

**Comment by MaximumCrash** [comment]
@all-contributors please add @MaximumCrash for design

**Comment by MaximumCrash** [comment]
Trying again

@all-contributors add @goldfarbas for content

**Comment by MaximumCrash** [comment]
Closed by #1172
