### ISSUE TITLE
Article page/template

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#1049]
## Description

Within the blog is it's articles. Where the heart of the YAML keys will apply. Each page will be written in as an mdx file like the rest of the site. One thing to note is the editorial is going to be done upfront _before_ the PR into the site, so the technical heavy lifting will be minimal and will add a last sanity check to content as it goes live.

[Figma mock](https://www.figma.com/file/7aKYK8Z5dzL7WN6PJYsmwV/Maker-Comm-Dev-%E2%80%93-Blog?node-id=3054%3A6547)

## Structure

Title 
First author
header image
MDX
Contributors
Read next

### Build within structure

- [ ] File structure paths (blog folder dependent on #1047 )
- [ ] Header pulls from `title: ` inside YAML
- [ ] Author component with name, image, and date
- [ ] first author in the authors array is the first to display on the page
- [ ] Content
- [ ] contributors element
- [ ] Read more element
- [ ] Data model for articles
- [ ] `create page` inside of gatsby.config

### Contributors at the bottom

Thinking we could leverage the `box` component and just insert some styling for article contributors.
- [ ] array of `contributors` at the bottom
- [ ] YAML key for `contributors`
- [ ] clear page breaks above and after the `box`

**Comment by patrick-j-govalpha** [comment]
Closing legacy issues
