### ISSUE TITLE
CDIP 40 - MakerRelay-DAOcast - finding ways to speak as a DAO Pt.2

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#1057]
**Title:** 
Maker-Relay-DAOcast - finding ways to speak as a DAO Pt.2

**Your name:** 
Jerry Goldfarb 
RocketChat: @Jerry.G 
Email: Jerryagoldfarb@gmail.com

**Advisor:** 
David Utrobin 

**Links to Github issue/forum post/ or discussion thread:** 
#753 - Previously completed CDIP
[Google Doc Draft](https://docs.google.com/document/d/1IEfNtKAt6SPB00o8_opKq2t8SQtowVlnH4o9f2iFGuI/edit#heading=h.ktbfbk9aggt4)

**Proposal abstract:**
Pilot run for the first version of the Podcast, consisting of 4 episodes, focused on Maker Relay.

**Who am I:**
I am Jerry, I have had a passion and love for audio for most of my life, and started learning Ableton (as well as other methods of audio-editing) around 2010. I am confident and hopeful that the examples I created, and will continue to create, offer a unique experience, as well as an idea of some of what the future of this project will look like.

**Proposal:**
To help expand the distribution of Maker Relay and the efforts of GovComms, I propose we figure out a way to distribute the content that goes into Maker Relay in a podcast format and find a way to incorporate voter education into the content. It is entirely possible to presume that this could include; an updated version of the community calls, onboarding info, foundational/community updates. The ideas are only limited by the bandwidth!

Based on my previous proposal and my research document, I would like to propose that the host and I create 4 sample episodes to put out for the community/ecosystem to digest. I will post another forum poll asking if anyone saw/listened/has feedback. This will progress the project forward, as well as giving more analytical information (aside from collected from views, likes, comments etc).

This is an example of one way that the community can improve communication between the DAO, the Maker ecosystem, and the greater DeFi community as a whole. Through weekly updates, we can hopefully keep a larger group up to date on what is going on in governance and the Maker community to keep things open and useful.

_This proposal is to move forward with a pilot and start creating a podcast from our weekly Governance Updates, to create a forum thread in parallel for feedback, and to produce a short report of the results and findings of this pilot._

**Deliverables:**
![image](https://user-images.githubusercontent.com/40721951/102105719-b9e8e400-3dfd-11eb-9924-544d0309c678.png)

**Task Breakdowns:**
![image](https://user-images.githubusercontent.com/40721951/102105771-ca00c380-3dfd-11eb-8db4-5e6350a05c1f.png)

**Cost | Resources:**
As it stands, for this initial proposal, here is the anticipated cost for a single episode. Please see my [research](https://docs.google.com/document/d/1s7rhHgSSxudAeo6jNSksNrGjPH5uvfK6MeWtI2yq5cc/edit) for further explanations of cost breakdowns.

![image](https://user-images.githubusercontent.com/40721951/102105891-ed2b7300-3dfd-11eb-853a-0aacbfd35b23.png)

**Estimated time to completion:**

Episode 1: Jan 5 2021

Episode 2: Jan 12 2021

Episode 3: Jan 19 2021

Episode 4: Jan 26 2021

Analytics and Feedback Report: Jan 29 2021

Availability status:
@Jerry.G - Editing, Research
@Seth.goldfarb - Host

**Comment by Davidutro** [comment]
@jerrygoldfarb

**Comment by jerrygoldfarb** [comment]
https://anchor.fm/voicesofmkr

**Comment by Davidutro** [comment]
Forgot to post this here yesterday,
Approval Committee approved this proposal :)

**Comment by patrick-j-govalpha** [comment]
closing legacy issues
