### ISSUE TITLE
Create FAQ for Translation Gitbook Menu 

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#106]
https://hackmd.io/jkmL7Xv2SAm9YBI4A5UiLA

**Comment by Davidutro** [comment]
- Burban Reviewed it
- Rich reviewed Burban's suggested Edits 
- I added the changes to the HackMD markdown version. I also fixed some minor errors.

**Comment by ghettodev** [comment]
Looks good, tweaked some stuff.  

- ⬙ is cool but it's a bit of a forced meme at this point.  Lets just say 'Dai'
- lets be consistent with the contractions. I prefer 'don't' as 'Do not' sounds a bit too direct
- "Click the links to find out what the Translator and Editor roles entail." What is this referring to?
