### ISSUE TITLE
Accordion Makes the Left Sidebar Drop

### ISSUE THREAD

**Issue by TomDeMichele** [makerdao/community#1062]
**Describe the bug**
On the portal on the desktop when you scroll down the page and the left sidebar moves with you and then you open a closed accordion, the left sidebar moves down with the accordian. See image.

**To Reproduce**
1. Go to 'https://community-development.makerdao.com/en/contribute/content/writing-style-guide'
2. Scroll down to the accordions and click
3. See error

**Expected behavior**
This should not happen.

**Screenshots**

![Screen Shot 2020-12-15 at 11 59 18 AM](https://user-images.githubusercontent.com/54551507/102267040-2fbc8080-3ece-11eb-948c-dfa3fa8c2756.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Brave

**Additional context**
Think this problem is site-wide and was fixed before.

**Comment by patrick-j-govalpha** [comment]
closing legacy issues
