### ISSUE TITLE
Break apart Meetups DIY Kit into sections

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#107]
7/3 update: 

- Documents have been broken apart 
- Waiting on David to edit each of the docs so they can stand alone. 
 

Markdown files here: 
 - [x] [DIY Meetups README](https://hackmd.io/9LezZJieR5qlwFmn5hU9VA)
    - [x] [Requesting Funds](https://hackmd.io/bOR3w0GFTEiv2Virri1pXA)
    - [x] [Getting Started Guide](https://hackmd.io/lZcGiCG5Tp6kybMNxTfoLg)
    - [x] [Event Formats Guide](https://hackmd.io/KMV4UdqETo-J3wEiX3LKhA)
    - [x] [Promotion Guide](https://hackmd.io/5SB0BuhnR5qNXznGQ4UWjQ)
    - [x] [Budget Guide](https://hackmd.io/uyNRhR7TQz65CaZApKUu0A)
    - [x] [FAQ](https://hackmd.io/HLPMFvP2TBqxmx33UPjIjw)

**Comment by amy-jung** [comment]
Elliot sent edited notes on the community chat 6/27

**Comment by ghettodev** [comment]
Links need to be relative from the files location:  
 - `Create a [budget](./Budget-Guide.md)`
not
 - `Create a [budget](community/meetups/meetups-en/Budget-Guide.md)`

Filenames should be lowercase:
 - `Create a [budget](./budget-guide.md)`
not
 - `Create a [budget](./Budget-Guide.md)`

Let's not link to any 3rd party dapp or product in the docs unless is it absolutely necessary. Projects come and go and anything we link to will have to be kept up-to-date. Always link to Awesome-MakerDAO instead. 

I removed: 

> - Short and Leveraged tokens [dYdX](https://dydx.exchange/)
> - Interest Rates [Compound Finance](https://app.compound.finance/)
> - Accounting and Settlement [Request Network](https://request.network/#/)

- No emdashes please. 
- Please don't mention RocketChat. 'our chat' or 'join us in #channel' is fine. 
  - Let's stick with 'in our chat' as opposed to 'on our chat'
- No exclamation points please. 
- Please make sure all docs are put through grammarly and prettier before review

@Davidutro can you or @aburban90 please make sure that the above suggestions are captured in the style guide and/or the editing guide if they aren't already?

Let's get these into a PR for a final pass.

**Comment by Davidutro** [comment]
Broke apart the doc 

Markdown files here: 
 - [x] [DIY Meetups README](https://hackmd.io/9LezZJieR5qlwFmn5hU9VA)
    - [x] [Requesting Funds](https://hackmd.io/bOR3w0GFTEiv2Virri1pXA)
    - [x] [Organizing & Executing](https://hackmd.io/lZcGiCG5Tp6kybMNxTfoLg)
    - [x] [Event Formats Guide](https://hackmd.io/KMV4UdqETo-J3wEiX3LKhA)
    - [x] [Promotion Guide](https://hackmd.io/5SB0BuhnR5qNXznGQ4UWjQ)
    - [x] [Budget Guide](https://hackmd.io/uyNRhR7TQz65CaZApKUu0A)
    - [x] [FAQ](https://hackmd.io/HLPMFvP2TBqxmx33UPjIjw)

**Comment by ghettodev** [comment]
Waiting on IA review.

**Comment by Davidutro** [comment]
Cleaning up docs, will ping Amy once they are ready for edit

**Comment by Davidutro** [comment]
Submitted all PRs

**Comment by ghettodev** [comment]
FYI: If you are closing issues in github, please close them in the Issue page itself with a description of the solution. That will move things automatically in the kanban board. Dragging things in the board won't close associated issues.
