### ISSUE TITLE
grants link is broken

### ISSUE THREAD

**Issue by seamoonm** [makerdao/community#1078]
**Describe the bug**
https://community-development.makerdao.com/en/funding/grants/ brings up a 404 error

**To Reproduce**
1. Go to https://community-development.makerdao.com/en/funding/grants/

**Expected behavior**
Arrive at a grants page

**Screenshots**
<img width="1014" alt="Screen Shot 2021-01-06 at 5 16 05 PM" src="https://user-images.githubusercontent.com/74146393/103791587-e7166400-5042-11eb-9e9b-752a214dd73b.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac Mojave 10.14.5
 - Browser [e.g. chrome, safari] Chrome

**Comment by twblack88** [comment]
File away under #908  please and thank you 🙇

**Comment by amy-jung** [comment]
I noticed because we have the naming convention as "development-grants" : https://community-development.makerdao.com/en/funding/development-grants 

@seamoonm how did you end up in that link?

**Comment by patrick-j-govalpha** [comment]
closing legacy issues
