### ISSUE TITLE
Calculation of Stability Fee in FAQ

### ISSUE THREAD

**Issue by Chaology** [makerdao/community#109]
Some inconsistency and issues of the calculation of the stability fee in the [FAQ](https://github.com/makerdao/community/blob/master/faqs/stability-fee.md).

Here, it displays the simple interest formula (which should be the correct estimation). but uses continuous compounding interest in the actual calculation, which yields higher interest.

> ### How do I calculate the impact of variable Stability Fees?
> You can use this simplified formula to determine accrued Stability Fees:
> 
> ((Borrowed DAI * (1 + Current Stability Fee in decimal format)) ^ (Age of Debt in days/365)) - Borrowed DAI) = Total Stability Debt owed in DAI
> 
> The fees on a 10,000 DAI debt over the course of 31 days at 5.0%:
> 
> (10000 x (2.7183...) ^ (5.0%*(31/365)) - 10000 = 42.474 DAI
> And at 10.0%:
> 
> (10000 x (2.7183...) ^ (10.0%*(31/365)) - 10000 = 85.2937 DAI

Instead, it should be:

```
10000 * (1 + 0.05)^(31/365) - 10000 = 41.524 DAI
10000 * (1 + 0.10)^(31/365) - 10000 = 81.277 DAI
```

Related to that, I feel the intro of [Euler's number and continuous compounding interest](https://github.com/makerdao/community/blob/master/faqs/stability-fee.md#formulas) in the FAQ is not necessary and somewhat misleading. 

> **Formulas:**
> Where:
> 
> A = Interest
> 
> P = the principal investment amount (the initial deposit or loan amount)
> 
> r = the annual interest rate (decimal)
> 
> n = the number of times that interest is compounded per year
> 
> t = the number of years the money is invested or borrowed for
> 
> e = Euler's number
> 
> P (1 + r/n)^nt - P = A: Annual Compounding
> P (1 + r/n)^nt - P = A: Monthly Compounding
> P (e)^rt - P = A: Continuous Compounding
> 
> Calculated with annual compounding, the future Stability Fee is:
> 100,000 × (1 + (12.5% / 1)) ^ (1 × 1) - 100,000 = 12,500 DAI
> 
> Calculated with monthly compounding the future Stability Fee is:
> 100,000 × (1 + (12.5% / 12)) ^  (12 × 1)  - 100,000 = 13,241.60 DAI
>
> Calculated with continuous compounding the future Stability Fee is:
> 100,000 × 2.7183... ^ (12.5% × 1) - 100,000 = 13,314.94 DAI
> 
> The difference between annual and continuous compounding fees on a 100,000 DAI debt, at 12.5% APY, works out to about 814.94 DAI. Let's take a look at a couple more examples of how a stability fee gets calculated in practice.

It may make readers think the system use the third one to calculate the real interest rate, and they will be paying higher interest than the nominal annual interest rate.

**The Stability Fee is the system is the nominal interest rate of the first year and was set internally by secondly compounding to approximate.** 

Take the current 16.5% stability fee as an example, the actual interest rate in the code is calculated by converting it into secondly compounding. 

Secondly compounding Interest of 16.5% is:

`1.165^(1/31536000) = 1.00000000484275391259066490345903
`

As you can see in the converted HEX value: `33b2e3ce3056b436e9984c7`  [here](https://etherscan.io/tx/0xf0b6a4187fde63b239a85764cdfe5e1246c8e6f3ec2e2f09965003ea16544f02#eventlog).

And vice versa.

` 1.00000000484275391259066490345903^31536000 gives 1.165`

Therefore, the simple interest calculation is actually a better approximation of the stability fee. 
The Continuous Compounding doubles the calculation and undoes the approximation, it is suggested to be removed.
  
Note that the interest rate is only **approximated annually** in the first year, onwards it is going to be **accumulated secondly**. But that is fine, as the first annual interest rate is generally what people perceive as the stability fee.

The second year will be:
1.00000000484275391259066490345903^(31536000*2) - 0.165 = 19.225%

**Comment by Davidutro** [comment]
Reaching out to Devs to confirm this :)

**Comment by Davidutro** [comment]
![image](https://user-images.githubusercontent.com/40721951/60376100-9304db00-99da-11e9-993d-0345d9e78101.png)


Still trying to understand how to better this section. Lev says in MCD the Stability Fee is calculated differently. Trying to wrap my head around the idea that our discrete secondly compounding interest actually works out to be the same as a simple interest calculation within the first year.

**Comment by Davidutro** [comment]
We decided to keep the Stability Fee FAQ the same as it is now. We will update it for the MCD launch. 

Although the SF FAQ is not perfect in describing how the SF works we can do the work of adequately describing it for MCD.
