### ISSUE TITLE
CDIP 41 - DAI LatAm Action Groups Extension 2

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#1133]
**Title**: DAI LatAm Action Group Renewal 2
Feb-Apr

**Leads**(Rocketchat handles:):

Mariano Dipietrantoni, @mariano.dp
Nadia Alvarez, @Nadia
Caio Vicentino, @caiovicentino, BZ
Felippe Percigo, BZ
Jose Bell, @claudio00, CO
Daniel Ballesteros, @daniel.ballesteros, CO
Luis Lozada, @lozadaluis12, VZ
Alejandro Fernandes, @alefcripto, VZ
Diego Ortiz Mayorca @Saludiego201, VZ

**Advisor**:
@Davidutro 

**Links**: 
[GitHub Issue #670: CDIP 24 - Original Dai LatAm Action Groups](https://github.com/makerdao/community/issues/670)
[CDIP 37 - DAI LatAm Action Groups Extension 1](https://github.com/makerdao/community/issues/992)
[Google Doc with the draft proposal](https://docs.google.com/document/d/122Hc5ZAjh769UaiARE2TfnrGnqDLoBUqIGCmvnxy3P8/edit#)
[Brazil Created Content Sheet](https://docs.google.com/spreadsheets/d/1tfznW2CFo7bJM-qoSTtAqY7lWZYmoO7cT-DTzGMQ7CY/edit?usp=sharing)
[Venuzuela Created Content Sheet](https://docs.google.com/spreadsheets/d/1tfznW2CFo7bJM-qoSTtAqY7lWZYmoO7cT-DTzGMQ7CY/edit?usp=sharing)
[ETHLATAM Discord](https://discord.gg/z5d4Mp5BE9)

Brazil Socials:
Telegram - https://t.me/MakerDAObr - (1000 followers)
Twitter: - https://twitter.com/MakerDAObr - (393 followers)
Medium - https://medium.com/@MakerDAObr - (76 followers)
Instagram - https://www.instagram.com/makerdaobr - (662 followers)

Venuzuela Socials:
Twitter: https://twitter.com/DaidefiVzla (followers: 1053)
Instagram: https://www.instagram.com/daidefivzla/ (followers: 301)
Youtube channel: https://www.youtube.com/channel/UCu6MWQGUjspWT42AjF75_Iw (95)
Telegram: https://t.me/DaiDeFiVzla (group members:221)
Medium: https://makervenezuela.medium.com/ (followers: 21)

Columbia Socials:
Twitter: https://twitter.com/DaiColombia (followers: 22)
Telegram: https://t.me/joinchat/Q5E6854Obz3RFiBE(members: 20)
Instagram: https://instagram.com/dai.colombia?igshid=1g694jl6t8pud

**Proposal abstract**:
1. Continue on with the same work being done 
2. Crypto community contests (art, blogs, memes)
3. Dai Action Groups Branding creation
4. Renews funding from 02/01/21 - 04/31/21

**Proposal**:

![Proposal1](https://user-images.githubusercontent.com/40721951/107067791-ccecb480-67ad-11eb-8977-cd7d3e28fac8.png)
![Proposal2](https://user-images.githubusercontent.com/40721951/107067916-ee4da080-67ad-11eb-9453-f41a9185f025.png)
![BZ Section](https://user-images.githubusercontent.com/40721951/107077165-7a65c500-67ba-11eb-9a39-dff311bbcd29.png)
![VZ Section](https://user-images.githubusercontent.com/40721951/107077797-5f478500-67bb-11eb-8f45-6ea8157c611e.png)
![VZ Section2](https://user-images.githubusercontent.com/40721951/107078097-d715af80-67bb-11eb-8bb4-26b0582fb663.png)
![CO Section](https://user-images.githubusercontent.com/40721951/107078249-0b896b80-67bc-11eb-9f61-ab9093fdf887.png)
![Budget](https://user-images.githubusercontent.com/40721951/107081084-25c54880-67c0-11eb-8713-668e70228b5a.png)

**Comment by Davidutro** [comment]
Jose Daboin is working with Luis on Educational videos and will invoice as an expense to the Educational Resources budget for the VZ team.

**Comment by Davidutro** [comment]
Funding was approved by the CDIP approval committee

**Comment by Davidutro** [comment]
## Notes

### DAG Brand Development

![image](https://user-images.githubusercontent.com/40721951/116568054-2c062500-a8d6-11eb-94ae-7ad818ed29f7.png)
![image](https://user-images.githubusercontent.com/40721951/116568077-31636f80-a8d6-11eb-93b7-66b7d31c5178.png)
![image](https://user-images.githubusercontent.com/40721951/116568134-3aecd780-a8d6-11eb-9e61-19a0cbaa11e7.png)
![image](https://user-images.githubusercontent.com/40721951/116568174-45a76c80-a8d6-11eb-98a5-998a6abe877c.png)
![image](https://user-images.githubusercontent.com/40721951/116568202-4b04b700-a8d6-11eb-8a48-f24884697905.png)
![image](https://user-images.githubusercontent.com/40721951/116568247-52c45b80-a8d6-11eb-930b-fa2e81d23a9e.png)
![image](https://user-images.githubusercontent.com/40721951/116568275-5952d300-a8d6-11eb-8fec-8deb01a2f408.png)
![image](https://user-images.githubusercontent.com/40721951/116568344-68398580-a8d6-11eb-99dd-2ef8421b9d74.png)
![image](https://user-images.githubusercontent.com/40721951/116568374-6cfe3980-a8d6-11eb-88a2-6b480b4e1aeb.png

## Questions

### How did the last 3 months go? did the team reach the goals set out in the proposal?

Luis Vz:
 We found powerusers for Telegram.
 Expanding defi interest in the chats.
 Many more Demo videos.
 We started a Tiktok and new Brand (unifying the DAG)
 We have had good cross-promotion with artists, dealing in Dai.
 
Jose Bell & Daniel Ballesteros CO:
Telegram p2p Group is working nicely (10 successful trades, ~50+ people)
Instagram: We hit our goal
Telegram: ??
Unified ourselves under one branding
Twitter: not much growth, low momentum.
Doing Dai rewards for translations.
We invite people to learn how to trade services for Dai.

![image](https://user-images.githubusercontent.com/40721951/116565858-3cb59b80-a8d4-11eb-8815-e4d1d37fe50e.png)
![image](https://user-images.githubusercontent.com/40721951/116566021-5eaf1e00-a8d4-11eb-9c41-0f44275653ab.png)
![image](https://user-images.githubusercontent.com/40721951/116566146-7f777380-a8d4-11eb-84f6-8fcbb8f32e22.png)
![image](https://user-images.githubusercontent.com/40721951/116566216-91591680-a8d4-11eb-817c-671dcca1b859.png)
![image](https://user-images.githubusercontent.com/40721951/116566275-9f0e9c00-a8d4-11eb-9def-5c7ee18721e3.png)
![image](https://user-images.githubusercontent.com/40721951/116566322-a8980400-a8d4-11eb-8258-5b817c531c10.png)

- Twitter suffered because Columbians use twitter mostly for politics, so there is not a well-developed crypto twitter circle in Columbia. From all the people who joined the p2p group, they all came from Instagram.
- We want to put a face to people who are using Dai.

### What documentation was produced about the countries?

All:
[DAG Notion Hub](https://www.notion.so/DAGs-37b749adba2044d3a5cf1a727f3e1c00)

Vz:
[Forum Post 3-month Recap](https://forum.makerdao.com/t/makerdao-venezuela-round-up-february-april-2021/7708)

Co:
Deck was created for each month.

Bz:
?

### How did the NFT idea go?

Luis:Planning to do contest, but in the middle of the planning the Maker community art contest showed up. Our thinking was why not make this contest more global, so we translated the page and shared on our channels.

### How did the p2p marketplace idea go?

Luis: We had a group for Dai announcements, but we started seeing lots of people in Vz using xDai. Alejandro took the initiative to be the admin and facilitator of the group. We helped 7-8k Dai get into the hands of our community.

p2p groups are separate per country, but they are linked to help each other.

### How did your teams work with each other?

- New group(CO) used existing resources to build up their own offerings. VZ group helped CO heavily.
- CO helped VZ with translating blogs.
- BZ not much, since the language is different.
- Luis jumps in often to converse in channels across countries.
- p2p group coordination.
- Working together to build up new teams.

### What's the future for these teams?

Continuing onto joining the appropriate Core Unit.

Kathleen: GRO will be working closely with MKT. We will try to be unified in our efforts.

### Kathleen: What's the setup of the Translation program?

Spanish translations are done on the blog and the forum are an initiative started a long time ago. The program Jose made is a marketing strategy to earn Dai while bridging the language barrier.

Translation of the blog is independent from what Jose mentioned.

## Recording

TBD

**Comment by amy-jung** [comment]
Really awesome growth!
