### ISSUE TITLE
Translation Section needs Review

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#114]
Follow links on Translation section: https://hackmd.io/fPLyYXWRQe2kSVJD2fg1fg?both#translations

Approval pending from: @ghettodev and @reuptaken

**Comment by Davidutro** [comment]
I reviewed all four documents today. Marcin made edits on a couple of the documents last night.

Stats and Transparency dashboard is in limbo, pending Rich's input.

**Comment by reuptaken** [comment]
How should I approve this?

**Comment by amy-jung** [comment]
> How should I approve this?

For now, you can put a check next to your name in the hackmd doc

**Comment by ghettodev** [comment]
Moving back into `Ready for Review`, I don't think this is done. 

Also, I turned on automations so tickets will show up in Done when they are closed.

**Comment by Davidutro** [comment]
added the changes to the Translation FAQ to the HackMD markdown version. I also fixed some minor errors.

**Comment by ghettodev** [comment]
Links need to be relative from the files location:  
 - `Create a [budget](./Budget-Guide.md)`
not
 - `Create a [budget](community/meetups/meetups-en/Budget-Guide.md)`

Filenames should be lowercase:
 - `Create a [budget](./budget-guide.md)`
not
 - `Create a [budget](./Budget-Guide.md)`

Let's not link to any 3rd party dapp or product in the docs unless is it absolutely necessary. Projects come and go and anything we link to will have to be kept up-to-date. Always link to Awesome-MakerDAO instead. 

I removed: 

> - Short and Leveraged tokens [dYdX](https://dydx.exchange/)
> - Interest Rates [Compound Finance](https://app.compound.finance/)
> - Accounting and Settlement [Request Network](https://request.network/#/)

- No emdashes please. 
- Please don't mention RocketChat. 'our chat' or 'join us in #channel' is fine. 
  - Let's stick with 'in our chat' as opposed to 'on our chat'
- No exclamation points please. 
- Please make sure all docs are put through grammarly and prettier before review

@Davidutro can you or @aburban90 please make sure that the above suggestions are captured in the style guide and/or the editing guide if they aren't already?

Let's get these into a PR for a final pass.

**Comment by ghettodev** [comment]
Will do another pass

**Comment by Davidutro** [comment]
submitted PRs for Translation Initiative pages

**Comment by ghettodev** [comment]
Numerous Translations Section Fixes

- don't use bold items as headers `**Project Snapshot:**`, it breaks the ToC paradigm
- no trailing spaces
- Quick-Start is not hyphenated
- No exclamation marks
- No curly quotes in markdown files
- 2 spaces, not 4
- multiple incorrect URLs, please validate relative links before submitting PRs
- inconsistent capitalization of headers throughout
- tense and syntax of stem sentences
- when referencing chat channels always provide a link
- never use absolute URLs for community portal content, it will break gitbook
