### ISSUE TITLE
Greenlight Polls 2021-02-15

### ISSUE THREAD

**Issue by LongForWisdom** [makerdao/community#1154]
[SB-LDB]
[FFT1-DROP]
[GLM]
REINNO
[renDOGE]
[UNI-V2-COMP-ETH]
[UNI-V2-DAI-BAT]
[UNI-V2-DAI-COMP]
[UNI-V2-DAI-LINK]
[UNI-V2-DAI-UNI]
[UNI-V2-LRC-ETH]
[UNI-V2-YFI-ETH]

**Comment by prose11** [comment]
On it!

**Comment by patrick-j-govalpha** [comment]
Closing legacy issues
