### ISSUE TITLE
Create PR on Meetups Kit while reviewing Elliot's edits

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#116]
I downloaded the .docx file and will add changes that I agree with to the Master meetup kit. 
Afterwards, I will break the document into 6 documents which will replace the one. 

General Info (landing page)
        - Requesting Funds
        - Planning and Organizing
        - Formats & Activities Guide
        - Promotion Guide
        - Budget Guide

**Comment by Davidutro** [comment]
Before creating a PR I need to get the HackMD files reviewed. 

I created the HackMD files for the broken up Meetups DIY Kit here:

>    - ☐ [DIY Meetups README](https://hackmd.io/9LezZJieR5qlwFmn5hU9VA)
        - ☐ [Requesting Funds](https://hackmd.io/bOR3w0GFTEiv2Virri1pXA)
        - ☐ [Organizing & Executing](https://hackmd.io/lZcGiCG5Tp6kybMNxTfoLg)
        - ☐ [Event Formats Guide](https://hackmd.io/KMV4UdqETo-J3wEiX3LKhA)
        - ☐ [Promotion Guide](https://hackmd.io/5SB0BuhnR5qNXznGQ4UWjQ)
        - ☐ [Budget Guide](https://hackmd.io/uyNRhR7TQz65CaZApKUu0A)
        - ☐ [FAQ](https://hackmd.io/HLPMFvP2TBqxmx33UPjIjw)

p.s. I will be going over them in the next day or two to try to remaster them. The Event Formats Guide in particular needs a refresh.

**Comment by ghettodev** [comment]
Multiple Fixes for meetups
 
 - don't use bold for header `**Project Snapshot:**` it breaks the autogenerated ToC pattern
 - renamed diy-meetups-faq.md to faq.mq. we don't need to distinguish them
 - Inconsistent header capitalization throughout
 - No ampersands please
 - 2 spaces not 4
 - removing old meetup kit doc
 - no exclamation marks
 - no ordered list unless the order matters
