### ISSUE TITLE
Community Call Documentation

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#1163]
# Community Call Documentation

## Overview

The community call, which has been running every Tuesday for the last three years, has been used to give the public a venue to receive MakerDAO updates, ask questions, request guests and topic coverage, and get exposed to projects happening around MakerDAO.

The call has evolved over the years, becoming more and more focused on guests and interesting topics rather than weekly updates. As of February 2021, weekly updates still happen occasionally, as fall-back programming when there are no scheduled guests or topic discussions.

With the evolution of MakerDAO, we've seen a number of new calls pop up, as well as a publication that takes care of weekly updates. Moving forward, the community call needs a clear vision, purpose, and strategy in order to ensure that value is being delivered to the public.

There are less than 100 weekly viewers on average, so this is a very small crowd. Of course, the size of the crowd matters less than who is watching and making sure these meetings are recorded and available for later viewing.

## Purpose

The community call expands the scope of the content offered by MakerDAO to stakeholders and the public.

It gives Dai and Maker integrators a platform to present their products and seek feedback.

It gives stakeholders and the public a series to tune into for deeper information, and exposure to projects happening around MakerDAO that they otherwise would not have known about.

## Vision

The community call will be completely run by a TBD Core Unit, and will act as a hub for a number of different formats that individuals can engage with. The call will surface interesting projects, current events, stories, and more.

The vision can be summarized as follows;

- Find which team this call belongs with, and integrate it into that team's operations.
    - Community Development?
    - Governance Communications?
    - Marketing?
- Multiple dedicated community hosts.
- Call guests every week.
- Move away from weekly updates, focus more on Q&A, requests, guests, and deep dives.

## Strategy

- Adjust the programming to avoid weekly updates, and have near 100% guest and discussion coverage.
- David to discuss where this call lives with Anna(comdev), and go from there to transition ownership of the call.
- Until a contributor is hired or comes about naturally, David will continue leading the call.

### Schedule Guests

Scheduling guests happens through a manual process of outreach via email or dms.

To keep track of scheduling, we use the [Community Call Guests Hackmd Doc.](https://hackmd.io/nDvYF6CyT8Oq32dOjvhYOg) This doc helps us keep the lineup visible to the public. It is also used to collect ideas for potential guests.

At the moment (02/2021), David.utro@makerdao.com & [Davidutro's Maker Forum account](https://forum.makerdao.com/u/davidutro/summary) are the primary contact points for scheduling guests. Anyone can refer people to that email, and David will arrange the ideal date for the guest.

Anyone can make a guest or topic recommendation on the [forum thread.](https://forum.makerdao.com/t/make-a-guest-or-discussion-topic-recommendation/6613)

### Post the Event Page

The event page should be posted the Tuesday prior to the call. 
_Best practice is to create the next event page directly after the current week's call._

At the moment (02/2021):
- [Crowdcast](https://www.crowdcast.io/makerdao) is used to set up the event.
- Use [Canva](https://www.canva.com/) or a similar platform to create the Thumbnail.
- Event page link and details are posted to the Maker Forum, Telegram, Rocketchat, Reddit, and Twitter.

If needed, an alternative host can setup the community call through zoom, google meets, or any other alternative video-conferencing platform. In this case, event details should be posted to the usual locations, with a notice that this week an alternative platform is being used.

### Promote the Call

[Templates](https://hackmd.io/D3kRCYuoRsehr-SlXHgvpA)

On the day of the call, usually an hour before, a link and brief description about the call should be posted to a number of places:

- [Twitter](https://twitter.com)
- [Reddit](https://www.reddit.com/r/MakerDAO/)
- [Rocketchat #general channel](https://chat.makerdao.com/channel/general)
- Telegram Groups: [Defi](https://t.me/de_fi) | [MakerDAO](https://t.me/makerdaoofficial)
- [MakerDAO Forum, under the community call category](https://forum.makerdao.com/c/community-calls)

### Host the call

Here are some useful heuristics to hosting public calls.

- Have a preamble.
- Assume some attendees have no idea what the call is about, or what the usual agenda is.
- Encourage a laid-back atmosphere.
- Volunteer to relay questions from the chat.
- Extend an invitation to people to come on the mic or video if they would like to speak directly.
- Smile!
- Think about questions that the audience would want to ask, and ask them yourself.
- Stories are powerful.
- When a guest is on, treat the call like a flowing conversation.
- Address people watching the recording.
- Mention where to find resources.
- Mention how to get connected to the community.
- Mention any high-priority opportunities.

### Upload the call

Once the live event finishes, 

- Download the recording.
- Upload to Youtube.
- Add it to the "Community Call" playlist.
- Update the [Community Calls Listing thread](https://forum.makerdao.com/t/community-calls-listing-2021-edition/6617)

**Comment by patrick-j-govalpha** [comment]
Closing legacy issues
