### ISSUE TITLE
Create a Reviewer's Guide for the Contributing Section

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#117]
The contributing section should improve contributor experience and onboarding. Guides should remove the barriers for community members to be part of the team, improve community resources, give and receive feedback, and grow the MakerDAO community.

[Working Doc](https://hackmd.io/PxQDuZ6mRvOUD8x7Q24YkQ?both)

[Project Planning Doc](https://hackmd.io/@rawhaus/rJX6JE3jH)       

 - It should include elements of style, tone, voice, editing approval process
 - Build from [previous project document](https://hackmd.io/CTK3kaUzSQO7VuyuU4L2hA)
- Workflow
- Two separate sections between educational resources and initiatives
- Reference translations guide for the structure

**Comment by amy-jung** [comment]
Current flow: 
1. Start on Google Doc
2. Editing Markdown for final
3. Submit as Pull request

**Comment by amy-jung** [comment]
@aburban90 will take the first try

**Comment by ghettodev** [comment]
Please lean heavily on the current [Style Guide](https://github.com/makerdao/community/blob/master/contributing/style-guide.md) and reference heavily from the new Editing process/guide.

**Comment by Davidutro** [comment]
saw this Hackmd file, I think it's relevant. 

https://hackmd.io/CTK3kaUzSQO7VuyuU4L2hA

Can be a good base for creating the editing guide

**Comment by aburban90** [comment]
Working Doc: https://hackmd.io/PxQDuZ6mRvOUD8x7Q24YkQ

**Comment by amy-jung** [comment]
Closed with PR #482
