### ISSUE TITLE
Bounties Project Archive

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#1170]
Hello! If you're new to our "Archive" section, here's an explainer: 

While Community Development's programs supported by Maker Foundation comes to an end, the "Archives" issues provide insight to project/programs that the team had worked on. Perhaps you're interested in starting a project or program like this of your own, or perhaps you're just simply curious. Either way, our team members have collected documentation and relevant Github issues/threads for anyone to read about it.

-----

## Motivation

In the early days (~2019), bounties were used as a tool to incentivize and community contributions. We were also hoping that we would find new contributors, as well as have contributors learn more about Maker through the bounty.

## Summary

Bounties (ranged 10 Dai for content edits to 10,000 Dai at hackathons) were set up on various platforms (Bounties Network, Gitcoin, etc.) Bounties were being used for small and one off requests, mostly tied with hackathons as they would provide the audience that would take on these bounties.

The goals and initial research were summarized in [this bounties planning document.](https://hackmd.io/z__nbzNBSuibsBzswsQUkQ?both) The desired goals were:

**Long Term (Mission Orientated):** 
1. Design or find a bounty system that allows contributors from the community to **easily access and take on bounties.**
2. Source a pool of contributors that we didn't have direct access to before
    - Consider the possibility of use of multiple platforms to take advantage of their communities
3. Community members can propose potential bounties

**Short Term (Action Orientated):** Create a streamlined discoverable bounties workflow.

- Gather data and requirements
- A standard platform/process in place for microbounties. Create standard operation procedures around:
- Create a page in the contributor section for microbounties

## Role(s)

While we had three managing a chunky process, only one person is needed. He/She/They would be responsible for scoping and writing the bounty and posting them to bounty platforms or promoting through channels, and sharing with relevant audiences. This person may work with someone in Marketing to increase visibility to bounties.

## Related Links

Where we last left off: The team was looking to streamline the workflow of how the team would develop and post bounties to how interested bounty hunters would find open bounties.

- [This Planning Document summarizes it all](https://hackmd.io/z__nbzNBSuibsBzswsQUkQ?both)
- [The Github Epic outlining to-dos](https://github.com/makerdao/community/issues/264)
- [Gather Data & Requirements](https://github.com/makerdao/community/issues/358)
- [Standardize Current Processes](https://github.com/makerdao/community/issues/359)
- [Improvements to Current Processes](https://github.com/makerdao/community/issues/360)

## Lessons & Recommendations

In the end, we found bounties too difficult to manage because of the Goldilocks problem: 
- If the bounty was too specific, no one would take them on, and if they were too wide we would receive random bounties. 
- It required time and effort to scope the bounty well, yet if the content of the bounties changed or evolved at any point, the bounty itself would be stale. 
- If the bounty amount was too small, people wouldn't spend the time taking them on, but if the bounty was too large, we would get redundant submissions. Then people would get frustrated at working on something that was not accepted.

Perhaps there was a way we could have handled the process better or tried to get more visibility on these bounties, but we hardly saw bounties providing a long tail: converting potential community members to continued contributions. 

We ended up focusing more on contributor experience as a program rather than bounties (which is one form or tool). Additionally, we found the grants program + microgrants called Community Development Initiative Proposals to fill this need.

Most details are outlined in this document, but if there are further questions, you can reach out to Amy @amy-jung on Github or @itsamyjung on Twitter.

**Comment by patrick-j-govalpha** [comment]
Closing legacy issues
