### ISSUE TITLE
Portal Content Maintenance Documentation

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#1171]
## Description

This issue documents the Portal Content Maintenance process.

## Links

[2021 Q2 Maintenance Plan Excel Sheet](https://docs.google.com/spreadsheets/d/16wm1ry29qUb_IfQwvb8rYvXrjmMWYVv6Gvc0VyDNQ9E/edit#gid=0)
[Hypothesis Portal Suggestions Private Group(anyone with link can join)](https://hypothes.is/groups/Q4QYmy5D/portal-suggestions)

## Roles

**Lead:** Responsible for executing the Maintenance Plan, setting up the excel sheet, assigning reviewers, reviewing PRs, and more.

**Reviewer:** Submits PRs based on Hypothesis suggestions and their own review.

**Casual Contributor:** Uses [Hypothesis private group(group invite link)](https://hypothes.is/groups/Q4QYmy5D/portal-suggestions) to leave suggestions and corrections.

## Workflow

1. A week before a maintenance cycle begins a spreadsheet must be set up that lists the grouped sections or individual pages that need to be reviewed, along with special notes if they are necessary.
   - This is to be done by the Lead of the Maintenance Plan by duplicating the previous quarter’s sheet and updating it for the new cycle.
   - Special notes contain improvement requests, special considerations, “do not change” requests, and virtually anything the person needs to keep in mind when reviewing that row item.
2. The Lead is responsible for assigning reviewers to sections of pages found on the spreadsheet.
   - This gives the Lead one week to fill all the spots.
   - Pages can be assigned by section, to make it easier if you are only working with one or two reviewers.
3. Assigned contributors are given access to the spreadsheet by the Lead prior to the start of the maintenance cycle sprint.
4. Week one: Contributors are asked to complete their Pull Requests by the end of the week and to post the link to them in the spreadsheet.
5. Week two: The Lead goes through all Pull Requests and requests changes or marks them reviewed.
6. EOW2-into W3: Pull Requests get merged by the portal team.

### Suggestions

In perpetuity, people will be able to leave feedback on pages using the [Hypothesis extension.](https://web.hypothes.is)

- Install the extension.
- Join the [Portal Suggestions](https://hypothes.is/groups/Q4QYmy5D/portal-suggestions) group.
- Leave any feedback and suggestions in the group space.

### Initial Pull Request

At the end of each quarter, the Maintenance Plan Lead will find and assign one or two reviewers to help look through Hypothesis suggestions and create pull requests with changes.

### Review of Pull Requests

The Maintenance Plan Lead will do final reviews of Pull Requests, marking them reviewed, and ready to be merged.

### Merge of Pull Requests

The lead will work with the portal team to get PRs merged that are marked reviewed.

## Update Sitmap URLs Process

This will be useful for ensuring the excel sheet contains all the live pages.

Go to this link: 
https://github.com/makerdao/community/blob/gh-pages/sitemap.xml

**Comment by patrick-j-govalpha** [comment]
Closing legacy issues
