### ISSUE TITLE
Finalize IA for Portal

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#118]
https://www.plectica.com/maps/7Z9YXKR8F

**Comment by amy-jung** [comment]
Led by Alex singh and Jordan Jackson

As of 6/28/19:

1. Team page Removed
2. Integrate list of contributors into the project page as a more modest alternative
3. @ghettodev @Davidutro have mentioned moving/reframing/updating some parts of the project IA

**Comment by Davidutro** [comment]
Quick Update on IA:
Rich, Alex, and I have met to talk a bit about the landing pages for the "initiative" type of major sections. These include:
`Translations`
`DIY Meetups`
`Grant Program`
`Hackathons`
`Contributing`

We're standardizing what this page should include. Some changes are being made to the landing pages that already exist (ie: Translations & DIY Meetups).

HackMD: [IA for "Initiative" landing pages](https://hackmd.io/vDXzQC6FQp6bc542_cK_0g?view)

**Comment by ghettodev** [comment]
Let's call this finalized for now. We can move the process into ongoing maintenance and tweaking.
