### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by Saurabhbagh** [makerdao/community#1218]
**Describe the bug**
404 error on a webpage.

**To Reproduce**
1. Go to 'https://community-development.makerdao.com/en/contribute/content/'
2. Scroll down "to the end"
3. Click on 'Publishing Content'
4. See error "https://community-development.makerdao.com/en/resources/technical-content/publishing-to-repo-process/"

**Expected behavior**
Info about publishing content or a page that does not lead to 404.
**Screenshots**

**Desktop (please complete the following information):**
 - OS:  windows 10 
 - Browser chrome
 - Version 89.0.4389.90

[Bug Report.zip](https://github.com/makerdao/community/files/6175960/Bug.Report.zip)

**Comment by patrick-j-govalpha** [comment]
closing legacy issues - docs no longer supported
