### ISSUE TITLE
FAQ IA needs reorganizing

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#122]
Currently in navi by language

**Comment by ghettodev** [comment]
I'd like to give some thought to whether we need a series of FAQ specific nav items under each language or if we can simply list the languages as we have all the FAQs rolled up into the readme's for each one anyway. 

**Current**

- [MakerDAO FAQs](faqs/README.md)
  - [English](faqs/README.md)
    - [Collateral Debt Positions](faqs/cdp.md)
    - [Dai](faqs/dai.md)
  - [Español](faqs/es/README.md)
    - [Dai Stablecoin](faqs/es/dai.md)
    - [Liquidación](faqs/es/liquidation.md)
  - [Français](faqs/fr/README.md)
    - [Dai](faqs/fr/dai.md)

**New**
- [MakerDAO FAQs](faqs/README.md)
  - [English](faqs/README.md)
  - [Español](faqs/es/README.md)
  - [Français](faqs/fr/README.md)
  - [Italiano](faqs/it/README.md)
  - [日本語](faqs/ja/README.md)
  - [한국어](faqs/ko/README.md)
  - [Polski](faqs/pl/README.md)

We also need to give some thought to how the portal will look once we have a sufficient weight of translations. Language specific subnavs under each item feels onerous. It would be best to have a header nav item that just allows people to pick their language.

**Comment by amy-jung** [comment]
@ghettodev will delete subcategories on the navigation menu (Gitbook is set up so that subcategories still exist on the right panel in each section per page) and the left navigation menu will only show languages.

**Comment by ghettodev** [comment]
- added new meetups and translations pages
- removed individual faqs from each language dropdown, lets use the readme's for navigation
- added readme's to summaries and transcripts
- removed summary and transcripts from the dropdown navs
