### ISSUE TITLE
Meetup Grants Program Documentation

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#1222]
# Meetup Grants Program Documentation

## Overview

The Maker Foundation launched the Meetup Grants program in February of 2019, with a vision to use small Dai grants to incentivize high-quality grassroots educational meetups around the world. These meetups would be a catalyst for educating and attracting potential users, active community members, and contributors while also giving passionate individuals an opportunity to earn an honorarium by organizing events that teach about Dai, MakerDAO, DeFi, and Ethereum.

## Vision

Dozens of high-quality physical meetups every month, in numerous countries, exposing individuals to technology that has the potential to transform their communities.

The program serves three purposes; 

1. To give passionate individuals around the world an opportunity to host educational events about MakerDAO.
2. To let those events be a funnel to attract more users, contributors, and active community members to MakerDAO.
3. To expose individuals to Dai and Defi in as many countries as possible.

## How-to Relaunch a version of this program

1. Create an informational page for the program.
2. Set up an email to handle application reviews and Request.Network invoices from.
3. Create an Application Form
4. Create a Post-Event Form
5. Set up a google sheet to track form data.

## Our Workflow

![image](https://user-images.githubusercontent.com/40721951/112021207-6aeed100-8b07-11eb-843a-1600cbc6364e.png)

### Application Form

1. What is your name? *
2. What is your e-mail?  *
3. What is the name of your event? *
4. Is this a Virtual meetup? *
Yes/No
5. What Country are you hosting your meetup in? *
Type "virtual" for Virtual Meetups.
6. What is the anticipated date for your meetup? *
mm/dd/yyyy
7. Please provide a description of your meetup in three to five sentences. *
8. Tell us something unique about your region and why you believe Dai or Maker would be impactful here *
Type "virtual" for Virtual Meetups.
9. What type of meetup is this? *
check all that apply; Select an option
For Academics
For Beginners
For Businesses
For Developers
10. If you answered "Other" please describe the event type. 
11. How long is this meetup? *
12. What is the agenda for this meetup? *
13. Please list the names of the speaker(s) that will be presenting at the event. *
14. Will you be demoing or using any dapps or other crypto technology? If so, what are they? *
eg: Burner wallets, Kickback, Bounties.network, PoolTogether, etc.
15. Are there any other sponsors for this meetup? *
16. Are you planning to monetize the event through ticket sales, raffles, contests, etc? 
If yes, please provide details and expected revenue. *
17. Please provide an itemized breakdown of all costs associated with the event: *
18. Approximately how many people do you expect to attend this meetup? *
19. How do you plan to collect signups? *
20. What is your plan for recording and sharing the meetup? *
21. What is your plan for promoting and advertising the meetup? *
If you need help, check out our meetup promotion guide in the community development portal.
22. Are you providing food or drinks at this meetup? *
Yes/No
23. Please provide links to any previous events you have held. Videos, announcements, blog posts, social media engagements, etc. 
24. Please submit your Request Network Invoice Link here *
[How-to create a Request Network Invoice]([https://request.network/en/invoicing/getting-started/](https://request.network/en/invoicing/getting-started/))
25. How did you hear about the meetup grant program? *

### Post-Event Form Questions

1. What is your name? *
2. What is your email? *
3. What was the name of your event?  *
Use the same name as you did on the initial application
4. What was the date of your event? *
mm/dd/yyyy
5. How much Dai were you granted for this event? *
6. How many people attended the event? *
Please be as precise as possible 
7. Did the event demo or use any dapps or other crypto tech? If so, tell us what you used and your experience with it. 
eg: Bounties.Network, PoolTogether, Uniswap, Kickback, etc..
8. Was the audience particularly engaged or receptive to any presentations or activities? *
9. How much time did you spend organizing the event? *
10. What was the total financial cost of this event? *
11. What was the feedback from the audience members after the event? *
12. Please provide links to social media mentions of the event. Your posts and those of the attendees. *
13. Please provide links to online videos of the presentation and any relevant slides *
14. Did anything go not-as-planned? * 
Select an option 
If you answered "Yes" to the above, please describe what did not go as planned 
15. What would you have done differently if you could redo the event? *
16. Are you considering hosting a meetup again in the future? *

### Links

[Final Report PDF]()
[Email Templates](https://docs.google.com/document/d/e/2PACX-1vTkGyUkqR4APDSYsbmM2_UNRg8O_MQ7TOrn6B8GVOQrBj9OSbo8_UQV9jxtYKsVXaSfExwZZWZ67cpT/pub)

**Comment by patrick-j-govalpha** [comment]
Closing legacy issues
