### ISSUE TITLE
Missing YAML headers creates formatting challenges on mobile

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#1223]
**Describe the bug**
The translations module likes to battle with the breadcrumbs on mobile. Shout out to @Davidutro for catching a bug. 

**To Reproduce**
1. Go to https://community-development.makerdao.com/en/learn/governance/module-dciam using any mobile browser
2. Behold the majesty of the page, yet the conflict in it's formatting. 
![Translation versus breadcrumbs](https://user-images.githubusercontent.com/8991325/112180142-849c2100-8bb8-11eb-81a7-87a7bb172dec.jpeg)
The top of the page 

![Formatting DCIAM page](https://user-images.githubusercontent.com/8991325/112180122-80700380-8bb8-11eb-8055-65055d4557dd.jpeg)
the formatting continued.

**Comment by patrick-j-govalpha** [comment]
Closing legacy issues
