### ISSUE TITLE
CDIP Program Archive

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#1225]
# CDIP Program Archive

## Motivation

Comm-Dev had lots of smart people with great ideas; in order to frame projects, we deployed a straightforward framework for project planning named CDIPs (community development initiative proposal). A framing tool for anyone interested in proposing new MakerDAO community initiatives or resources. Upon acceptance, they would receive funds to deliver.

## Summary

At a high-level CDIPs were simple: fill out a doc, get feedback to approve the project, execute on a cadence, and deliver (submit, execute, complete). This process took most of 2020 to get right and went through [one major revision](https://docs.google.com/presentation/d/1krg2s_MAZalaXcvhCD_gPc55cWMAQTp07XYmQpSQQo0/edit). You can see the documentation on [the portal](https://docs.google.com/presentation/d/1krg2s_MAZalaXcvhCD_gPc55cWMAQTp07XYmQpSQQo0/edit) including a [visual guide](https://community-development.makerdao.com/en/funding/community-projects/cdips-visual) for the end-to-end process. 

  Some key assumptions and design decisions were: 
 - The template should be easy to fill out.
 - Each CDIP should punch above its weight class.
 - CDIPs need to provide impact or some way to measure the result on delivery.
 - CDIPs need a specific, measurable idea with somewhat clear estimated timelines.
 - CDIPs are not for research or already completed work.
  
## Role(s)

- Contributor (Proposal Owner): Creator of the proposal and the driver of the project. Leads meetings and communication, sets other contributor roles, goals, timelines, and expectations.
    - Contributing Team: Contributes responsibilities or expertise to the owner or lead.
- Adviser: Supportive role that can help scope, follow up, brainstorm, test, and keep Community Development abreast of communications and project updates.
- Approving Group: Evaluators reviewing and approving proposals. A mix of Maker Foundation employees and seasoned contributors of the community.
 
## Related Links

- [CDIP label](https://github.com/makerdao/community/issues?q=is%3Aissue+label%3Acdip)
- Here is a deck about the [final highlights of the program](https://docs.google.com/presentation/d/1WZ8DFNhncywxeEj3ETDcOCfcGCnnvtPhcYaWgNrQTtk/edit#slide=id.g84608da28d_0_0)
- [The template](https://docs.google.com/document/d/1lF8mNuomrguIS3lnvqTomS4NdON40nuyKRbLS6ZkMoA), this doc is also an issue template in this /community github repo.
    - [Decision grid](https://docs.google.com/document/d/1rOTi9J_X9VkWVsIfm0tkd3bwDuPscfuKYSRJFXuO0-A/edit#) for advisers to add to any new CDIP idea.
    - Granular [what to expect doc](https://docs.google.com/document/d/19Y84_yGRHmhNDYJpL511ewhm4IMJxEdOoAVvjqiImn8/edit#heading=h.9njpgnz7y42t) for every stage and the status applicable in any CDIP's lifecycle.

## Highlights

🎫 292 Badge Redemptions
📹 [Comm-Dev Demo Day video ](https://www.youtube.com/watch?v=vkPaT_7EEbs&list=PLLzkWCj8ywWP1NPbyf69PUUCus_KsG7FI&index=107)
👥 [Community personas presentation](https://docs.google.com/presentation/d/1dCO5lBjduSQHwUr588j6T1Pl6Cx9r9BF-GKz0-nXyLI/edit#slide=id.gabcca7034c_0_14) from CDIP 36
🏪 [Dai-rectory page](https://community-development.makerdao.com/en/learn/merchant-directory)
🎙 [Voices of the DAO](https://open.spotify.com/show/2oQkhWmMhbfARAjJBdhcgt)

Program details:
- 41 Total CDIPs
  - 27 Completed | 2 still executing
  - 11 Paused, archived, VOID, Replaced
  - 28 Unique Contributors
  - 8 advisers
  - Avg time for completion: ~ 2 months
  - Avg time for approval: 3 weeks 
  - Program Lifetime: One year
  - Extensions: 3 (Transparency dash, Badges, and Marketing)

## What Worked

- When the idea was clear, and the milestones were obvious, it was a really easy call to make for the committee.
- Lots of ideas came through the pipeline; humans of MakerDAO are creative!
- We learned a lot and supported 11 projects that grew from or were adjacent to this program.
- We compiled a nice set of questions [to evaluate any project](https://docs.google.com/document/d/19Y84_yGRHmhNDYJpL511ewhm4IMJxEdOoAVvjqiImn8/edit#bookmark=id.7c5y8dl6y7yy).

### Evaluating grants from the committee

It's worth unpacking all the work the team did to understand how to fund an idea or not: 

- Feasibility (Do the qualifications match the bandwidth?)
- Dependencies (Does this block anyone or other projects? )
- Flextime/Slack (What does this budget look like at 3x the amount? Where are the scope creep risks?)
- Feedback (Is there feedback already, or does it need more?)
- Promotion/Sharing (Plan for telling the community about the finished plan?)
- Additional Resources (Can we route additional people to the proposal?)
- Maintenance costs (Is there a plan to maintain or hand off maintenance?)

A short note on impact, the team spent a lot of time trying to think through the impact of CDIPs. The hope is that they would punch above their weight class.

| Impact Estimate | Description | Numbers |
| -------- | -------- | -------- |
| S     | Small Win     | 5-50 people     |
| M     | Medium Win     | 50-500 people  |
| L     | Large Win     | 500-5000   |
| XL     | Extra Large Win     | 5000 +   |

## What didn't?

- The adviser role, though completely well-meaning, created far too much telephone. Contributors would focus on the process instead of executing their plan, which added more confusion than it clarified. 
    - They often ended up serving as a quasi-owner to projects more than a process guide. 
    - It might have been easier to onboard more of them, creating a separation from the approving committee where many advisors would own updates but also approve projects they advise.
    - It might have also been easier to have one person serve in a dedicated advisor role, responsible for documentation, execution, and promoting projects.
- Group decisions are tough, and settlement by committee is difficult. It takes practice and needs a framework that gets used constantly.
- We needed **ONE** central platform for most of the activity. We used Github, but Github is for software, not project updates. Engagement fell off pretty quickly after approval.
- CDIP’s are for ideas; they needed a space for iteration. An open call and a chance to meet with approvers on a regular cadence.
- We could have telegraphed to Governance and the wider community more often. Posting "state of CDIPs" to the forum and Reddit etc.
- Framing a project as a whole and attaching a value was hard. Contributors would often default to hourly rates. 
- One CDIP was for a go-to-market field, and it never got included in the template. Probably my bad. 
- These are cheap in the grand scheme of things, more MVP’s, and we could have funded way more of them.
- We over-documented this program.

--- 

### Taking over CDIPs

If a team comes in to use this program in a new setting, here are some recommendations: 
💰 a transparent structure for deciding on funding. Open the review to everyone (or record it and post to youtube at a very minimum), either on a public platform or on a public call. 
🗓 Set expectations for regular updates upon funding. 
📞 Remove the need for advisers. Anyone presenting a micro-grant to the DAO should just have an accountability buddy and regular updates. 
📚 Make sure the process, whatever form it changes to, is visually represented and has a single page.
👍 👎 Speed up the feedback and MVPs. 
👾 Rename them to mini-MIPS or project-to-hire (like a contract to hire but on a specific project with milestones as deliverables)
📣 Create a read-only chat channel or use one platform for updates and post updates same time every week.
👨‍🍳 Make sure there is a person who keeps documentation of different grants continuous in case contributors drop off or stop work due to other commitments. If a grant can be picked up by another team, then that would be awesome.

**Comment by patrick-j-govalpha** [comment]
Closing legacy issues
