### ISSUE TITLE
Portal Backlog

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#1245]
Just as an additional task so they don't get buried, there is a robust amount of user stories and features on the most recent roadmap. Here's a link [to the specific cell](https://docs.google.com/spreadsheets/d/1O9p9WRJMs0QWVmeVU08qgxqha3AdjplOYKF6kHrqtSw/edit#gid=602571222&range=B7).

**Comment by patrick-j-govalpha** [comment]
Closing legacy issues
