### ISSUE TITLE
404 on link from docs (Emergency Shutdown)

### ISSUE THREAD

**Issue by tgxn** [makerdao/community#1281]
**Describe the bug**

https://community-development.makerdao.com/en/faqs/emergency-shutdown/#when-should-emergency-shutdown-be-used

> Examples of attacks on the system include hacking or security breaches of the smart contracts, manipulation of the [Oracles](https://community-development.makerdao.com/en/learn/oracles/), and attacks on governance through ratified malicious proposals.

**To Reproduce**
click link in docs as linked above.
https://community-development.makerdao.com/en/faqs/emergency-shutdown/#when-should-emergency-shutdown-be-used
navigates to:
https://community-development.makerdao.com/en/learn/oracles/

**Expected behavior**
it to exist

**Comment by twblack88** [comment]
Thanks for sharing this @tgxn . These are legacy guides though, did this banner not display for you?

![Screen Shot 2021-04-19 at 11 36 08 AM](https://user-images.githubusercontent.com/8991325/115286012-6ff17100-a103-11eb-8e71-1acb1ff124ab.png)

**Comment by tgxn** [comment]
Hmm, I did not notice that banner! That explains it! Cheers!
