### ISSUE TITLE
Community Development Self Governance Workshop Archive

### ISSUE THREAD

**Issue by annaalexakr** [makerdao/community#1311]
## Motivation

- Enable MakerDAO’s growing community development group to use best practices in self-governance to make decisions and identify roles and responsibilities.
- Go through a transparent process to make a decision on compensation structure.
- Facilitate group learning and real-time practice on self-governance, in order to empower the group to do organizational work moving forward.

## Summary

Over the course of two months contributors in Community Development participated in workshops facilitated by Hadassah Damien with the help of Amy Jung and Anna Kryukova to learn tools and strategies to better self organize and govern as a community. 

We started by uncovering some of the driving reasons behind why our community members came together and continue to re-engage with Comm-Dev. Then we explored some of the principles that currently govern our community. We learned best practices and tools for self-organizing. And spend time outlining current roles and responsibilities for the projects and programs that make up Comm-Dev and what are the decisions and decision making power required at various stages in order to iterate fast while also working collaboratively.

## Role(s)

- Facilitator
- Comm-Dev Lead
- Co-lead / facilitator 

## Related Links

- [Workshop Timeline](https://app.mural.co/t/designfacilitation8369/m/rffm0088/1598963297774/d08d800ada27608bd2a5e3db8476295bd8413d5b)
- [Comm-Dev Decision Process](https://www.notion.so/annaalexa/Comm-Dev-Decision-Process-892348e134044108a218a351953a0d86)
- [Workshop Figma](https://www.figma.com/file/gtwFvMsxIozCym7bJ7Fym2/Comm-Dev--CD1.0?node-id=0%3A1)
    - Workshop 1: [Principles](https://www.figma.com/file/gtwFvMsxIozCym7bJ7Fym2/Comm-Dev--CD1.0?node-id=362%3A430)
    - Workshop 2: [Self-Org Practice](https://www.figma.com/file/gtwFvMsxIozCym7bJ7Fym2/Comm-Dev--CD1.0?node-id=510%3A2)
    - Workshop 3: [Roles and Responsibilities](https://www.figma.com/file/gtwFvMsxIozCym7bJ7Fym2/Comm-Dev--CD1.0?node-id=601%3A74), [Takeaways](https://www.notion.so/annaalexa/Comm-dev-Roles-d1fcd2fb720a40808e738def0c0abac8)

## Resources and Further Reading

- [A self-governance starter kit](https://medium.com/@ericmorrow/a-self-governance-starter-kit-ca77d4ba968b)
- [9 Decision Types You Should Know](https://medium.com/@alanna.irving/9-decision-types-you-should-know-3311f2621e04)
- [Design Facilitation: Preamble to the Design Thinking Facilitator's governance handbook](https://designfacilitation.gitbook.io/governance/)
- [Compensation in Self-Organizing Teams](https://www.notion.so/annaalexa/Comp-in-self-org-teams-633dea49af694655a60504d43dcce3b2)

## Lessons & Recommendations

- Working together on various exercises in Figma worked well and allowed all members to express ideas and converge on key themes. 
- As one outcome of this workshop series, Comm-Dev gained a [Proposal Framework](https://github.com/makerdao/community/issues/893) for significant and formal decisions. The team iterated and came up with a process by which any member in the community can put forth a proposal with a plan for execution, outline decisions that need to be made, the impacts of and outcomes of the proposal, and timeline for the community to add comments and vote. This process can be used to make decisions on program and project level as well as organizational structure. 
- Most workshops required a minimum of 90 minutes to allow enough time to participate in exercises, write individual answers, and share common themes.
-  Learning different frameworks and models for self-organization was useful to have an understanding of various tools available. But we found that committing to one framework and using it in over time is the best application of this workshop.
- Reach out to @annaalexak on Twitter or Maker Chat with any further questions.

**Comment by patrick-j-govalpha** [comment]
closing legacy issues
