### ISSUE TITLE
Governance Communications Social Media Distribution Archive

### ISSUE THREAD

**Issue by annaalexakr** [makerdao/community#1320]
#### Grow and Sustain Community Engagement

Governance communications produces a number of informational resources to keep stakeholders informed about Maker Governance. A social media strategy helps create a wider reach and engage with the larger community.

## Summary

In addition to posting Maker Relay and Snippets on the forum, the team syndicates information to Reddit, Twitter and cross posts in channels on Rocket Chat. 

## Role(s)

- Social media manager

## Suggestions and requirements

- Access to [@mkrgov](https://twitter.com/mkrgov) Twitter - ping @annaalexak for pw
- Posting in the morning EST proved to reach most amount of people.
- Tagging people and companies in threads to gain more exposure and engagement.
- Turning Maker Relay into a tweet thread with high level updates and reminders for calls going on that week creates added value and new format for the content. 

### Maker Relay Tweet Storm Example: 
    - 1/N Header + link to episode on the forum, one line overview of what's important this week
    - 2/N Executive (usually current week's or recap of last week's if appropriate), reminder of what time in governance cycle we are
    - 3/N Weekly polls - a summary of what is up for a vote or other important news related to weekly governance
    - 4/N - 5/N MIPS or Greenlight polls or both, depending on the week
    - 6/N Collateral Onboarding update - link to replay o last week or reminder of next week
    - 7/N -9/N Any news from community, upcoming events, hackathons, replays of interesting virtual events, help wanted, other news
    - 10/N Closing remarks with community call reminder which is that same day, ask for feedback etc

### Snippets Tweet Storm Example:
    - Intro, description what call this is from
    - Smart contracts domain team update
    - Oracle domain team update
    - Risk domain team update
    - Operational Support Community Development update
    - Collateral On-boarding update
    - MIPs update
    - Active discussion
    - Dai Peg

## Related Links

- Read more about [Maker Relay Distribution Guide](https://hackmd.io/Ks6X9k7PQ_ecDl6wga5FmQ)
- [Community Social media strategy](https://www.notion.so/annaalexa/Social-One-pager-4d9e84bc127546c5b8b805d70e0d8232)
- [MKRGOV Twitter strategy and analytics](https://www.notion.so/annaalexa/Maker-Gov-Current-Strategy-bd33c092796541ed9dea52c1576f2b12)
- [Tweet Thread Template](https://hackmd.io/H3rIjUH0RdyNCtNyz8VIcA)

**Comment by patrick-j-govalpha** [comment]
closing legacy issues
