### ISSUE TITLE
Create a "Contributor Quickstart Guide"

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#133]
The contributing section should improve contributor experience and onboarding. Guides should remove the barriers for community members to be part of the team, improve community resources, give and receive feedback, and grow the MakerDAO community.

[Working Doc](https://docs.google.com/document/d/1DvpA7EdhoK2a_bepfAzP3mAz_QsDvRKFBfI_qaHiGTQ/edit?usp=sharing)

[Project Planning Doc](https://hackmd.io/@rawhaus/rJX6JE3jH)

**Goals** 

- [ ] [Basic workflow guidelines](https://hackmd.io/@rawhaus/S1irbeGfL/edit) with approver process. 
- [x] Project Management Best Practices
- [x] High level list of tools we use (hackmd, Github that links to Tools Guide)
- [x] High level list of guides 
- [x] Templates & Project Frameworks
     - [x] [IA for landing pages](https://hackmd.io/vDXzQC6FQp6bc542_cK_0g)
     - [x] IA for Project Planning
- [ ]  Finding bounties to work on- link to bounties page

**Comment by Davidutro** [comment]
needs README.md

**Comment by Davidutro** [comment]
@aburban90 Can you write a Landing Page (README.md) for the Contributors section. 

Please use the same framework as these:
https://github.com/makerdao/community/blob/master/translations/README.md
https://github.com/makerdao/community/blob/master/meetups/README.md

**Comment by aburban90** [comment]
Started a Google doc for first draft.

https://docs.google.com/document/d/1VOesQzGjm1H4uO3_nWE9ZAMhPYr0hx0a87QrdTxr208/edit?usp=sharing

Feel free to comment

**Comment by aburban90** [comment]
@Davidutro Looking over your sample READMEs...

I wanted to follow the style but...

The first lines in both:

"Welcome to the MakerDAO Translations Initiative. A place where community members can help expand the reach of MakerDAO educational resources by translating them into various languages."

"Welcome to Do It Yourself Community Meetups. A place where you can find all the resources you need to host your very own meetup."

These are not separate sentences. Each second sentence is just a descriptive phrase. It describes the Initiative (etc), but it doesn't stand alone as a sentence.

**Comment by Davidutro** [comment]
@aburban90  I put up two PRs to fix that. Also fixed it in the drafts of pages that haven't been put up yet. Good catch.

**Comment by Davidutro** [comment]
Some relevant links: 

How to change your commit after a PR has been created
https://github.com/RichardLitt/knowledge/blob/master/github/amending-a-commit-guide.md

Also an example contributor guide to awesome-makerdao
https://github.com/apbendi/use-dai/blob/master/CONTRIBUTING.md

**Comment by Davidutro** [comment]
Created the HackMD for the landing page with my edits and additions

[Contributing Landing Page](https://hackmd.io/nImtCReuT-uDRiK-cD7Kcw)

**Comment by Davidutro** [comment]
We need pages that are basically"intro to using github" 
How do we want to include these in this section? 

I know there are many great resources that already exist, so I don't think its a good idea to create our own guide to github stuff from scratch. 

Is it possible to link a subnav item in the contributors section to someone elses .md file? or maybe it's a better idea to find a guide in a repo, fork it, and use it as our own?

**Comment by ghettodev** [comment]
I'm not sure we need separate pages. A doc that goes over some lifecycle examples: `idea -> forum -> issue -> hackmd -> chat -> PR -> Portal`, with some best practices that we like "Make sure the issue has a good description, link your PR to an existing issue, tell people in chat what you are doing and ask questions, etc" should be fine. 

We can link out to 'how to make and issue, PR, etc' in the body of the page.

**Comment by amy-jung** [comment]
Here's my draft of the workflow guide: https://hackmd.io/@rawhaus/SJb_IdNfB/edit

**Comment by amy-jung** [comment]
working through some higher level metrics on contributing. Early, early draft - should be worthwhile by next week: https://hackmd.io/w1-_i7fkRrq6E1KINPiFEQ

**Comment by amy-jung** [comment]
Working Doc: https://docs.google.com/document/d/1DvpA7EdhoK2a_bepfAzP3mAz_QsDvRKFBfI_qaHiGTQ/edit?usp=sharing

**Comment by amy-jung** [comment]
Draft 1 of the guide is up for review: https://docs.google.com/document/d/1DvpA7EdhoK2a_bepfAzP3mAz_QsDvRKFBfI_qaHiGTQ/edit?usp=sharing
