### ISSUE TITLE
Translations Archive

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#1346]
Hello! If you're new to our "Archive" section, here's an explainer:

While Community Development's programs supported by Maker Foundation comes to an end, the "Archives" issues provide insight to project/programs that the team had worked on. Perhaps you're interested in starting a project or program like this of your own, or perhaps you're just curious. Either way, our team members have collected documentation and relevant Github issues/threads for anyone to read about it.

---

## Motivation

MakerDAO was built to provide anyone, anywhere with a better, unbiased, transparent way to participate in the global financial system. As MakerDAO and Dai spread across the world, our focus was on creating universally accessible resources. Through the Translations Initiative, we were working to grant wider audience access to materials about MakerDAO in their native languages.

## Summary

We were hoping to expand the educational reach of existing resources and find and engage global contributors who are interested in learning more about Maker through writing and editing.

This is community led initiative had users translate MakerDAO resources to their native languages, via DAI bounties. Sections of existing documentation have been translated into Spanish, Korean, Polish, Japanese, Mandarin, Italian, and French. 

The most recent goals were summarized in this [Translations Planning Document](https://hackmd.io/@Davidutro/ByG7u2d9S). The desired goals were:

* **Long Term (Mission Orientated):** As MakerDAO and Dai spread across the world, our focus is on creating **universally accessible resources.** Through the Translations Initiative, we are working to grant wider audience access to materials about MakerDAO in their native languages.
* **Short Term (Action Orientated):** With inclusivity as a foundational part of our culture, our goal is to **translate our current resources impactfully.** 

    1. Figure out if the current process is working and how we can make it better
    2. Come up with measurements to define utility & ROI
    3. Develop the best community integrated strategy to choose next languages and resources to convert

**The Process**

Generally, the translations process could be broken into 3 parts: 
1. Procure & develop documentation to be translated
    - This [Github Project Board](https://github.com/makerdao/community/projects/4) to track translations doc statuses.
3. Cultivate the translators & editors for each language
    - Used a spreadsheet to keep track (private due to contributor contacts)
    - [Translator Guidelines (Requires Requesting Access)](https://docs.google.com/document/d/1SnqxnaVie3TSjHE16lN9HsFBv-fMDIN2lilFDAAlgxU/edit?ts=5dbb37d4#heading=h.1wf5zxdrn5h1)
    - [Editor Guidelines (Requires Requesting Access)](https://docs.google.com/document/d/1w03GeJrDKZh2kB6AK8WsEVfBdlLGHuX11Di4e1DiMiU/edit?ts=5dbb37c3#)
4. Review translations and include documentation in final Portal / educational platform

## Role(s)

We managed with just one community operator, but it requires a variety of contributors who speak various languages.

1. A Project Owner responsible for developing, executing, and optimizing the process for onboarding translators and translations process, communicating blockers and points for growth, and defining strategy. 
2. A person working on the developing and/or sourcing the documentation to be translated. This person could be the same as the person above.
3. Writers to contribute various languages
4. Editors to review the content in various languages.

## Related Links

Where we last left off: The Comm-Dev team was looking to launch a larger pilot of the translations program, which halted as we rewrote our documentation site and looked for a strategic owner. 

- [Translations Initiative (Requires Requesting Access)](https://docs.google.com/document/d/14oygO0LN96T1-M7ucOqSDH2xPsoYZ9DsY-xrAiH7spg/edit?ts=5dbb37a7)
- [Github Epic outlining to-dos](https://github.com/makerdao/community/issues/341)
    - [Gather Data & Requirements](https://github.com/makerdao/community/issues/347)
    - [Figure out if the current process is working and how we can make it better.](https://github.com/makerdao/community/issues/350)
    - [Establish a public MCD-centric inventory list for resources available for translation by special request.](https://github.com/makerdao/community/issues/348)
    - [Develop best community-integrated strategy to choose the next translated content](https://github.com/makerdao/community/issues/349)
- [Ideas on how someone could Request Content Translation](https://hackmd.io/IKQG20bURKasy5RuFj-wuQ?view)

## Lessons & Recommendations

One of the challenges we had initiating this program was being able to measure ROI and what it meant for this project to be successful.
- Being able to easily see the metrics
- Measuring outcomes more clearly
- Better quality translations
- Reducing onboarding friction
- Measure utility of the docs created

We were also working on redesigning our Portal (documentation site), therefore content was constantly changing.

A key decision of this program was to do human translations. While these were costly, we had two reasons: 1) DeFi content is very specific and uses language that requires understanding the content 2) We wanted to engage contributors through learning. There were parts of the process that could have been more automated while retaining human interaction, such as having initial translations done by automated systems and having contributors mostly focus on reviewing.

If there isn't a desire to launch an entire initiative, smaller grants are a good way to fill this need.

Most details are outlined in this document, but if there are further questions, you can reach out to Amy (@itsamyjung on Twitter).

**Comment by patrick-j-govalpha** [comment]
Closing legacy issues
