### ISSUE TITLE
Hackathon Archive Template

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#1347]
Hello! If you're new to our "Archive" section, here's an explainer: 

While Community Development's programs supported by Maker Foundation comes to an end, the "Archives" issues provide insight to project/programs that the team had worked on. Perhaps you're interested in starting a project or program like this of your own, or perhaps you're just simply curious. Either way, our team members have collected documentation and relevant Github issues/threads for anyone to read about it.

-----

## Motivation

Hackathons represent a significant source of potential developer talent; the intention was to foster long-term relationships with MakerDAO and give winners a clear path to continue building for the MakerDAO ecosystem. Additionally, hackathons encourage diverse groups to hack on prototypes for new products and services. 

## Summary

We needed 2 weeks notice on event themes and total prize amounts to generate and write bounty ideas, collect speakers/mentors/reviewers, invoice and escrow funds on time. Comm-Dev worked closely with MarComms / Events Lead to ensure a smooth process. 

- This page on the Community Development Portal [outlines the process for organizers to request funding](https://community-development.makerdao.com/en/funding/hackathon-funding) from the Maker Foundation for their hackathon.
- This page on Community Development Portal serves as a [resource for hackers](https://community-development.makerdao.com/en/contribute/hackathons) who are interested in building on top of Maker.
- This page on Github gives a few examples of [past bounties](https://github.com/makerdao/community/issues?q=label%3Ahackathons+label%3Abounty+is%3Aclosed+).
- Docs.makerdao.com provides technical resources, as well as [#dev channel](https://chat.makerdao.com/channel/dev) on the Maker Rocketchat.
- Where we left off: [Potential Improvements to our Hackathon Process](https://github.com/makerdao/community/issues/124)

## Role(s)

Sponsoring or running hackathon can be a lot of work and require a lot of operators. Due to all the activities going on, hackathons can get fairly hectic. 

1. At minimum, one person would be leading, representing the organization's operations, coordinating hackers and working with organizers to get sponsorship materials.
2. He/She/They would be responsible for scoping and writing the bounty, posting them to bounty platforms, promoting through channels and sharing with relevant audiences. This person may work with someone in Marketing to increase visibility to bounties.
3. Depending on the challenge, a minimum of one reviewer (3 is recommended) who is also apt at reviewing code. 
4. A Mentor or Integration expert who is usually requested by hackathon organizers for providing technical support to hackers. This person should be very knowledgable in technical details of the Protocol.

## Related Links

- [Older Github Issues with past bounties](https://github.com/makerdao/community/issues?q=label%3Ahackathons+is%3Aclosed)

## Lessons & Recommendations

Hackathons are a great way for organizations to get developers to build on a protocol. However, given Maker is one of the well known projects, and developers take time onboard and built solutions for Maker, we didn't find that to be serving our needs. One thing we considered was running our own Maker specific hackathon.

Ultimately we didn't find utility in engaging in both virtual and in person hackathons due to the costs and operational overhead not offsetting the ROI.

One of the biggest challenges of running a hackathon is understanding the ROI you want and building the channel for it. If the hacker doesn't have a clear funnel for engaging deeper with your community after the hackathon (ie. receiving funding to continue building their idea, getting hired onto an organization's team), the high operational efforts are wasted on a one-time engagement.

1. Coming up with hackathon bounties can be difficult. You want to create something wide enough to have many submissions, but also narrow enough that it may be useful for your project. It is good to set one or more specific tracks and always keep one open-bounty track, where it's a "build anything using the protocol". Also consider engaging with your existing community to come up with a running list of challenges.
2. Setting bounty sizes are tricky. If you have one grand prize, many may not be encouraged by the opportunity size. If you have few lesser amount prizes, you may have lower quality submissions. In some cases, you may have no submissions worthy of a winner, but you still need to choose and pay out winners.
3. It's always great to showcase projects who built on your project. We considered [developing a "Transparency Dashboard"](https://github.com/makerdao/community/issues/200) that showed past hackathon winners/projects.

If there are further questions, you can reach out to Amy (@itsamyjung on Twitter).

**Comment by patrick-j-govalpha** [comment]
Closing legacy issues
