### ISSUE TITLE
# Community Development Onboarding Archive

### ISSUE THREAD

**Issue by annaalexakr** [makerdao/community#1359]
# Community Onboarding Archive

[//]: <> (Try to be concise, under 500 words. More information does not equal good information. If someone wanted to bootstrap their own version, what could they take away from this?)

## Motivation

The initial motivation for onboarding was to improve the contributor experience within the MakerDAO community. Since Comm-Dev is make up of contributors participating in the wider DAO the aim was to give them access to mentorship, include them in community activities, and help them map their skills and interests to existing or new opportunities.

Onboarding is one of the most crucial parts of running any community and in Community Development we identified that there are two sides to onboarding someone into a community, the technical side and the cultural side. Technical can involve learning about the Protocol, the tools we use, processes, and workflows. While the cultural side involves keeping the social protocol and aligning with values of Community Development and community at large. 

## Summary

As part of crafting this process, we asked our community the question, "if we had a formal onboarding program what would you, the contributor, want it to look like?" This lead to a series of questionnairs that we gave our contributors to tease out the specific needs of this program. 

[Questionnaire](https://hackmd.io/D9Yq5L-nSmWnv1kSFAD4CA)

## Role(s)

- **Peer mentor**: a seasoned contributor who is closely familiar with both the technical tools we use but also with the culture and social protocol of Comm-Dev. This person would help a new contributor become familiar with the mandate of Community Development and ways to get involved. 
- **Project Lead**: someone who can help a new contributor evaluate their skills and interests and how it maps to existing projects or how to navigate the process of proposing work of their own. Familiar with our process and can be the point person for a specific project as well help navigate proposing new work. 
- **Onboarding Program Lead**: a person responsible for owning and developing Onboarding as a program. This person would be responsible for conducting necessary research in the community for what works and what doesn't, maintaining documentation, providing guidance and support to peer mentors and leads so that they can help scale the health and growth of the community through a positive onboarding culture.

## Related Links

Com-Dev team worked on creating the contributing section of Comm-Dev portal to improve contributor experience and onboarding. We created guides to remove the barriers for community members to be part of the team, improve community resources, give and receive feedback, and grow the MakerDAO community.

- [Contributing Section V2 Epic](https://github.com/makerdao/community/issues/503)
- [MakerDAO documentation Framework](https://github.com/makerdao/community/issues/134)
- [Contributing Section - Earn as a Contributor](https://github.com/makerdao/community/issues/506)
- [Contributing Section - Visual Style Guide](https://github.com/makerdao/community/issues/509)
- [Contributing Section - Contributing Section](https://github.com/makerdao/community/issues/507)
- [Contributing Section - Contributor Onboarding Guide](https://github.com/makerdao/community/issues/505)

# Links and Resources 

- [Onboarding program questions](https://hackmd.io/D9Yq5L-nSmWnv1kSFAD4CA)
- [documentation](https://github.com/makerdao/community/issues/134)
- [onbaording guides from portal](https://community-development.makerdao.com/en/resources/onboarding)
- [Goals and Objectives for Comm Dev](https://www.figma.com/file/EimiCAvBZiT6bAgHVF20Vk/Comm-Dev-CAMP-SPACE-2020?node-id=351%3A36)
- [Culture Questionnaire Responses](https://docs.google.com/spreadsheets/d/1-biKTcwLzRaFHaPM7fWrQdwtv3iY3-MJZj_TwR-RJsw/edit#gid=2001245556)
- [Soft Skills](https://docs.google.com/spreadsheets/d/1HH6XPFHjx8SMerF-knMtppQlNtWwNX7gtgVxhJ-S41g/edit#gid=1064289387)
- [Process responses](https://docs.google.com/spreadsheets/d/1dBZoq3YjKqTanO_fI0Vh3Ft_upcL0PvWcUIv-ixyEYY/edit#gid=786976232)
- [All responses](https://docs.google.com/spreadsheets/d/1usnA5P4JyWq4QeqAZVlFcTgFiFHYNduqJH4lq4cpJ2Q/edit#gid=1028389829)

**Comment by patrick-j-govalpha** [comment]
closing legacy issues
