### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by hscha** [makerdao/community#1369]
https://community-development.makerdao.com/en/collateral-and-risk/dai-credit-system
https://community-development.makerdao.com/en/collateral-and-risk/types-of-risk
https://community-development.makerdao.com/en/collateral-and-risk/risk-teams

these urls show 404 error

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Geoge1** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14164218/

**Comment by patrick-j-govalpha** [comment]
URLs no longer supported - closing issue
