### ISSUE TITLE
Transparency Dashboard V1

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#137]
[Project Planning doc](https://hackmd.io/rGoz8zqESkqKrsuydlweZA)

The first launch will include the minimum for transparency rollup:
- number of countries in participation
- social media shares
- stats from events. 

Needs to be consistent for each Major Section.

**Comment by Davidutro** [comment]
Thoughts on the information that would be nice to have in each section's transparency dashboard

**Meetups**
- Countries
- # of attendees
- # of meetups
- # of Dai granted

**Translations**
- # of languages
- # of contributors (editors+translators)
- # of translated documents
- # of Dai granted to contributors

**Hackathons**
- # of hackathons we've participated in total
- # of hackathon participants who've become grantees
- # of Dai prizes we've sponsored
- # of countries total

**Contributors**
- Total # of unique contributors to all initiatives minus the grants program
- # of Dai granted to contributors

**Comment by as-dr** [comment]
It’s done. Last thing we need is the updated JSON.

**Comment by amy-jung** [comment]
@Davidutro will send the updated JSON to @as-dr

**Comment by as-dr** [comment]
Update: I'm going to update the country numbers with region numbers instead. This saves time (since we don't have each grantee country recorded) and doubles as an act of security/privacy by limiting geographic information on grantee locations.

**Comment by amy-jung** [comment]
@asterix will finish up by next week 
@david.u needs to send current JSON file to @rich.brown 
we'll consider redacting info /stealth mode for grantees who want to stay anonymous

**Comment by amy-jung** [comment]
@as-dr : updates?

**Comment by as-dr** [comment]
@amy-jung Sorry I only mentioned this in the comm-dev channel: the site is complete and ready to go. Next step is to get confirmation that all grantees consent to having their information publicly available on the site. Think this might be a job for @Davidutro

**Comment by ghettodev** [comment]
I've updated the json, it should be complete now. A notice has gone into the incubate channel to get feedback from grantees. Depending on the level of response I might send an email as well. I'll update the ticket when we are ready to go live.

**Comment by amy-jung** [comment]
Currently says "since February 2018" will that update as well?

**Comment by amy-jung** [comment]
@ghettodev pinging Dev Ops to be pushed live

**Comment by amy-jung** [comment]
Live! https://grants.makerdao.com/

Need to work on a marketing "launch" plan
