### ISSUE TITLE
Website Broken Links - 404

### ISSUE THREAD

**Issue by uncliggett** [makerdao/community#1379]
**Describe the bug**
There are broken links on this page. 
https://community-development.makerdao.com/en/learn/collateral-and-risk

**To Reproduce**

Visit these URLS:

https://community-development.makerdao.com/en/collateral-and-risk/dai-credit-system
https://community-development.makerdao.com/en/collateral-and-risk/types-of-risk
https://community-development.makerdao.com/en/collateral-and-risk/risk-teams

**Expected behavior**

I expected to see the information for that page, not a 404 error. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Firefox
 - Version 89.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by patrick-j-govalpha** [comment]
closing legacy issues - these docs are no longer supported
