### ISSUE TITLE
Broken link 2021 Sept

### ISSUE THREAD

**Issue by Yeetcaps** [makerdao/community#1558]
**Broken link**
To a nonexistent page

https://makerdao.world/en/contribute/

**To Reproduce**
1. Go to https://ethereum.org/en/stablecoins/#earn

2. Scroll down to ‘ How to get stablecoins'
3. Scroll down to ‘Earn’
3.  Click ‘More’
4. Scroll down and click on ‘MakerDao Community’

**Expected behavior**
To reach either a contribute page, community page, or be redirected somewhere to MakerDao site without error

**Smartphone **
 - iPhone XR
 - OS: iOS15.1
 - Browser [safari]

![C908BD6E-7EEE-4C2E-8AEC-BAE214E11961](https://user-images.githubusercontent.com/77501011/140629698-2713ae75-de86-41ff-b7c8-1cb3ef918ea5.png)
![CDA69EDA-3751-4DCA-9403-289C6DA88EB0](https://user-images.githubusercontent.com/77501011/140629700-488ebe85-087c-44db-b3c4-9a75c0a6d155.png)
![A6C87083-6AC4-41D3-91FD-A42E6AAD6093](https://user-images.githubusercontent.com/77501011/140629701-f2904038-0f09-4efc-9a46-9ec0f817917c.png)
![42ACA973-04CF-45C8-A110-B2E05EF556D8](https://user-images.githubusercontent.com/77501011/140629702-003da023-1993-4443-8fd9-d41734e5f708.png)
![6DBA7B4B-9399-41F1-82D7-C67C61B967A2](https://user-images.githubusercontent.com/77501011/140629703-930297d4-ee22-442c-9f90-14fabc86e243.png)

**Comment by patrick-j-govalpha** [comment]
Closing legacy issues - makerdao.world is no longer supported
