### ISSUE TITLE
Translation Transparency Dashboard

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#157]
Once the main transparency project page is done for the grants program, lets re-engineer for translations as well.

**Comment by amy-jung** [comment]
Starting to capture this with @reuptaken :

Must-have

* Total number of languages (+ map?)
* Total number of translators/editors
* Total number of documents translated
* Total number of bounties paid

Optional

* Countries from which translators/editors are from (as map?)

**Comment by amy-jung** [comment]
"Apply section"

Link to our [Community Portal Quickstart](https://community-development.makerdao.com/translations/translators-quick-start-guide)

Add https://airtable.com/shr415iT3e8S8nuzS as Call To Action

**Comment by Davidutro** [comment]
not happening
