### ISSUE TITLE
Why is stability fee in my CDP set to 7.5%?

### ISSUE THREAD

**Issue by bitkominer** [makerdao/community#16]
Hi guys, I was surprised seeing the stability fee of my CDP changed into 7.5%. It was 1.5% when I initiated my CDP, then after a week it's changed into 3.5%, and now 7.5%.

Is this normal guys? I thought the fee is 2.5%. Would it keep increasing? What should I do?

![image](https://user-images.githubusercontent.com/21021582/55287920-ff6f3e80-53d9-11e9-97fc-085c4f5e4926.png)

**Comment by ricburton** [comment]
You should follow the MakerDAO governance process on twitter.com/makerdao

You should sign up for our app, Balance.io, which will notify you of stability fee changes in the future.

Richard

**Comment by bitkominer** [comment]
OK, noted. Thanks!

**Comment by ghettodev** [comment]
Hi @bitkominer, 

You can find a wealth of information about the Stability Fee and the communities reasoning behind the changes in our subreddits:

- https://www.reddit.com/r/mkrgov/
- https://www.reddit.com/r/MakerDAO/

and in our chat if you would like to discuss them in realtime: 

https://chat.makerdao.com/home
