### ISSUE TITLE
#909

### ISSUE THREAD

**Issue by Solefuamz** [makerdao/community#1722]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Solefuamz** [comment]
It says that it thinks something is broken on your side

**Comment by Solefuamz** [comment]
It's says error 404

**Comment by Solefuamz** [comment]
'....'

**Comment by Geoge1** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14164218/
