### ISSUE TITLE
'Types of Risk' bug: https://makerdao.world/en/collateral-and-risk/types-of-risk

### ISSUE THREAD

**Issue by igorcisa** [makerdao/community#1766]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Geoge1** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14164218/

**Comment by patrick-j-govalpha** [comment]
Closing legacy issues makerdao.world is no longer a supported site
