### ISSUE TITLE
Wrong linking on Collateral And Risks docs page

### ISSUE THREAD

**Issue by verkhohliad** [makerdao/community#1773]
**Describe the bug**
Wrong link to "Type of Risk" page.

**To Reproduce**
1. Go to 'https://makerdao.world/en/learn/collateral-and-risk'
2. At the bottom of the page click on the link "Types of Risk" or "Risk teams"

**Actual behavior**
404 page open
(wrong links - https://makerdao.world/en/collateral-and-risk/types-of-risk; https://makerdao.world/en/collateral-and-risk/risk-teams - missed /learn)

**Expected behavior**
https://makerdao.world/en/learn/collateral-and-risk/risk-teams
or 
https://makerdao.world/en/learn/collateral-and-risk/types-of-risk
should be opened

**Comment by Geoge1** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14164218/

**Comment by patrick-j-govalpha** [comment]
makerdao.world is no longer supported - closing issue
