### ISSUE TITLE
community-development.makerdao.com and makerdao.world redirect broken

### ISSUE THREAD

**Issue by Toliak** [makerdao/community#2077]
**Describe the bug**
The https://community-development.makerdao.com/ and https://makerdao.world/ redirects to https://makerdao.com/

**To Reproduce**
1. Go to the website, https://makerdao.com/
2. Click on `Learn -> FAQs`
3. Scroll down to `FAQs` section and click any item (e.g. `Liguidation`)
4. See the redirect to the website main page

**Expected behavior**
I expected opened https://community-development.makerdao.com/en/faqs/liquidation page with the documentation

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Browser Chrome 
 - Version 108.0.5359.125 (Official Build) (64-bit)

**Comment by patrick-j-govalpha** [comment]
These sites are no longer supported. Growth team are reworking makerdao.com and broken legacy links should be removed at that stage
