### ISSUE TITLE
Clean up and edit style-guide.md

### ISSUE THREAD

**Issue by aburban90** [makerdao/community#211]
@ghettodev 

See the Hackmd link:
https://hackmd.io/ren8L9McTLaTpsw6p3X2aQ

I changed some word choice, grammar, and added several points for consistency throughout.
Thoughts?

**Comment by aburban90** [comment]
## Links

- Use descriptive hyperlinks.
  - **No:** Learn more [here](link).
  - **Yes:** Learn more at [awesome-makerdao](link).

Ideas for links?

**Comment by aburban90** [comment]
What is right?

MakerDAOs
or
MakerDAO's

**Comment by aburban90** [comment]
Updated grammatical links to point to wikipedia pages. I don't love the way wikipedia writes up stuff... gets messy, but fair point that it'll be there to stay

**Comment by Davidutro** [comment]
> What is right?
> 
> MakerDAOs
> or
> MakerDAO's

MakerDao's is correct

**Comment by ghettodev** [comment]
I've changed the title back to Style Guide. It's not completely accurate but it is the norm for these kinds of things. Anything not directly related to style, grammar, and syntax can be moved to other documents as they are created. 

I think it's ready for a PR.
