### ISSUE TITLE
Portal: Increase the Visibility

### ISSUE THREAD

**Issue by ghettodev** [makerdao/community#216]
Now that it's 80% done, lets get the word out:

- everywhere we interact with the community we need to add links to the forum, portal and github
- come up with plan to remind people in chats/etc the portal is a resource that should be used
- need more ideas about how to raise awareness...
- update the meetups grants framework to include requirements that people talk about the commdev project, portal, resources.
_added this point to the DIY Meetups Epic #242, also see #346 for more ideas on this point - David_ 

Let's start brainstorming here about ways to raise visibility.  @Davidutro @amy-jung

**Comment by amy-jung** [comment]
We'll need to decide on updating and adding the portal to the Community section on makerdao.com

**Comment by Davidutro** [comment]
@ghettodev can you glance over the portal in its current state and decide if it's ready to go on Makerdao.com? 

If it's more or less ready, it should definitely be listed in that dropdown 👇 

![image](https://user-images.githubusercontent.com/40721951/70275525-4d63ef80-177c-11ea-8233-e6e27ca8551d.png)

**Comment by amy-jung** [comment]
@TomDeMichele can we construct this in a way with action items?

**Comment by TomDeMichele** [comment]
I can come up with a marketing/seo blueprint aimed at increasing visibility of items that will generally apply to any project, portal, resource, etc that needs visibility.  Current notes on it are here https://docs.google.com/document/d/1GKZ6xOMkb8LZ3j2OuEIYodrgpQhErTi2nle0pfxoQUc/edit?usp=sharing.

**Comment by Davidutro** [comment]
Added @TomDeMichele and @goldfarbas as assignees since they are spearheading the decentralized comms and marketing working groups.

There is a [marketing plan for the portal.](https://docs.google.com/document/d/1M2b0Vxu_UFHSrKgRjvsSOTFjDh35_6wav6IyVLxRC9Y/edit#heading=h.wdof6stnnjd) | #720 

Actually I will close this issue in favor of the above issue 720
