### ISSUE TITLE
Create The Maker Foundation / DAO major section

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#223]
- **Status:** Considered for post-launch
- **Issues:**
- **Type:** Educational
- **Who:** Rich
- **Approver:**
  - [ ] Rich
  - [ ] David
  - [ ] PM
- **What:**
  - Anything to do with transparency
  - Business units
    - Principles
    - Mandates
- Pages:
   - [ ][Landing Page]()
      - [ ][?]()
      - [ ][?]()
      - [ ][Links to MakerDAO FAQ in the FAQ Section]()

**Comment by amy-jung** [comment]
Went into FAQs, doesn't need its own section
