### ISSUE TITLE
Add Question to Contributor FAQ once process doc is done

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#227]
> How can I submit a contribution to GitHub?

TODO: Add this once the process doc is finished. 

Status: I think someone needs to own this. If it's me, then I can work on this after the new year.
The answer to this question can get into both Git and local repo usage, as well as just GitHub interface usage for newer, less technical, contributors. 

Docs:

- [Current Contributor FAQ](https://github.com/makerdao/community/blob/master/contributing/faq.md)
- [Working doc](https://hackmd.io/qBruCs2YTUuke7Je_Spdgw?both)

**Comment by aburban90** [comment]
@Davidutro where's the link to... anything?

**Comment by aburban90** [comment]
Nvm, got it

**Comment by aburban90** [comment]
@Davidutro  @ghettodev 
https://hackmd.io/qBruCs2YTUuke7Je_Spdgw?both

Proofread the FAQ, ran it thru Grammarly. Changed phrasing and word choice. Added a relative link to the contributing section**. (Please make sure I set the right link!)** 
Removed first and second-person voice where I could (we, us, you, etc).

Go over my edits, let me know what you think.

**Comment by Davidutro** [comment]
@aburban90 This is just a subtask/issue of this larger one
https://github.com/makerdao/community/issues/158

You can see it here:
![image](https://user-images.githubusercontent.com/40721951/61747112-2e376900-ad6b-11e9-85a8-495993c4fdd1.png)

**Comment by Davidutro** [comment]
I updated the working doc to be the same as the current public version of the contributor section FAQ

Anyone can jump in and do work on this issue here:
https://hackmd.io/qBruCs2YTUuke7Je_Spdgw?both

**Comment by Davidutro** [comment]
@amy-jung Can you change the assignees

I don't think this falls under me anymore :)

**Comment by amy-jung** [comment]
Submited as part of #159
