### ISSUE TITLE
Create Onboarding Voters Guide

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#238]
This page is currently missing from the Governance section and is an important resource for community members who want to start voting. 

Doesn't have to be complex or crazy since this process may change in the mid-term(6mo-2yr) future.

### Thought exercise

What would a Voter Onboarding Guide look like?
What questions are we trying to answer?
1. How does voting work, basically? 
Explanation of Governance Polls vs Executive Votes.
2. How do I vote? (assuming you own MKR)
2. How do I vote from a cold storage wallet without needing to reconnect it every time there is a vote?
3. What do I vote on?
types of governance polls
types of executive votes
4. What do I do after I vote? 

### Other Considerations
Prioritize: 
**confidence building & information accessibility**
In producing this guide we want to give new users value. The best value I can think of when introducing people to voting is getting them to understand that votes are a signal and that no matter the size of your MKR holdings your vote matters. 

### Links

[Hackmd final draft](https://hackmd.io/faFjG3XsSsyI13q-UbsZkg)
[Draft Gdoc](https://docs.google.com/document/d/1vQ9rVQLpPStGhEubgWLaOK7xAxBHmEPRCLB1eW7D0Z8/edit)
[Onboarding Section Project notes](https://hackmd.io/PgIr2M8_RkiEuBxLXcVRrw)

**Comment by Davidutro** [comment]
Unsure if this would live int he Governance Section or the Onboarding Section, or both. Linking the Onboarding Section Epic here: #240

**Comment by ebpwt02** [comment]
I'll take a stab at this over the next couple of days

**Comment by ebpwt02** [comment]
Just going to do SCD since that's all I know

**Comment by aburban90** [comment]
Started a Gdoc
https://docs.google.com/document/d/1bq4Wk6c3yDvS_CwjrpOcp7AyVgRGw4-dl__2ClDKOpg/edit#

**Comment by aburban90** [comment]
Where is latest gdoc for this?

**Comment by aburban90** [comment]
Is this it?

https://docs.google.com/document/d/1vQ9rVQLpPStGhEubgWLaOK7xAxBHmEPRCLB1eW7D0Z8/edit

**Comment by Davidutro** [comment]
@ghettodev 

Please review the Voter Onboarding Guide

[Working Doc is found here](https://github.com/makerdao/community/issues/238#issuecomment-528133310)

**Comment by ghettodev** [comment]
Doc reviewed. Changes needed.

**Comment by Davidutro** [comment]
Rich did a run-through a few of days ago, I ran through the suggestions today.

**Comment by Davidutro** [comment]
Need to convert the current doc to markdown today and send it to Rich.

Need notes on how to handle the screenshots without imgur, using github as our repo for the assets themselves.

**Comment by Davidutro** [comment]
I moved the "Are Voters with Small MKR Holdings Influential?" question and text to a scrap bin. I can recover it if necessary. It now lives in the Governance FAQ draft google doc, in the scraps section below the document itself.

**Comment by aburban90** [comment]
Notes/Comments:

1. "Linked Wallet Voting Contract" or "linked wallet Voting Contract"
Both are used, which is right?

2. Links to AMD should be re-checked once AMD Revamp is done.

**Comment by aburban90** [comment]
3. Do we _really_ need "Accounts" drop-down menu to link to Governance Portal?

**Comment by aburban90** [comment]
4. Did "The Voting Process" not transfer? Could swear there was more stuff...

**Comment by Davidutro** [comment]
This was actually completed and launched.

https://community-development.makerdao.com/onboarding/voter-onboarding

Closing the issue, I think the guide was moved in some form to the redesigned comdev portal.
