### ISSUE TITLE
Maker Community Styleguide

### ISSUE THREAD

**Issue by as-dr** [makerdao/community#244]
Placeholder for the style guide.

To do:

1. List out styles, organized by type (typography, type scale, colors, etc.)
2. Provide usage examples where appropriate (when different headings are used, or colors, etc.)
3. Determine where this style guide will live (as a MD document inside of a Maker owned repo - which one?)
4. Publish a v0.1

**Comment by amy-jung** [comment]
https://hackmd.io/KfJZKuElQwqp9t97sw68NQ?both

**Comment by ghettodev** [comment]
Looks great. I've posted it to the portal: https://community-development.makerdao.com/contributing/visual-style-guide
