### ISSUE TITLE
Create Landing Page for Onboarding Section

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#248]
The Onboarding Section is an "educational" section rather than an "initiative" section. It needs a landing page. Before creating this landing page, I need to consult @as-dr on how best we could do the Landing page IA for these, like we did for the initiative section.  

Links
- Draft [Landing Page for Onboarding section HackMD](https://hackmd.io/10VopNNWR-CS8vMqlTKELw?edit)
- [Initiative Section IA](https://hackmd.io/z7TQipyARi2rWU3jxZxRHg?edit)
- Educational Section IA (don't know if all sections will follow the same. Will need to see other educational sections get developed first.)

**Comment by as-dr** [comment]
Let's discuss in chat.

**Comment by Davidutro** [comment]
Ok well the landing page is done. It's short, sweet, and straight to the point. 

It mirrors the Initiative Section Landing Pages IA to a certain extent. I remover the "Project description" header & text

**Comment by amy-jung** [comment]
@Davidutro - can we close the issue?

**Comment by Davidutro** [comment]
@amy-jung Yes

Though, Rich does need to review. This can happen later once we have the rest of the section ready to go.

**Comment by Davidutro** [comment]
outdated
