### ISSUE TITLE
Create Onboarding Vault Users Guide

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#252]
This page is currently missing from the Onboarding section and is an important resource for newer users who want to use Vaults responsibly.

It doesn't have to be complex or crazy since this process may become a little more complex in the mid-term(6mo-2yr).

### Thought exercise

What would a Vault User Guide look like?
What questions are we trying to answer?
How do we categorize these questions (101, 201, 301 level guides)
1. How do I use a Vault? (assuming one has an ETH address already, with some acceptable collateral)
How do I open a Vault?
How do I add collateral to a Vault?
How do I borrow from a Vault?
How do I repay a Vault?
How do I close a Vault?
How do I transfer a Vault?
2. What are the best practices for using a Vault?
What are my risks?
How do I manage these risks?
3. What is the purpose of using a Vault?

### Other Considerations

I feel like many of the questions we are trying to answer above are thoroughly covered in the Vault FAQ. However, an onboarding guide should incorporate all this information differently. Using images, screenshots, links to outside resources, etc. is heavily encouraged. Readers will read, but some learners are visual as well. - David

In producing this guide we want to give new users value. The best value for Vault users is probably helping them understand the risk management necessary, the tools available to them for dealing with their CDPs. 
Includes:
* Tax guidance (I wish)
* Tools for seamlessly leveraging, unwinding, or selling their Vaults. 
* Tools for tracking their Vaults
* Troubleshooting guide? 
* Vault calculators

Should reflect MCD Vaults and Oasis.app/borrow

### Links:
[Working Doc](https://docs.google.com/document/d/14MUqQiveDkbA-PHnfwftDoR27RmZQqTK_npUSpdU_Pk/edit#)

**Comment by aburban90** [comment]
Started a gdoc:
https://docs.google.com/document/d/1bq4Wk6c3yDvS_CwjrpOcp7AyVgRGw4-dl__2ClDKOpg/edit#

**Comment by Davidutro** [comment]
@ghettodev Ready for review

[Working Doc](https://docs.google.com/document/d/14MUqQiveDkbA-PHnfwftDoR27RmZQqTK_npUSpdU_Pk/edit#)

**Comment by Davidutro** [comment]
CDP Onboarding Guide is ready. Though we are waiting for Oasis Borrow to come out when MCD launches, since it may change the screenshots and process of the cdp portal.

**Comment by aburban90** [comment]
Vaults: User Onboarding Guide
 Vaults User Onboarding Guide

**Comment by Davidutro** [comment]
@aburban90 
When you can, please redo the document to include screenshots for oasis borrow instead of the old SCD CDP portal.

Also send me a gdrive folder with the screenshots so I can move it from gdocs into a .md file and have the screenshots stored locally.

**Comment by aburban90** [comment]
Updated Working Doc: https://docs.google.com/document/d/14MUqQiveDkbA-PHnfwftDoR27RmZQqTK_npUSpdU_Pk/edit#

IMAGE FILES: https://drive.google.com/open?id=1UZZMz3SuMCvgPfWliwfIFfvsymh15sPe

**Comment by aburban90** [comment]
Wanted to come on here and try out those new "ready for review V0.1" stuff... but maybe too soon.

Anyway, ready for another person

**Comment by aburban90** [comment]
Figma Assets Provided by Hazel
https://drive.google.com/drive/folders/1uNAOUlj1qz66vqr8_yl_OC6GpSCgHNxS

**Comment by Davidutro** [comment]
Additional section for V2:

# Vault Risk Mitigation Tools and Services

**Comment by Davidutro** [comment]
outdated. This has been moved into the new comdev portal.
