### ISSUE TITLE
Create Onboarding Dai Users Guide

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#253]
This page is currently missing from the Onboarding section and is an important resource for newer users who want to know how to hold and use Dai.

It doesn't have to be complex or crazy since this may change rapidly to have more use cases and better wallets. 

### Thought exercise

What would a Dai Users Guide look like?
What questions are we trying to answer?
How do we categorize these questions (101, 201 level guides)
1. Where to acquire Dai? 
2. Where to hold Dai?
3. What can you do with Dai? How does one use Dai?
4. How do you turn Dai back into fiat?
5. How do I use Dai from mobile-only? (what is the wallet we will use for this guide?)
6. How do I manage a wallet from my computer? (PC or Mac)
7. How do I send or receive Dai? (Dependant on the wallet, but the general principle should be universal maybe?)
8. How do I recover lost Dai?

### Other Considerations

In producing this guide we want to give new users value. The best value I can think of when introducing people to Dai is the ability to lend it for yield. To send it between friends casually. To use with apps like PoolTogether. To use with games (though not many currently exist that seamlessly interact with Dai). 

The easiest actions with Dai currently are to save them and to use them transactionally between friends who also use Dai.

Do we need to give a brief overview of wallet security and personal wallet management generally? 
Probably, it's useful to new crypto users. Wallet security is huge since there's no centrally controlled recourse for lost passwords and hacked accounts.

## Resources

- Working Doc: [Dai User Onboarding](https://docs.google.com/document/d/13SZ4EW_5R0P56vGmV3TxohQgbaE7GeVNm0Uc1hoTu2g/edit#heading=h.t16kx7yasc5d)
- [Planning Doc defining the scope](https://hackmd.io/V4tZMYoUTvuTLEkJOKMKHA)
- [Chaz's Guide we can pull copy from](https://defipulse.com/blog/zero-to-defi-cdai/)

**Comment by Davidutro** [comment]
Currently searching for someone who is willing to tackle this. Looking outside our current community to see if we can attract some new people interested in doing this kind of stuff.

**Comment by scott-l-e-w-i-s** [comment]
sure. we (defi pulse) can write this.

**Comment by Davidutro** [comment]
Scott, come into the #community-development channel on our [rocketchat](https://chat.makerdao.com/channel/community-development)

Let's talk there!

**Comment by scott-l-e-w-i-s** [comment]
i will not be adding another chat client to my desktop, but @ChazSchmidt will be. expect him soon.

**Comment by Davidutro** [comment]
Latest update:
Chaz gave permission for the contributors to use copy from the [guide he wrote for DefiPulse](https://defipulse.com/blog/zero-to-defi-cdai/) as long as we give him credit. He told me DefiPulse was comfortable with this as well.


Advaith and his friend will be working on this with me. Tuesday, Dec 10th we have a call.

**Comment by Davidutro** [comment]
Advaith on deadline to get first draft done by Jan 3rd

**Comment by Davidutro** [comment]
Will be mentioning that this task needs a fresh contributor to develop the doc further and get this thing done.

**Comment by aburban90** [comment]
https://docs.google.com/document/d/13SZ4EW_5R0P56vGmV3TxohQgbaE7GeVNm0Uc1hoTu2g/edit#

Need to get it out of the way.
I think it's MVP now, at least to pass along for review (legal?)
We'll clean it up more when we move to the new portal.

**Comment by Davidutro** [comment]
I will go through it on Sunday/Monday and give it a final review and my thoughts on whether it's ready to be released. Then pass it to legal after final touch ups.

**Comment by Davidutro** [comment]
Closing this issue as it is replaced with this new Epic
#679
