### ISSUE TITLE
update landing page README with new categorized headers

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#256]
Remove "Our Initiatives" and define top-level header categories to guide users on the portal.

Each sub-section will have elements of learning and contributing, but we want to guide users in different states 1. absorbing information ("passive" mode) and 2. Taking action ("active" mode). It should be a verb to align with Maker style guideline. Currently loosely grouped: 

- Learn (Alternatively: Resources, Educational)
Awesome-MakerDAO
MakerDAO FAQs

- Contribute (How do I take action to contribute my time?)
Community Meetup Grants
Community Translations
Development Grants
Hackathons and Bounties
Contributing

- Govern?
Governance

Categories will also define different maintenance plans.

**Comment by Davidutro** [comment]
Instead of `Contribute`, can we do `Participate` ?

I feel like it may be a more accurate word.

**Comment by Davidutro** [comment]
I actually still like the `Initiatives`/`Resources` pair.

### Participate / Initiatives

Community Meetup Grants
Community Translations
Development Grants
Hackathons and Bounties
Contributing
Governance

### Learn / Resources

Awesome-MakerDAO
MakerDAO FAQs
Onboarding

**Comment by ghettodev** [comment]
Something that includes the idea of a reciprocal relationship as well. i.e. Earn or something.

**Comment by Davidutro** [comment]
https://github.com/makerdao/community/pull/265

**Comment by amy-jung** [comment]
Created new categories Learn, Work With Us, and Funding: https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=36%3A1693
