### ISSUE TITLE
Reformat Landing Page for Portal

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#275]
-  should reference Call to Action
-  include most recent Governance community calls

**Comment by scottrepreneur** [comment]
Substrate has a nice example we can build on.
https://substrate.dev

**Comment by amy-jung** [comment]
@scottrepreneur and I are waiting to do a working session with @as-dr on Figma

**Comment by as-dr** [comment]
I’m back in the land of the living and will be 100% from next week.

I may be able to get started on this with you both towards the end of this week. I’ll attempt to coordinate that in the Maker chat in the next few hours.

**Comment by amy-jung** [comment]
This is paused while we wait for more research on moving forward with Docusaurus

**Comment by amy-jung** [comment]
Completed with new portal
