### ISSUE TITLE
Add new question to the Governance FAQ: What is a Spell and the Hat?

### ISSUE THREAD

**Issue by scottrepreneur** [makerdao/community#322]
There's probably some other things in here that could be described. I'll add some ideas if I think of any other specific ones.
https://community-development.makerdao.com/makerdao-faqs/faqs/governance#how-is-the-voting-calculated

**Comment by ghettodev** [comment]
If anyone in the community wants to take a crack at this one there is a small bounty available.

**Comment by amy-jung** [comment]
@Davidutro will take a look

**Comment by amy-jung** [comment]
Updated.
