### ISSUE TITLE
MCD FAQs Epic

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#324]
This is the top-level issue for MCD FAQs. The current status is that 5 are left to be completed as V1. The goal is to roll out the remaining FAQs as quickly as possible.

V2 will involve bounties that incentivize the community to offer suggestions and improvements to these docs. A series of bounties will occur in line with the V2s. Currently, we are thinking whether to do one at a time, 1x per week, or batches of 2-3 FAQs per week so we can get through this review process relatively quickly. I, David, am leaning towards doing these bountied reviews in batches.

[Planning Doc](https://hackmd.io/3lpxrCohSvmvKp_WNNlN8g)

_Note:_ 
- Cross-linking happens right before the final commit after everything is already in markdown
- I am trying to simplify and shorten them compared to the SCD versions. Answers should be concise, non-technical, and as accurate as possible. When needed, I offer links to additional resources that may dive into a question more technically.
- No community contributors necessary until after the initial launch of the bounties. The plan is to list several bounties to get the FAQs polished and properly cross-linked.
- Added Milestones V1 and V2; V1 is the initial release, and V2 is community reviewed and final approval from relevant people (legal +technical expert)

_Other Issues:_
- [ ] #403 - V2 MCD FAQs
- [x] #365 - Plan for the reorganization of Github for the new set of FAQs and Glossary of terms

The current priority for release and status list:

1. **Glossary of Terms**
- [x] V1 #326 
- [ ] V2 #413
2. **Liquidation**
- [x] V1 #327 
- [ ] V2 #414
3. **DSR**
- [x] V1 #328 
- [ ] V2 #416
4. **Stability Fee**
- [x] V1 #329 
- [ ] V2 #415
5. **Emergency Shutdown**
- [x] V1 #331 
- [ ] V2 #417
6. **Oracles**
- [x] V1 #330 
- [ ] V2 #418
7. **Vaults**
- [x] V1 #368 
- [ ] V2 #419
8. **Governance**
- [x] V1 #376 
- [ ] V2 
9. **Dai**
- [x] V1 #375 
- [ ] V2 #420
10. **MKR Token**
- [x] V1 #378 
- [ ] V2 
11. ~Risk Management~
- [ ] ~V1 #377~
12. **Keepers**
- [ ] V1 #374 
- [ ] V2
13. **MakerDAO**
- [x] V1 #423 
- [ ] V2

**Comment by Davidutro** [comment]
Question:

Does it make sense to have a protocol security FAQ?

**Comment by ghettodev** [comment]
Not sure what protocol security means in this context.

**Comment by Davidutro** [comment]
The GSM, OSM, and ESM

should they be in a special Security Features FAQ?

Or just live in their respective domains:
GSM - Governance FAQ
OSM - Oracles FAQ
ESM - Emergency Shutdown FAQ

probably the latter, and we can just maintain cross-linking when relevant

**Comment by Davidutro** [comment]
I have a local folder ready with all the changes to makerdao/community
Have not pushed a PR yet.

**Comment by Davidutro** [comment]
Need to add to AMD once the PR is committed

**Comment by Davidutro** [comment]
PR pushed, AMD updated.

Next items on priority list are the get the remaining FAQs out in this order:

1. Keepers
2. Dai
3. Governance
4. Risk Management
5. MKR Token
6. Keepers

**Comment by Davidutro** [comment]
Marcin idea: To submit a commit with a message under the header of each SCD FAQ that links to the MCD version and disclaims that that is an FAQ for the old version of the Make Protocol

**Comment by aburban90** [comment]
@Davidutro the links above... these are the MCD FAQs to review?

**Comment by Davidutro** [comment]
Community sign off can be managed through the forums.

**Comment by Davidutro** [comment]
Added this to top-level comment, but just an updated status for the year:

The current status is that 5 are left to be completed as V1. The goal is to roll out the remaining FAQs as quickly as possible.

V2 will involve bounties that incentivize the community to offer suggestions and improvements to these docs. A series of bounties will occur in line with the V2s. Currently, we are thinking whether to do one at a time, 1x per week, or batches of 2-3 FAQs per week so we can get through this review process relatively quickly. I, David, am leaning towards doing these bountied reviews in batches.

Open to hearing thoughts on whether another way might garner better results.

Ultimately though, anyone can offer an improvement in the future if needed.

**Comment by Davidutro** [comment]
Reminder: Ping Tom, give him the option of working on one of three of the remaining FAQs

MKR Token | #378
Risk Management | #377
Keepers | #374

Tom needs to pick one and provide the timeline/cost/reasoning
Talk to Amy about whether this needs to go through C-dip process

**Comment by Davidutro** [comment]
Need to close finished V1 issues,
Open new issues for FAQs ready for V2

**Comment by Davidutro** [comment]
#374 last one is not done yet. ALMOST RICH, ALMOST

**Comment by Davidutro** [comment]
Goodnight sweet prince. You were a big boi

FAQs replaced by Learn pages in the new comdev portal
