### ISSUE TITLE
Glossary of Terms MCD rework

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#326]
_Parent Issue: https://github.com/makerdao/community/issues/324_

The [current Glossary of Terms](https://community-development.makerdao.com/makerdao-faqs/faqs/glossary) is specific to SCD. This task is to rework the Glossary for Multi-Collateral Dai. 

Goal: Get a completed list ready for launch with MCD on November 18th

Some basic rules for contributing:
- Use ~~strikethrough~~ for removing obsolete questions or terms
- **Bold** new additions

Working doc: 
[MCD Glossary of Terms Draft](https://hackmd.io/0IAUAZrXTJWk7qX1Yz8h-g)

**Comment by Davidutro** [comment]
created and reviewed local .md file in my fork of the /community repo
added all the definitions

still missing cross-links

**Comment by ghettodev** [comment]
Committed 15 days ago. Closing.
