### ISSUE TITLE
DSR FAQ for MCD

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#328]
_Parent Issue: https://github.com/makerdao/community/issues/324_

There is currently no DSR FAQ. This task is to create it.

Goal: Get V2 milestone completed by getting sign-off from Fennie & Kenton

Status: Before sending the live FAQ to Kenton and Fennie for sign-off I am considering posting this to the community for review. Need to create a bounty.

Working doc: 
[DSR FAQ](https://docs.google.com/document/d/1Osp67GniEtABKEYBNyzR1OhXedFA05KkOYNtgHTm_Go/edit#heading=h.kr3hzx1ncr99)

**Comment by Davidutro** [comment]
Did a run-through of DSR. 

I spoke with Kenton and Wouter to get some clarity on a few answers. 
The FAQ is pretty short and sweet, so it shouldn't be too much more work.

**Comment by Davidutro** [comment]
Added the question and answer for "How is the DSR being used by MKR token holders as a monetary policy tool?"

Sent link to Kenton requesting a look-over for mistakes

**Comment by Davidutro** [comment]
created and reviewed local .md file in my fork of the /community repo

still missing some cross-links

**Comment by Davidutro** [comment]
pushed a PR today which updated some language in response to feedback from Fennie and Andrew Burban

**Comment by ghettodev** [comment]
PR was accepted, closing.
