### ISSUE TITLE
Emergency Shutdown FAQ MCD Rework

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#331]
_Parent Issue: https://github.com/makerdao/community/issues/324_

The [current Emergency Shutdown FAQ](https://community-development.makerdao.com/makerdao-faqs/faqs/emergency-shutdown) is specific to SCD. This task is to create a new Emergency Shutdown FAQ for MCD. 

Goal: Get a completed version ready for launch with MCD on November 18th

Status: Direct working doc is closed to public contributors for now.

Working doc: 
[MCD Emergency Shutdown FAQ](https://docs.google.com/document/d/1qhV0WOc377c7NpN_Pf6Tpy4sJTYsNXU3L0E9Ce9gLY4/edit#)

**Comment by Davidutro** [comment]
created and reviewed local .md file in my fork of the /community repo

still missing some cross-links

**Comment by ghettodev** [comment]
Looks like this was merged and the copy looks good. Is there any additional review to be done here?
