### ISSUE TITLE
Translations: Data & Requirements gathering

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#347]
## Data & Requirements gathering

Marcin's V1: [Nov 2019 Popularity analysis of FAQ translations.pdf](https://github.com/makerdao/community/files/4032792/Popularity.analysis.of.FAQ.translations.pdf)

### General overview

- Gather the analytics
    - export a Google Analytics report for the team to review in PDF
    - make basic guesses about what languages are providing immediate value
    - plan internally with community and community managers to figure out a narrative behind the numbers
    - informs the priority list of languages and content

- Requirements gathering 
    - insight from the community leads
    - interview Mariano and Kathleen about translation requirements

### Concrete Tasks(should be done in order as some are dependent and can better inform the latter tasks.)

- [ ] Interview Mariano and Kathleen about translation requirements
_There is an internal bi-weekly community manager call. I can ask if would be welcome to use that as the place to ask them questions about this_
- [ ] Brainstorm what queries you want from the Google Analytics
- [ ] Export a Google Analytics report for the team to review in PDF

#### Brainstorm what queries you want from the Google Analytics

Questions we are trying to answer:
1. What are the top pages people are looking at from the set of non-English pages only?
2. Are there similarities in the popularity of certain pages across multiple languages?
3.

**Comment by ghettodev** [comment]
Adding @reuptaken as a read only viewer for the portal to examine translation metrics.

**Comment by Davidutro** [comment]
[Popularity analysis of FAQ translations.pdf](https://github.com/makerdao/community/files/4032792/Popularity.analysis.of.FAQ.translations.pdf)
