### ISSUE TITLE
Translations: Figure out if the current process is working and how we can make it better

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#350]
Current process: https://hackmd.io/kpjDvDVIQaS5aPwb8PPKhQ?view#Current-Process

Emphasis on reproducibility in case Marcin disappears :) 

current status:
All of Marcin's stuff is shared with us publicly and is not at high risk of being lost.

**Comment by amy-jung** [comment]
Open question: Is the Github translations board effective?

**Comment by reuptaken** [comment]
It's not a tool I use for myself (for my internal progress checking I use Google sheet). It adds a bit of overhead but it's manageable. 

Is anyone using the board as a source of information about translations? I don't know.

**Comment by ghettodev** [comment]
continue with current process, revisit after translations restart.

**Comment by ghettodev** [comment]
Moving to icebox.

**Comment by Davidutro** [comment]
Since the new Community Development Portal will include tools for adding translations soon, we need to rethink the flow from scratch. If there is a more recent issue for that, adding a link to it in a comment below would be helpful @twblack88 

 I am closing this issue.
