### ISSUE TITLE
Standardize method for summaries of G&R Meetings

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#354]
In the spirit of making routine things reproducible and high quality, this task is to create an addition to the community portal's Contributor section of standards for producing recurring summaries of the Governance & Risk call.

Working Doc:
https://hackmd.io/wZ5onc4-TzyLeswSfJ1ZbQ

**Comment by amy-jung** [comment]
@Davidutro what's the update on this?

**Comment by Davidutro** [comment]
@amy-jung 

Will be doing a V1 release in a couple of weeks, hopefully sooner.
The last couple of weeks the summary QA was done by me in a bit of a rush so I wasn't working on this doc.

The following weeks I will have more room to focus and sharpen the doc. 

I want to say i'm hoping to release EOD March 16th

**Comment by amy-jung** [comment]
Merged
