### ISSUE TITLE
Awesome MakerDAO: Documents and links need review and cleaning up

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#361]
[Project Planning Doc](https://hackmd.io/UGAkkqWTQv-a7Gsz2yRfyw)

- [x] Resources and links need review and cleaning up
- [x] Consistent formatting
- [x] Include lightweight MCD official postings
- [x] Edit Awesome-MakerDAO to be consistent with the [Contributor's Style Guide](https://github.com/makerdao/community/blob/master/contributing/style-guide.md)

**Comment by amy-jung** [comment]
@aburban90 is working on this: [Working AMD Doc: Andrew Burban](https://hackmd.io/jCtXTqGURSCtOZs8UOknqA)

**Comment by amy-jung** [comment]
@aburban90 :

- I like the intro broken down as shown now. It's easier to digest core concepts
- adding brief/one sentence on MKR token in overview. maybe in the governance section
- should we introduce abbreviations in parenthesis beforehand? ie: "The origin of all Dai is the CDP smart contract. CDPs hold collateral asset..." > "The origin of all Dai is the Collateralized Debt Position (CDP) smart contract. CDPs hold collateral asset..."
- (to bring up in today's convo) should we change vocab already to match MCD or should it still hold some historical/backstory? IE: "CDP" to "Vault", etc
- I would bring "awesome makerdao" section up to the very top, then start with overview
- I don't think you need bullet points for "Please Be Advised" since it's a short section
- alphabetized platforms under "Channels" for easier search
- strangely japanese FAQ repo says /en for me. (pic below) all other ones are fine
- do we want to make sure grantees are listed in the resources (if so, should we state that in the disclaimer)
- Include Monolith.zyx in the Dai resource list

Notes from the Nov. 13, 2019 call:
- Add separate sentences about each of the following: Foundation, DAO, and community
- Regarding MCD. Let's stick with "Good enough" for first take. Next week, we'll work with David on incorporating new vocab like Vault/Dai/Sai
- Remove headers in intro/turn them into bold
- no spacing inbetween line items (check markdown formatting either on awesome-makerdao or make a different branch on Github) two space at the end of a line is a hard return, but we want to avoid formatting issues on other places the repo may be used
- We'll leave comments on github issues and project planning hackmd under "call notes"- NOT hackmd comments (too hard to see)

**Comment by aburban90** [comment]
no pic?

**Comment by aburban90** [comment]
WeChat is a weird link?
Just to wechat.... ive never used.
Is Makershequ a channel?
Is there better way to name it?

**Comment by aburban90** [comment]
> We'll leave comments on github issues and project planning hackmd under "call notes"- NOT hackmd comments (too hard to see)

This is the correct thread I assume, right?

**Comment by aburban90** [comment]
Those interested in MakerDAO are invited to explore AMD's collection of resources below. Get to know Maker with the help of beginner guides, official documentation, analysis pieces, tools, partnership announcements, AMAs, podcasts, and third-party apps, **and much more.**

@amy-jung don't like "and much more" but can't think of anything better. Any ideas?

**Comment by aburban90** [comment]
Where should I throw this? Seems to stick out

## Network Updates
- Changelog: Multi-Collateral DAI Public Releases

**Comment by aburban90** [comment]
- Moved translated/foreign stuff to their own section


- Removed italics from Custodial Exchanges and Other Stablecoin Projects
  - I liked it... but didn't seem to go... semi inconsistent with everything else

What do we think looks better?

**Option 1:**

#### Other Stablecoin Projects

- [AMPL: Ampleforth](https://www.ampleforth.org): Algorithmic Stability
- [CUSD: Carbon](https://www.carbon.money/): Algorithmic Stability
- [USDC: Coinbase](https://www.centre.io/usdc/): USD Backed
- [GUSD: Gemini](https://gemini.com/dollar/): USD Backed
- [NUSD: Neutral](https://dapp.neutralproject.com/): Metastable Stablecoin Basket
- [PAX: Paxos](https://www.paxos.com/pax/): USD Backed
- [RSV: Reserve](https://www.reserve.org/): Collateral Backed
- [SU: StableUnit](https://stableunit.org/): Collateral Backed
- [SUSD: Synthetix](https://www.synthetix.io/): Collateral Backed
- [TUSD: TrustToken](https://www.trusttoken.com/trueusd/): USD Backed
- [USDT: Tether](https://tether.to/): USD Backed

**Option 2:**

#### Other Stablecoin Projects

- [AMPL: Ampleforth](https://www.ampleforth.org): 
  - Algorithmic Stability
- [CUSD: Carbon](https://www.carbon.money/): 
  - Algorithmic Stability
- [USDC: Coinbase](https://www.centre.io/usdc/): 
  - USD Backed
- [GUSD: Gemini](https://gemini.com/dollar/): 
  - USD Backed
- [NUSD: Neutral](https://dapp.neutralproject.com/): 
  - Metastable Stablecoin Basket
- [PAX: Paxos](https://www.paxos.com/pax/): 
  - USD Backed
- [RSV: Reserve](https://www.reserve.org/): 
  - Collateral Backed
- [SU: StableUnit](https://stableunit.org/): 
  - Collateral Backed
- [SUSD: Synthetix](https://www.synthetix.io/): 
  - Collateral Backed
- [TUSD: TrustToken](https://www.trusttoken.com/trueusd/): 
  - USD Backed
- [USDT: Tether](https://tether.to/): 
  - USD Backed
  
**Option 3:**

#### Other Stablecoin Projects

- [AMPL: Ampleforth](https://www.ampleforth.org): 
  - *Algorithmic Stability*
- [CUSD: Carbon](https://www.carbon.money/): 
  - *Algorithmic Stability*
- [USDC: Coinbase](https://www.centre.io/usdc/): 
  - *USD Backed*
- [GUSD: Gemini](https://gemini.com/dollar/): 
  - *USD Backed*
- [NUSD: Neutral](https://dapp.neutralproject.com/): 
  - *Metastable Stablecoin Basket*
- [PAX: Paxos](https://www.paxos.com/pax/): 
  - *USD Backed*
- [RSV: Reserve](https://www.reserve.org/): 
  - *Collateral Backed*
- [SU: StableUnit](https://stableunit.org/): 
  - *Collateral Backed*
- [SUSD: Synthetix](https://www.synthetix.io/): 
  - *Collateral Backed*
- [TUSD: TrustToken](https://www.trusttoken.com/trueusd/): 
  - *USD Backed*
- [USDT: Tether](https://tether.to/): 
  - *USD Backed*

**Comment by aburban90** [comment]
"do we want to make sure grantees are listed in the resources (if so, should we state that in the disclaimer)"

@amy-jung elaborate?

**Comment by aburban90** [comment]
Changelog apppears few times


#### Contracts

> Can probably axe this
> _While MCD is on a TestNet, contract addresses are subject to change. Visit [changelog.makerdao.com](https://changelog.makerdao.com/) for up-to-date information._

**Comment by aburban90** [comment]
> Where should I throw this? Seems to stick out
> 
> ## Network Updates
> * Changelog: Multi-Collateral DAI Public Releases

I threw it under milestones:

## Miltstones
### Governance Polls
xxxxxx
### Network Updates
xxxxxx

**Comment by aburban90** [comment]
@amy-jung you threw a bunch of comments in on my doc... they were sorta hidden. I'm pretty sure I moved stuff around, but the comments didn't necessarily move. Check the intro... make sure the comments you had are still valid.

More visible option, I think, would be to add a Code or Quote section directly to the doc... and I'll definitely see it then.

------- 

as for updating terminology (one of your comments), been semi slacking on staying in the loop. I think there's a glossary of new terms?... but I haven't come across it yet

**Comment by aburban90** [comment]
@amy Updated Milestones... broke it up by year
Would be nice to find stuff from earlier, but the makerblog web archive seems to be dead

let me know what you think

**Comment by aburban90** [comment]
Official Meetings
Community Meeting needs zoom call link added
- Does the link stay the same each week?
Community Meeting Youtube playlist starts at May 7th instead of recent 
 - How do you invert it to start with latest?

**Comment by aburban90** [comment]
Assorted Translations
Translated Resourses 

@amy-jung  @Davidutro 

I left typo in "Resources" and the link doesnt work from TOC to the section itself

**Comment by amy-jung** [comment]
We'll be starting a fresh hackmd based from [the last commit](https://github.com/makerdao/awesome-makerdao/commit/a566db57a645cbe33e7fbecca11333c5687ec030#diff-04c6e90faac2675aa89e2176d2eec7d8).

@aburban90 will link here

Will finish up cleaning remaining links, and sections. For developer guides - 
Double check the links since a lot of the new mcd info should be in docs.makerdao.com , so we can link there. Touch base with @Davidutro since he last updated the developer guides.

**Comment by aburban90** [comment]
New HackMD
https://hackmd.io/TARaxB0dRJGf53xmU2GBQw?both

**Comment by aburban90** [comment]
Added
- [Neutrality](https://dapp.neutralproject.com/#/)
Keep? Delete?

**Comment by aburban90** [comment]
https://daicard.io/
thoughts?

**Comment by amy-jung** [comment]
Intro:
(Get Started):
"Those interested in MakerDAO are invited to explore AMD’s collection of resources below. Get to know Maker with the help of beginner guides, official documentation, analysis pieces, tools, partnership announcements, AMAs, podcasts, and third-party apps, and much more." 
- I'd just remove the "much" and say "more"
 
(MakerDao):
"The Maker Protocol employs a two-token system. Dai, a collateral-backed stablecoin, offers stability, while MKR, a governance token, is used by stakeholders to maintain the system and manage Dai." 
- should it be DAI in this case: "DAI, a collateral-backed stablecoin, offers stability, while MKR, a governance token, is used by stakeholders to maintain the system and manage Dai."

- Should we be linking here?
(The Maker Foundation): The maker Foundation
- (Dai/Vaults): The Vault Portal

Dai:
- I would opt to do a parenthesis after Oasis (Vault), Coinbase (Earn Dai) or the opposite - Vault (Oasis), Earn Dai (Coinbase) over a | since | denotes two separate entities or concepts (see Hold Dai).

Watch Dai (Analytics and Metrics):
- DeFi.ai should go above DeFiTracker

Milestones | Achievements:
- we should add:
https://blog.makerdao.com/single-collateral-dai-to-multi-collateral-dai-upgrade-timeline-and-actions/
and/or
https://blog.makerdao.com/what-to-expect-with-the-launch-of-multi-collateral-dai/

**Other notes:**
- I think Translated docs should be a subsection of each section or the entire section should be moved up before Governance.
- I'm going to vote no on Neutrality because it hasn't been live very long and audited (But I can be persuaded otherwise)
- Yes to Dai card since Connext is a Project.
- Do we want to make sure grantees are listed in the resources (if so, should we state that in the disclaimer)?" cc @ghettodev 
- (Governance): Is this section is ordered by learning level (as opposed to newest/oldest)?

**Notes for us to think of later:**
- (Eventually) we link the Maker Foundations grants program offers.." bounties" to our bounties
- MKR - capitalization rule should be in the copy style guide

**Comment by amy-jung** [comment]
@aburban90 will submit a PR for review today, @ghettodev will review - need to settle preamble

**Comment by aburban90** [comment]
axed neutrality, added dai card

**Comment by aburban90** [comment]
Not sure what to do about the translated resources? (or archived for that matter... thinking to kill it?)

At least, for what's there, not much translated stuff....I can put placeholder translations section on each though


- Where would grantees go? @ghettodev 


(Governance): Is this section is ordered by learning level (as opposed to newest/oldest)?
- I just have it newest/oldest... well... seems like oldest-> newest

**Comment by aburban90** [comment]
maybe put bounties/grants under Earn Dai?

**Comment by ghettodev** [comment]
I feel like this ticket may have reached it's breaking point and most things seem to have been completed. Can we close it and move any outstanding tasks into new issues?
