### ISSUE TITLE
Plan for reorganization of Github for the new set of FAQs and Glossary of terms

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#365]
Rich and I came to an agreement on this:

The new FAQs will go into the old FAQs repository so that all legacy links to FAQs are preserved.

The old SCD FAQs and their translated counterparts will be placed into a new section called "SCD FAQs"/"Legacy FAQs"

**Comment by scottrepreneur** [comment]
https://github.com/makerdao/community/pull/367
