### ISSUE TITLE
Create a "Tools" Guide for Contributing Section

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#385]
The contributing section should improve contributor experience and onboarding. Guides should remove the barriers for community members to be part of the team, improve community resources, give and receive feedback, and grow the MakerDAO community.

[Working Doc](https://hackmd.io/JKv26kagS5eTGnpgMpBxUA?view)

[Project Planning Doc](https://hackmd.io/@rawhaus/rJX6JE3jH)

**Goals**
- [x] How to submit a PR and issues
- [x] [Fix a Commit](https://github.com/RichardLitt/knowledge/blob/master/github/amending-a-commit-guide.md)
- [x] Tutorials

**Comment by amy-jung** [comment]
@twblack88

**Comment by twblack88** [comment]
[Workflow doc is now the tools doc](https://hackmd.io/JKv26kagS5eTGnpgMpBxUA?view
)

**Comment by amy-jung** [comment]
@twblack88 please link your PR to this issue :)
