### ISSUE TITLE
Improve Contributing Section FAQs

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#386]
The contributing section should improve contributor experience and onboarding. Guides should remove the barriers for community members to be part of the team, improve community resources, give and receive feedback, and grow the MakerDAO community.

This is V2 

[Current Working Doc](https://hackmd.io/@rawhaus/HyA_DaxfL/edit)
- Add a question about Github contributions / #227 

[Larger Project Planning Doc](https://hackmd.io/@rawhaus/rJX6JE3jH)

**Comment by amy-jung** [comment]
Tied to: #227

**Comment by amy-jung** [comment]
Also include: #227  (but this may be covered by Tools Guideline #385 )

**Comment by aburban90** [comment]
https://hackmd.io/vnDKBcqLRY25cpAruvK83Q?both

The hackmd is either private, or dead link

@amy-jung

**Comment by amy-jung** [comment]
Try this: https://hackmd.io/@rawhaus/HyA_DaxfL/edit

**Comment by amy-jung** [comment]
@TomDeMichele is working on this

**Comment by amy-jung** [comment]
Closed with PR #511
