### ISSUE TITLE
Update Copy Style Guide for Contributing Section

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#387]
The contributing section should improve contributor experience and onboarding. Guides should remove the barriers for community members to be part of the team, improve community resources, give and receive feedback, and grow the MakerDAO community.

[Working Doc](https://hackmd.io/FOSfAmyuTgK6Z9epMi5hqQ)

Reference comments in #231 

- Update name to "Writing or Written Style Guide"
- Update with grammar tools? 
- Move some content to different pages (Tooling or editor's guide)
- Add content from Marcin's user doc: [#134: MakerDAO documentation Framework needs refining](https://github.com/makerdao/community/issues/134)

[Project Planning Doc](https://hackmd.io/@rawhaus/rJX6JE3jH)

**Comment by Davidutro** [comment]
Adding @aburban90's comment from the older issue here:


Add to Style Guide:

Add to Style Guide:
- Whole Text Editors:
    - Grammarly (https://app.grammarly.com/)
        - Mistake-Free Writing Editor
    - HemingwayApp (http://www.hemingwayapp.com/)
        - Make writng bold and clear
- Word and Phrasing Suggestions
    - Thesaurus (https://www.thesaurus.com/
        - Single Word Suggestions
    - Powerthesaurus (https://www.powerthesaurus.org/)
        -  Phrase Suggestions
    - WordHippo (https://www.wordhippo.com/)
        -  Phrase Suggestions

**Comment by aburban90** [comment]
@amy-jung  closed?

**Comment by aburban90** [comment]
Is there a working doc?

**Comment by aburban90** [comment]
Live: https://github.com/makerdao/community/blob/master/contributing/style-guide.md

**Comment by aburban90** [comment]
@amy-jung Naming options:
Writing Style Guide _[Picked this one for now]_
Community Style Guide
Community Writing Style Guide

I think Writing Style Guide works... I am updating AMD Maintenance doc to match.

**Comment by amy-jung** [comment]
My raw notes:

https://hackmd.io/@rawhaus/HyOS_8xmL/edit
