### ISSUE TITLE
Create project plan for weekly status update for MKR voters Epic

### ISSUE THREAD

**Issue by ghettodev** [makerdao/community#393]
## Description

We need to present a one-pages rollup of the weeks events in order to give voters the confidence to make informed decisions. 

- should have standardized KPI's 
- maybe link to a custom dashboard
- condensed version of highlights from the summary
- links to relevant resources for deeper research

Will finish the below later...

- should be compatible for tweet, email it, find it in the gitbook archives, etc. 

[Working or Proposed Project Doc](https://hackmd.link)

## Tasks

- [ ] Task 1
- [ ] Task 2 / [If relevant, any linked Github Issue number](https://link)
- [ ] Example: Standardize operation procedures / [#359](https://github.com/makerdao/community/issues/359)

## Bounties (If relevant)

- [Title of Bounty - Platform](https://link.me)
- [Example: Find and update deadlinks in FAQs](https://explorer.bounties.network/explorer)

**Comment by amy-jung** [comment]
Fulfilled by Adrian's DAI-gest #431
