### ISSUE TITLE
Dead Link: Glossary of Terms link under Capitalization heading in Style Guide.

### ISSUE THREAD

**Issue by LongForWisdom** [makerdao/community#405]
https://community-development.makerdao.com/contributing/style-guide#capitalize

The link to 'Glossary of Terms' within this section resolves to a github 404. 

Link target: https://github.com/makerdao/community/tree/15a59c0a290c93d761c3f1325cba74b721221565/contributing/community/faqs/glossary.md

Possible fix: https://community-development.makerdao.com/makerdao-mcd-faqs/faqs/glossary ?

**Comment by amy-jung** [comment]
Submitted a PR
