### ISSUE TITLE
CDIP4: RocketChat bot @scottrepreneur

### ISSUE THREAD

**Issue by scottrepreneur** [makerdao/community#412]
## Brief Program Description
[//]: <Notes> (Provide context. What are we working on? Keep it concise. One sentence if possible.)

`@mkr.bot` is a friendly resource sleuth and command runner that is built for MakerDAO (specifically RocketChat for right now).

Commands generally look like:
* `faqs topic` i.e. `faqs vault`, `faqs keepers`
* `amd topic` i.e. `amd spend dai`, `amd lend dai`
* `check spells`, `vault {id}`

## Project Goal & Scope
[//]: <Notes> (Why are we working on this?)
"S-medium" scope
* **Long Term (Mission Orientated):** Reduce burden on current community members onboarding new members and encouraging their contributions.
* **Short Term (Action Orientated):** Reduce number of duplicated work curating resources and running technical commands.

## Deadlines or Timelines
[//]: <Notes> (Avoid arbitrary dates. Define a goal or reason for this to move towards.)

**Idea:** Created bot with spells command
**Then:** Added Resources - faqs and amd links
**Next:** Curate additional resources and commands
**After:** Implement additional resources/commands
**Would be neat:** Handle in-chat tipping

**Comment by twblack88** [comment]
[x] Scott emails RB budget/estimate for next dev steps (guessing about 5 hours?)
[x] Cross Internal maker teams for rocketchat instance access (Devops)
[ ] Scott makes the bot responds to commands
[ ] @Davidutro ,  and Tim add resources to command spreadsheet
[ ] Test in chakachat only with whole comm dev team. Use communtiy resources and current scripts in commands
