### ISSUE TITLE
CDIP 2 - Non-transferable Badges for Maker Ecosystem Activity

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#433]
**Title:** Non-transferable Badges for Maker Ecosystem Activity

**Your name/handle:** @ lix 

**Links to Github issue/forum post/ or discussion thread:** https://chat.makerdao.com/channel/general?msg=ukvxuysoTugky9aY9

**Proposal abstract:**
A video game like “achievement” would be a fun way to engage users. It gives all participants (large and small) a way to be proud of their on chain activity and show off to their peers. These badges would only have personal value since they would be non-transferable. Some ideas for individual badges which users could claim:

- opening a Vault/CDP
- vote in a governance poll
- vote in an executive
- use the DSR
- transfer 100 DAI, transfer 1000000 DAI, etc
- locked MKR in chief for over 180 consecutive days, 365 days, etc

Much of the implementation for an idea like has already been done here: https://github.com/poapxyz/poap

I think Mariano Conti did a poap NFT for his birthday party, so ask him how it went if you’re exploring this idea. The only difference is that the poap smart contract would have to be changed to not allow transfers of the badges. Or, if transfers were allowed, they would only be allowed by the owner address. I’ve looked into non-transferable badge EIPs such as https://github.com/ethereum/EIPs/issues/1238 and https://github.com/ethereum/EIPs/issues/735
The non transferable claim seems to have gained the most traction so far in the ethereum community, but it is still hard to see a clear winner as far as which claim standard will become mainstream.

From Maker's point of view, here is how the badges would work:

On the backend, we run a script every hour that checks for new badges.
User 0xabe1 logs into metamask, goes to badges.makerdao.com
If 0xabe1 is on the list of claimable badges, then we sign a message with our issuance key saying that “0xabe1 can claim the DSR badge at 0x2345”
The user signs the signed message above. This proves that both parties want the badge issued, and the issuer (Maker) can execute the transaction and issue the badge. Maker pays the gas for this transaction.

[CDIP2](https://docs.google.com/document/d/1-R-Uln3mXtioawSiUZhPLmhRqCr9WRbqZ1c12fbNuS8/edit?usp=sharing)

**Comment by amy-jung** [comment]
Was approved to move forward into execution. Unfortunately Lix ran out of bandwidth to continue. It's open for others to tackle

**Comment by twblack88** [comment]
I think with the closing of #536 this is all set!
