### ISSUE TITLE
Fix "Governance FAQ" link

### ISSUE THREAD

**Issue by john-light** [makerdao/community#441]
## Description

"Governance FAQ" link in [this section](https://github.com/makerdao/community/blob/master/faqs/mkr-token.md#what-voting-rights-do-mkr-holders-have) of the FAQ leads to a 404 page.

Also, "Voter Onboarding Guide" in that same section says "insert link" rather than actually linking to the guide.

**Comment by amy-jung** [comment]
Awesome thanks John! Tagging @Davidutro to roll up in next PR

**Comment by Davidutro** [comment]
Leaving it since I will need to change it back anyway. 

The new governance FAQ under that link will be released soon
