### ISSUE TITLE
Create bounties for producing Media from your meetups

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#446]
## Description

We want to set up some ongoing bounties for meetup organizers to be incentivized to do cooler and more impactful stuff with their meetups. This is specifically for creating Media like photos, videos, blog posts, and more.

[HackMD for sample bounty texts](https://hackmd.io/X-S_X9fJSqm0mgDEpLsYFw)

## Tasks

- [ ] Task 1 / Create list of bounty types and payouts
- [ ] Task 2 / Create draft text for each of those bounties

## Bounties

- [Bounties Network](https://explorer.bounties.network/explorer)

**Comment by amy-jung** [comment]
Perhaps sync with Simona on Pepo/Intro to Blockchain

**Comment by Davidutro** [comment]
This issue is up to date in principle, it is backlogged and still something I want to devote time to in the coming months.

Leaving it in the Meetups Program Epic since I will revisit and clean this issue up when further developing the program.

**Comment by Davidutro** [comment]
Backlogged this in CDC, need to think of way to make this lighter. Bounties take up a lot of maintenance and operational overhead.

**Comment by Davidutro** [comment]
not happening
