### ISSUE TITLE
Create a "Submitting Invoices Guide"

### ISSUE THREAD

**Issue by TomDeMichele** [makerdao/community#455]
The submitting invoices guide walks contributors through how to create an invoice. It covers everything a person needs to know to get paid, so it covers tracking hours, formatting an invoice, submitting an invoice, and some FAQ.

old:
[working doc](https://docs.google.com/document/d/1fAZAa4uYztEjjTC_uRNTzjfKegHpQPJ06UGxBq-YIFk/edit?usp=sharing)
[current template](https://docs.google.com/spreadsheets/d/1e2Wq2S3inxHucIJCfrxG5Nhjoc4ITb7CfUN42gPx-z4/edit#gid=1329408724)

Links to the official docs:
[Invoice Guide(Google Doc)](https://docs.google.com/document/d/1fpxm8l7DSKolp1KBogxKwt948FZTl1vPSncGai0qvVo/edit?usp=sharing)
[Invoice Guide(.pdf)](https://drive.google.com/open?id=1D5_dhKED5ZwWX6j1EKjFuJIvSJ0wBZdM)
[Itemized Invoice template(Google Sheets )](https://docs.google.com/spreadsheets/d/1Ccdkw89Ozqjz3krDgIajNz45jznP4TMPd67Voa0x2_A/edit?usp=sharing)

Tasks

- [x] Create template
- [x] Include details on how & who to request from request network

**Comment by amy-jung** [comment]
Turned into a PDF to share when requested

**Comment by TomDeMichele** [comment]
To confirm this is ready to be turned into a PDF to share as requested, the user will also need a copy of the spreadsheet. Feel free to take a final look, but it should all be ready to go.

**Comment by Davidutro** [comment]
Ok, I made a copy of the template so it can live in our internal files and have done the same for the invoicing guide itself.

I'll make a PDF and put it there as well.

**Comment by Davidutro** [comment]
Closing issue, marking it complete.
