### ISSUE TITLE
Add new question about meetup themes to Meetups FAQ

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#459]
Add "Does the meetup theme need to be exclusively about MakerDAO?"

**Comment by Davidutro** [comment]
No it doesn't. It can be Defi more broadly. As long as the meetup includes Maker/Dai and mentions this meetup program they qualify.

p.s. sorry for seeing this so late

**Comment by amy-jung** [comment]
No, I mean add the question + answer to the FAQ

**Comment by Davidutro** [comment]
Need to keep this issue in mind when I go over the meetup program FAQ next. Will do so as part of the maintenance cycle testing/planning phase.

I linked this in #594
