### ISSUE TITLE
CDIP 11 - Content distribution framework for Comm-Dev

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#538]
**Title**: Content distribution framework for Comm-Dev 

**Your name/handle**: @mkrtomalpha

**Links to Github issue/forum post/ or discussion thread**: From our Community initiative “discoverability” there was this blog post in addition to several community initiatives that could use a more aligned marketing effort without straining MakerDAO’s marketing team.

**Proposal abstract**: The best way to spread awareness of Comm-Dev is for other people to spread awareness for you. For that to happen people have to discover your content.  Thus creating content people want to share, aiming to rank for key terms, syncing on distribution team wide, and linking to pages and platforms people already use is important. The proposal is to:
- [x] Create a posting workflow (URL, title, tags, tracking/analytics etc,) 
- [x] Distribution blueprint
- [x] A boilerplate/structure/outline that could be replicated on every post that needs discoverability. 
- [x]  A short deck to explain how they work for Comm-Dev ( presented on a Weds call). 
- [ ] Host this deck on the Comm-Dev portal near the writer's guide, in contributing. 

Ideally, this deck will be broadly applicable to already active contributors and future contributors who want to interact with comm-dev and/or the Foundation. The end result should be an ongoing answer to the “discoverability” question regardless of what type of content a contributor is working on.

**Comment by TomDeMichele** [comment]
Current working notes on this project. Request access as needed https://docs.google.com/document/d/15SjSZ9FvMBfnL-kGyQR2LI5FfxVSMPtzKjfZAbPctio/edit?usp=sharing

**Comment by twblack88** [comment]
This was wrapped up into #720 and delivered on sept 2.
