### ISSUE TITLE
Portal Redesign (Content): Create a CMS/component guide / training

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#565]
## Description

Once components are finished, short documentation should be created and sessions scheduled to explain their usage to anyone who wants to play a larger role in editing and maintaining content on the site. 

Maintaining site content will require a bit more technical know-how than before as React components are a lot more temperamental than markdown.

**Comment by amy-jung** [comment]
@twblack88 and Dev team are working on this

**Comment by twblack88** [comment]
Named installation-guide.mdx and with a couple of rounds of content clean up. It is currently in `hidden` pages until we map that user experience better.
