### ISSUE TITLE
Portal Content Sprint: Work with us/Bounties

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#583]
## Description
Suggested content already exists in the Work with us and Funding sections. The content team should review these pages against what exists.

Lead/Writer: @TomDeMichele
Reviewer: @amy-jung 

- [ ] [Action Page](https://www.notion.so/Work-with-us-action-page-example-Translations-e55a774d099b4a458d16a617eb0f23cd) | Work with us/Bounties
- [ ] [Process Page](https://www.notion.so/Process-page-example-using-GitHub-ad1e9bdc00214d4aa2fad4e7244d7821) | Work with us/Bounties/Working on a bounty

[Link to Working or Proposed Project Doc](https://hackmd.link)

## Steps
1. Review [Writing Style Guide](https://community-development.makerdao.com/contributing/writing-style-guide)
2. [Download the .md files](https://github.com/ryancreatescopy/community)
3. Work in hackmd (for comments/suggested edits) (We’ll be skipping google docs)
      - View [prototype](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=355%3A73) to get a sense of end goal
      - Make sure content fits Page Template model ([Linked in google sheet](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0&range=B1))
      - Compare [old content](https://community-development.makerdao.com/) with new content (look for any missing holes)
      - Check for any outdated information
4. Run edits through a spell checker

**Acceptance criteria**

- [ ]  No missing content (these pages should include all necessary content from the existing site)
    - Reviewers should note that if content appears missing it has probably been left out deliberately. Consider what the user is trying to do an ask yourself whether it's needed or whether it just adds clutter to the page.
    - Any missing content should be turned into a new GitHub issue
- [ ]  Information is accurate
- [ ]  Language/terminology meets expectations
- [ ]  Links are correct

**Comment by TomDeMichele** [comment]
Hack.md files are up. Still need to be translated to .mdx files.
Bounty Hack.md file: https://hackmd.io/wVHI9qZqTBqBZ_DrXypHvA
Working on Bounty Hack.md file: https://hackmd.io/pcyBVpi2RsKeBvJdUuhF4Q

**Comment by amy-jung** [comment]
Cool does this mean you finished editing/it's ready for review or you just created the files and still working through them?

**Comment by TomDeMichele** [comment]
I would still like to review them before passing them on. Thanks for asking! I'll update when they are ready for review.

**Comment by amy-jung** [comment]
Old Comments before 2nd take (added here for visibility):

Work with us/Bounties #583
- Made small edits. Most notes are in the hackmd doc.
- We need a better transition from "Start Work" to "Payment". Preferably, referencing the "working on a bounty" page.
- [ ] Note to replace "See Open Bounties" link once we're done

Working on a bounty #583
- Need to remove 'you's
- Left comments in the hackmd.
- [ ] Note to replace "How to use GitHub" link

**Comment by amy-jung** [comment]
**Reviewed and Approved for both!**

**Notes for Working on a bounty**
- I realized a lot of the content here is related more so to "content" process instead of a general one so I made small clarifications.
- Added "Technical Resources"
- Would be good to use a "process stepper" component

**Comment by TomDeMichele** [comment]
These pages are pretty much good to go. Still needs:

- Links checked
- SEO
- A final copy edit to make sure the content is the best version of what we want from all different versions of this.
