### ISSUE TITLE
Portal Content Sprint: Work with us/Translations

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#584]
## Description
Suggested content already exists in the Work with us and Funding sections. The content team should review these pages against what exists.

- [x] [Action Page](https://www.notion.so/Work-with-us-action-page-example-Translations-e55a774d099b4a458d16a617eb0f23cd) | Work with us/Translations
- [x] Application Page | Work with us/Translations/Apply to join the team
- [x] [Process Page](https://www.notion.so/Process-page-example-using-GitHub-ad1e9bdc00214d4aa2fad4e7244d7821) | Work with us/Translations/The translation process

[Link to Working or Proposed Project Doc](https://hackmd.link)

## Steps
1. Review [Writing Style Guide](https://community-development.makerdao.com/contributing/writing-style-guide)
2. [Download the .md files](https://github.com/ryancreatescopy/community)
3. Work in hackmd (for comments/suggested edits) (We’ll be skipping google docs)
      - View [prototype](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=355%3A73) to get a sense of end goal
      - Make sure content fits Page Template model ([Linked in google sheet](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0&range=B1))
      - Compare [old content](https://community-development.makerdao.com/) with new content (look for any missing holes)
      - Check for any outdated information
4. Run edits through a spell checker

**Acceptance criteria**

- [x]  No missing content (these pages should include all necessary content from the existing site)
    - Reviewers should note that if content appears missing it has probably been left out deliberately. Consider what the user is trying to do an ask yourself whether it's needed or whether it just adds clutter to the page.
    - Any missing content should be turned into a new GitHub issue
- [ ]  Information is accurate
- [x]  Language/terminology meets expectations
- [x]  Links are correct

**Comment by twblack88** [comment]
The last step here is a kickoff with @reuptaken and @Gala-G to discuss the translations possibilities and how locales function. Merging Marcin's process with the new portal has a wealth of collaboration opportunities. 🚀

**Comment by Gala-G** [comment]
hey @twblack88 and @reuptaken,
It will be  a pleasure to do a kickoff call to discuss about this. 
Amy mentioned it briefly to me. Structuring a general translation process but also how it's important that we tailor each process to fit the interests and priorities of each region.

**Comment by twblack88** [comment]
Yassss!
