### ISSUE TITLE
Portal Content Sprint: Work with us Landing Page

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#591]
## Description
Suggested content already exists in the Work with us and Funding sections. The content team should review these pages against what exists.

Lead/Writer: @andytudhope 
Reviewer: @amy-jung  

- [ ] Landing Page | Work with us Landing Page

## Steps
1. Review [Writing Style Guide](https://community-development.makerdao.com/contributing/writing-style-guide)
2. [Download the .md files](https://github.com/ryancreatescopy/community)
3. Work in hackmd (for comments/suggested edits) (We’ll be skipping google docs)
      - View [prototype](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=355%3A73) to get a sense of end goal
      - Make sure content fits Page Template model ([Linked in google sheet](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0&range=B1))
      - Compare [old content](https://community-development.makerdao.com/) with new content (look for any missing holes)
      - Check for any outdated information
4. Run edits through a spell checker

**Acceptance criteria**

- [ ]  No missing content (these pages should include all necessary content from the existing site)
    - Reviewers should note that if content appears missing it has probably been left out deliberately. Consider what the user is trying to do an ask yourself whether it's needed or whether it just adds clutter to the page.
    - Any missing content should be turned into a new GitHub issue
- [ ]  Information is accurate
- [ ]  Language/terminology meets expectations
- [ ]  Links are correct

**Comment by andytudhope** [comment]
Oh, first draft done @aburban90: https://hackmd.io/@YemuuYMVQlulHcUUJJLS9g/HkxTftv6U

Only 2 small edits:

One in the `page description` "up for grabs" -> "to be earned" as colloquialisms can be misleading. 

One in `Got an idea`: "we'll see what we can do" -> "we'll help you get started" as it is more encouraging.

**Comment by amy-jung** [comment]
**Reviewed & Approved!**

Capitalized titles- content looks great :) Most of the work will be playing with components in MDX so excited for that end 🎉
