### ISSUE TITLE
Portal Content Sprint: Work with us/Content and Content publishing process

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#592]
## Description
Suggested content already exists in the Work with us and Funding sections. The content team should review these pages against what exists.

Lead/Writer: @aburban90 
Reviewer: @andytudhope

- [ ] [Action Page](https://www.notion.so/Work-with-us-action-page-example-Translations-e55a774d099b4a458d16a617eb0f23cd) | Work with us/Content
- [ ] [Process Page](https://www.notion.so/Process-page-example-using-GitHub-ad1e9bdc00214d4aa2fad4e7244d7821) | Work with us/Content/Content publishing process

[Link to Working or Proposed Project Doc](https://hackmd.link)

## Steps
1. Review [Writing Style Guide](https://community-development.makerdao.com/contributing/writing-style-guide)
2. [Download the .md files](https://github.com/ryancreatescopy/community)
3. Work in hackmd (for comments/suggested edits) (We’ll be skipping google docs)
      - View [prototype](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=355%3A73) to get a sense of end goal
      - Make sure content fits Page Template model ([Linked in google sheet](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0&range=B1))
      - Compare [old content](https://community-development.makerdao.com/) with new content (look for any missing holes)
      - Check for any outdated information
4. Run edits through a spell checker

**Acceptance criteria**

- [ ]  No missing content (these pages should include all necessary content from the existing site)
    - Reviewers should note that if content appears missing it has probably been left out deliberately. Consider what the user is trying to do an ask yourself whether it's needed or whether it just adds clutter to the page.
    - Any missing content should be turned into a new GitHub issue
- [ ]  Information is accurate
- [ ]  Language/terminology meets expectations
- [ ]  Links are correct

**Comment by aburban90** [comment]
[Action Page](https://hackmd.io/R6uteKDiRjy84yExzk1hEA) | Work with us/content | index.mdx
[Process Page](https://hackmd.io/AznAgCNBTfO4ogtPJdus_Q) | Work with us/Content/Content publishing process | content-publishing-process.md

**Comment by andytudhope** [comment]
1. Action Page | Work with us/content | index.mdx - there are a LOT of open questions for me here @amy-jung 

a. `Educational Content` should link to the new Learn section.
b. New design for links auto-add an arrow. So I'm not sure what to do about the old convention of using the arrow only for external links, i.e. AMD.
c. `Reference Content` should link to the new Work With Us section.
d. Not sure what to do about sentences like `A friendly community member will get back to you and explain the next steps`
e. Can we now removed "Google Docs" from the requirements?

**Comment by amy-jung** [comment]
**For A & C:** We should avoid the educational vs reference and stick with the mental model that defines around [Page Types](https://www.notion.so/Content-templates-cbb6cf99e08c463185859a6c7eb60b59).
**B.** Dang, wasn't aware of that auto add. I think we should pose that question to the larger group. 
**D.** When in doubt, I always reference reaching out in the community chat channel. (before you start work/if you have questions/etc). Then I try to be vague in who, but if there's a specific role (e.g. Advisor), I mention an Advisor will reach out. I avoid using "friendly" as I think it sets weird expectations :P   
**E.** I'm not fully convinced of us removing Google Docs from our workflow for two reasons: 1. if we need other stakeholders such as Legal to review the document, it creates a lot of friction to force them to use hackmd 2. hackmd doesn't render Images or video embeds.
