### ISSUE TITLE
Portal Content Sprint: Work with us/Meetups

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#594]
## Description
Suggested content already exists in the Work with us and Funding sections. The content team should review these pages against what exists.

Section Lead: @Davidutro 

- [ ] [Action Page](https://www.notion.so/Work-with-us-action-page-example-Translations-e55a774d099b4a458d16a617eb0f23cd) | Work with us/Meetups | Writer: @Davidutro 
- [ ] [Guide Page](https://www.notion.so/Guide-page-example-Work-with-us-Meetups-d611fbbd17264d38981e30f1f48b9655) | Work with us/Meetups/Getting Started Guide | Writer: @goldfarbas
- [ ] [Guide Page](https://www.notion.so/Guide-page-example-Work-with-us-Meetups-d611fbbd17264d38981e30f1f48b9655) | Work with us/Meetups/Events Formats Guide | Writer: @goldfarbas
- [ ] [Guide Page](https://www.notion.so/Guide-page-example-Work-with-us-Meetups-d611fbbd17264d38981e30f1f48b9655) | Work with us/Meetups/Promotion Guide | Writer: @Davidutro 

- [ ] [Guide Page](https://www.notion.so/Guide-page-example-Work-with-us-Meetups-d611fbbd17264d38981e30f1f48b9655) | Work with us/Meetups/Budget Guide | Writer: @Davidutro 

[Link to Working or Proposed Project Doc](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0&range=C10:C14)

## Steps
1. Review [Writing Style Guide](https://community-development.makerdao.com/contributing/writing-style-guide)
2. [Download the .md files](https://github.com/ryancreatescopy/community)
3. Work in hackmd (for comments/suggested edits) (We’ll be skipping google docs)
      - View [prototype](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=355%3A73) to get a sense of end goal
      - Make sure content fits Page Template model ([Linked in google sheet](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0&range=B1))
      - Compare [old content](https://community-development.makerdao.com/) with new content (look for any missing holes)
      - Check for any outdated information
4. Run edits through a spell checker

**Acceptance criteria**

- [ ]  No missing content (these pages should include all necessary content from the existing site)
    - Reviewers should note that if content appears missing it has probably been left out deliberately. Consider what the user is trying to do an ask yourself whether it's needed or whether it just adds clutter to the page.
    - Any missing content should be turned into a new GitHub issue
- [ ]  Information is accurate
- [ ]  Language/terminology meets expectations
- [ ]  Links are correct

**Comment by Davidutro** [comment]
I created all of the working docs in Hackmd. They are linked in the [google sheet in column C](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0)

**Comment by amy-jung** [comment]
Added writer / doc

**Comment by Davidutro** [comment]
the content side is reviewed.

Work still needs to be done to fix:
- the link format
- component format
- convert to mdx and setup live environment.

**Comment by goldfarbas** [comment]
Content looks good.

**Comment by Davidutro** [comment]
https://github.com/makerdao/community-portal/pull/134

Set up the pages, they still need a lot of work with regards to all the components.
Also updating content as I go along and see still.

**Comment by goldfarbas** [comment]
Content with MDX for Getting Started and Event Formats have been submitted in a PR here: https://github.com/makerdao/community-portal/pull/162.

**Comment by Davidutro** [comment]
Figure out where the Meetup FAQs ended up, and add the question about themes that Amy pointed out in #459
