### ISSUE TITLE
Portal Content Sprint: Work with us/Hackathons

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#595]
## Description
Suggested content already exists in the Work with us and Funding sections. The content team should review these pages against what exists.

Lead/Writer: @andytudhope 
Reviwer: @amy-jung 

- [ ] [Action Page](https://www.notion.so/Work-with-us-action-page-example-Translations-e55a774d099b4a458d16a617eb0f23cd) | Work with us/Hackathons
- [ ] [Guide Page](https://www.notion.so/Guide-page-example-Work-with-us-Meetups-d611fbbd17264d38981e30f1f48b9655) | Work with us/Hackathons/Guide to Hacking

[Link to Working or Proposed Project Doc](https://hackmd.link)

## Steps
1. Review [Writing Style Guide](https://community-development.makerdao.com/contributing/writing-style-guide)
2. [Download the .md files](https://github.com/ryancreatescopy/community)
3. Work in hackmd (for comments/suggested edits) (We’ll be skipping google docs)
      - View [prototype](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=355%3A73) to get a sense of end goal
      - Make sure content fits Page Template model ([Linked in google sheet](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0&range=B1))
      - Compare [old content](https://community-development.makerdao.com/) with new content (look for any missing holes)
      - Check for any outdated information
4. Run edits through a spell checker

**Acceptance criteria**

- [ ]  No missing content (these pages should include all necessary content from the existing site)
    - Reviewers should note that if content appears missing it has probably been left out deliberately. Consider what the user is trying to do an ask yourself whether it's needed or whether it just adds clutter to the page.
    - Any missing content should be turned into a new GitHub issue
- [ ]  Information is accurate
- [ ]  Language/terminology meets expectations
- [ ]  Links are correct

**Comment by andytudhope** [comment]
First draft done @aburban90 : https://hackmd.io/@YemuuYMVQlulHcUUJJLS9g/HkA3NKwaU

Quite a few finicky edits - a little too many to detail here. Look forward to comments. Not sure why Rimble UI is on that page, for instance (maybe just Ryan's bias @amy-jung?).

**Comment by andytudhope** [comment]
First draft of the Guide: https://hackmd.io/@YemuuYMVQlulHcUUJJLS9g/Byt4KtvTU

Also quite a few edits, most importantly: removed the recommendations for various medications and "the will to live" (not very funny imo). Added "good vibrations" to try keep the light tone without being potentially inappropriate.

**Comment by amy-jung** [comment]
Reviewed both documents. Needs another go through before approval:

The main discrepency I see across both documents is clarification on intent and as you mentioned, specificity.

- Is the page supposed to be MakerDAO focused or general? Currently it sits in between both, but not very clearly. My humble opinion is that it should be MakerDAO focused - and the guide should include more specifics of MakerDAO resourcing and experience (who to go to for what, what chat channels to go to, etc) as a guide to send to hackers at the start of a hackathon we're sponsoring. Might be good to reach out to the Developer Experience team to get more thoughts. 
- Similar to the landing page. CTAs for pathways could be clearer/perhaps more general that points to other pages or resources. Example:
1. Move content in "Start Hacking" section to the Guide" and replace with CTA referencing the guide for someone who is currently hacking on Maker related and wants resources or new to a hackathon but wants to explore maker related hacking experience
2. Keep development grants section in the landing page for cross reference.
3. Keep tout for Organizer looking for sponsorship funding from Maker

**Other side notes**
- Reference [prototype for the landing page](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=385%3A604)
- Guide is not very inclusive of virtual hackathons experience

**Comment by andytudhope** [comment]
Hey @amy-jung - I agree with most of this, and ideally want to rewrite a lot of this.

1. I don't like the "Backend" vs "Frontend" split - this is fundamentally **not** how blockchains work.
2. I agree it should be MakerDAO focused (though Rimble is a nice tool). That said, I wouldn't link to AMD first on the page...

Agree on your four clear points. Will implement now.

**Comment by andytudhope** [comment]
OK, have had a go at rewriting these two pages bit based on the feedback. Lmk what you think...

**Comment by amy-jung** [comment]
@andytudhope 

**Both are reviewed and approved!** 

**Notes for Guide:**
- Changed the title to "Guide to Hacking with MakerDAO" to be more specific and easier to find
- Added In-person hackathon / virtual differentiator
- I think "start hacking" section would be great with a list component
- Much love to Rimble, but removed :'( because it didn't fit quite well with all the MakerDAO resources. Another option if we want to keep it would have to add other external hackathon resources. 
- Moved previous hacks to a new header. We may have to take it out for V1 as we don't have a compiled list yet...
