### ISSUE TITLE
Portal Content Sprint: Work with us/Governance and risk meetings

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#596]
## Description
Suggested content already exists in the Work with us and Funding sections. The content team should review these pages against what exists.

Writer/Lead: @twblack88 
Reviwer: @Davidutro 

- [ ] [Action Page](https://www.notion.so/Work-with-us-action-page-example-Translations-e55a774d099b4a458d16a617eb0f23cd) | Work with us/Governance and risk meetings
- [ ] [Action Page](https://www.notion.so/Work-with-us-action-page-example-Translations-e55a774d099b4a458d16a617eb0f23cd) | Work with us/Governance and risk meetings/Take notes
- [ ] [Guide Page](https://www.notion.so/Guide-page-example-Work-with-us-Meetups-d611fbbd17264d38981e30f1f48b9655) | Work with us/Governance and risk meetings/Take notes/Formatting guide
- [ ] [Process Page](https://www.notion.so/Process-page-example-using-GitHub-ad1e9bdc00214d4aa2fad4e7244d7821) | Work with us/Governance and risk meetings/Take notes/Note-taking process
- [ ] [Guide Page](https://www.notion.so/Guide-page-example-Work-with-us-Meetups-d611fbbd17264d38981e30f1f48b9655) | Work with us/Governance and risk meetings/Take notes/Governance call template

[Link to Working or Proposed Project Doc](https://hackmd.link)

## Steps
1. Review [Writing Style Guide](https://community-development.makerdao.com/contributing/writing-style-guide)
2. [Download the .md files](https://github.com/ryancreatescopy/community)
3. Work in hackmd (for comments/suggested edits) (We’ll be skipping google docs)
      - View [prototype](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=355%3A73) to get a sense of end goal
      - Make sure content fits Page Template model ([Linked in google sheet](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0&range=B1))
      - Compare [old content](https://community-development.makerdao.com/) with new content (look for any missing holes)
      - Check for any outdated information
4. Run edits through a spell checker

**Acceptance criteria**

- [ ]  No missing content (these pages should include all necessary content from the existing site)
    - Reviewers should note that if content appears missing it has probably been left out deliberately. Consider what the user is trying to do an ask yourself whether it's needed or whether it just adds clutter to the page.
    - Any missing content should be turned into a new GitHub issue
- [ ]  Information is accurate
- [ ]  Language/terminology meets expectations
- [ ]  Links are correct

**Comment by twblack88** [comment]
Hack mds: 

[Work with us/Governance and risk meetings](https://hackmd.io/XSJIzUGbTnWQaTQ9fVTAuA)
[Work with us/Governance and risk meetings/Take notes](https://hackmd.io/JjnrXTwlQzWTxj_5kD19IQ)
[Work with us/Governance and risk meetings/Take notes/Formatting guide](https://hackmd.io/rlm1XufoQZ-ngYyIAvdT5Q)
[Work with us/Governance and risk meetings/Take notes/Note-taking process](https://hackmd.io/YBF5U6xDTzONnCLP8XqAGg)
[Work with us/Governance and risk meetings/Take notes/Governance call template](https://hackmd.io/vIu8AfczROe06tpRylVySg)

before tagging david I want to do a formatting pass.

**Comment by twblack88** [comment]
OK formatting and content focus pass done. @Davidutro feel free to get after a review when you have some time.m

**Comment by twblack88** [comment]
I’ve even got the landing page working in an mdx in new repo @Davidutro 😇😇
