### ISSUE TITLE
Portal Content Sprint: Funding/Hackathon funding

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#597]
## Description
Suggested content already exists in the Work with us and Funding sections. The content team should review these pages against what exists.

Lead/Writer: @andytudhope 
Reviewer: @amy-jung 

- [ ] [Application Page](https://www.notion.so/Application-page-example-Development-grants-or-Join-the-translation-team-81eef02069bc47d2879d0c8bdc823d18) | Funding/Hackathon funding

[Link to Working or Proposed Project Doc](https://hackmd.link)

## Steps
1. Review [Writing Style Guide](https://community-development.makerdao.com/contributing/writing-style-guide)
2. [Download the .md files](https://github.com/ryancreatescopy/community)
3. Work in hackmd (for comments/suggested edits) (We’ll be skipping google docs)
      - View [prototype](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=355%3A73) to get a sense of end goal
      - Make sure content fits Page Template model ([Linked in google sheet](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0&range=B1))
      - Compare [old content](https://community-development.makerdao.com/) with new content (look for any missing holes)
      - Check for any outdated information
4. Run edits through a spell checker

**Acceptance criteria**

- [ ]  No missing content (these pages should include all necessary content from the existing site)
    - Reviewers should note that if content appears missing it has probably been left out deliberately. Consider what the user is trying to do an ask yourself whether it's needed or whether it just adds clutter to the page.
    - Any missing content should be turned into a new GitHub issue
- [ ]  Information is accurate
- [ ]  Language/terminology meets expectations
- [ ]  Links are correct

**Comment by amy-jung** [comment]
**Reviewed and approved!** 

Made some small edits to content and capitalized titles. 

**Other note**
"Apply to hackathons@makerdao.com" section will need to be updated at a later time once we review the hackathons process in greater detail.

**Comment by andytudhope** [comment]
I prefer 'request'. Thanks for the other stuff, and noted the notes :+1:

**Comment by amy-jung** [comment]
**Approved!**

For V2: Need a form to replace the "apply" section
