### ISSUE TITLE
Portal Content: Funding/Meetup funding

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#598]
## Description
Suggested content already exists in the Work with us and Funding sections. The content team should review these pages against what exists.

Lead/Writer: @Davidutro 
Reviewer: @goldfarbas 

- [ ] [Application Page](https://www.notion.so/Application-page-example-Development-grants-or-Join-the-translation-team-81eef02069bc47d2879d0c8bdc823d18) | Funding/Meetup funding

[Link to line in the Content Sprint Spreadsheet](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0&range=40:40)

## Steps
1. Review [Writing Style Guide](https://community-development.makerdao.com/contributing/writing-style-guide)
2. [Download the .md files](https://github.com/ryancreatescopy/community)
3. Work in hackmd (for comments/suggested edits) (We’ll be skipping google docs)
      - View [prototype](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=355%3A73) to get a sense of end goal
      - Make sure content fits Page Template model ([Linked in google sheet](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0&range=B1))
      - Compare [old content](https://community-development.makerdao.com/) with new content (look for any missing holes)
      - Check for any outdated information
4. Run edits through a spell checker

**Acceptance criteria**

- [ ]  No missing content (these pages should include all necessary content from the existing site)
    - Reviewers should note that if content appears missing it has probably been left out deliberately. Consider what the user is trying to do an ask yourself whether it's needed or whether it just adds clutter to the page.
    - Any missing content should be turned into a new GitHub issue
- [ ]  Information is accurate
- [ ]  Language/terminology meets expectations
- [ ]  Links are correct

**Comment by Davidutro** [comment]
I created all of the working docs for this page in Hackmd. It is linked in the [google sheet in column C, row 24](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0)

**Comment by goldfarbas** [comment]
My drafts are updated in HackMD. Do I need to fork the repo, copy that in, and submit a PR?

**Comment by Davidutro** [comment]
@amy-jung 

At the end of the month, once we confirm the new contributor invoicing flow, I will update this page to reflect that.

Currently meetup applicants are asked to link their REQ Network invoice link.
However, now there will be a gasless easier way to do so.

Need to figure out if they make the invoice billable to
contributing@makerdao.com
or
meetups@makerdao.com

**Comment by Davidutro** [comment]
Updated the form, and the funding page to integrate new invoicing flow.

Waiting for V1 of the portal to go live before I add links to portal pages on the form itself.
