### ISSUE TITLE
Grants - Clarify whether the program has reopened

### ISSUE THREAD

**Issue by pcowgill** [makerdao/community#602]
## Description

Can you please clarify whether the grants program has reopened? [Here](https://github.com/makerdao/community/blob/master/grants/README.md) it says it will reopen on June 1, 2020, which is in the past (albeit only slightly). Thanks!

## Tasks

- [ ] Update README in `grants` dir

**Comment by amy-jung** [comment]
Hey Paul, the grants have reopened.
