### ISSUE TITLE
2020-07-06 - Unscheduled Executive: Debt Ceiling Raise

### ISSUE THREAD

**Issue by ghettodev** [makerdao/community#633]
This [signal request](https://forum.makerdao.com/t/signal-request-eth-a-stability-fee-and-debt-ceiling-adjustments/3059)  will expire outside of PST working hours so I am queuing up an exec in case it passes.

**Comment by LongForWisdom** [comment]
What's the plan if it doesn't pass? I have no idea how to cancel it if you're asleep.
