### ISSUE TITLE
CDIP 26- Humans of MakerDAO

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#649]
Title: Humans of MakerDAO - A marketing campaign to promote the community portal.

Your name/handle: @goldfarbas 

Links to Github issue/forum post/ or discussion thread: #portal

Proposal abstract: To increase visibility to the new Community Portal, I propose we run a marketing campaign profiling some of the great people involved in bringing it to life. 

In the style of [Humans of New York](https://twitter.com/humansofny), the Humans of MakerDAO campaign will involve producing, distributing, and tracking the performance of a series of 30 profiles on the people building the community portal.

Sharing these profiles will help the cryptosphere see themselves in the people of MakerDAO and humanize the experience of participating in a DAO, helping them see a path to their own participation.

Each profile will include:

A name (or pseudonym)
A picture (real or avatar)
A self-written mini-essay about their experience with Maker (max 500 words)
A CTA linking to the portal

Goals of the campaign are to:

1. generate portal awareness
2. get people working for comm-dev or the DAO or the protocol as a result
3. help clarify topics
4. get feedback on said topics

CTAs can include:
-  Want to work on (design/development/content/other depending on the individual being featured) for MakerDAO? Join our weekly Community Call
- Check out more great work from (Featured Individual) and the rest of MakerDAO in the new [Community Portal]()!
- Interested in learning more about (whatever the Featured Individual’s working on)? Check out the (Name) section of the new [Community Portal]()!

The profiles will be distributed via Twitter and Reddit.

Est: 25 hours and one month timeline. 
- [ ] First check in with @twblack88 ~7-20

**Comment by patrick-j-govalpha** [comment]
Closing legacy issues
