### ISSUE TITLE
CDIP 24 - DAI LatAm Action Groups

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#670]
**Title**: DAI LatAm Action Groups

**Leads**:
Rocketchat: @marianodp, @Nadia

**Advisor**:
@Davidutro 

**Links**: 

[CDIP 24 Google Doc](https://docs.google.com/document/d/1Mp3wN7ql4gqgDGS6tH60QtCxHEOwuVHihT4nxck-28E/edit#)

**Proposal abstract**:
Run a 3-month program to fund local community building and market research in Brazil and Venezuela. This will be done through the creation of "action groups" made up of passionate local community members who will be granted a monthly stipend along with a set of tasks and goals.

If the first three months go well the intention is to renew for the complete 6 months with refined tasks and goals.

_Why are we working on this?_

Long Term (Mission Orientated):
- Increase Dai adoption in Latin America creating a local message to empathize with each community depending on the country.

Short Term (Action Orientated):
- We want to have an action group in the main LatAm markets for Dai, starting with Venezuela and Brazil.
- Create and administer the groups that will serve the local community, including social media groups and meetups.
- Localize Dai message, identifying legal constraints, market dynamics, and how to communicate Dai advantages.
- Translate or adapt Dai and Maker content related (Blog posts, tweets, news, etc.)

_The Countries_

**Venezuela** is an oppressed country with hyperinflation, capital controls, and a devalued currency. Due to the country’s restrictions (political and social) is important to have a local group that helps us to understand the different rules and caveats around crypto.

**Brazil** is the biggest market in LatAm and after several years of having a strong currency, the devaluation of the Real is a reality. In Brazil, we need an action group that can help us not just with the message but also translating all the information around Maker and Dai into Portuguese. Brazilians are more open to trusting new projects when they know there are Brazilians behind.

_Scope_

Tasks for members of these action teams:
- Set up a local social media channel: moderating the conversation, finding the right channel, creating content specifically for that channel (Instagram post, tweets, etc), engaging the community, helping new Dai users with onboarding, point people towards educational resources and ways to work with us.
- Producing some documentation about the country they are dealing with, with regards to localizing the Dai message, identifying legal constraints, market dynamics, how to communicate Dai advantages, etc.
- Organizing and hosting virtual or physical meetups for their communities.
- Translate content into the local language. May help translate the "learn" section in the coming new community development portal.
- Organizing and hosting virtual or physical meetups for their communities.

Milestones per country:

Brazil:
- 1 action group members; Caio
- Own a Social Media Channel: 300 followers in the first 3 months, a total of 1000 followers by 6 mo if the pilot continues in its current form.
- Help Partners in educational initiatives around Dai and DeFi the country. Webinars, tutorials and Videos.

Venezuela:
- 3 action group members: Luis Lozada, Alejandro Fernandes, Diego Ortiz
- Own a Social Media Channel: 250 followers in the first 3 months, a total of 500 followers by 6 mo if the pilot continues in its current form.
- Help Partners in educational initiatives around Dai and DeFi the country. Webinars, tutorials and Videos.

Questions from reviewers:
1. Is the funding for both of you, or is it for distributing as compensation to community members who help build, manage, and communicate on the social media channels?
Funding is for compensation to members willing to own all the goals of the Action group. They will invoice you or Rich as we do with DIY meetup.
2. How will you track the progress of the action groups? Will there be any documentation of their work?
Yes, we will have constant contact with members of these action groups and document their progress because our objective is to replicate this in other LatAm countries. The idea is to set quarterly goals (defined in the proposal) and have weekly calls to help them to set a plan and track their progress.

**Comment by Davidutro** [comment]
Status update:

It is currently the end of month 2 of this 3-month pilot.

I believe as we approach the end of March there will be a retrospective meeting to review how this pilot went, and I suppose to decide on how to go about possible future funding.

As the advisor on the CDIP I will be reaching out the team, and Leads to schedule a call.

**Comment by Davidutro** [comment]
Call scheduled for 
2pm EST Tuesday 20th October

**Comment by Davidutro** [comment]
Questions for the retro:

- What documentation was produced about the countries?
- Have you experienced any community rockstars, super active people?
- What do you see is the purpose and function of the action group moving forward?
- What are the results of the program, any tracked KPIs?
- Biggest thing you learned during this pilot?
- Biggest obstacle you or the team faced during the pilot?

**Comment by Davidutro** [comment]
[Venezuela team summary of the pilot program](https://docs.google.com/document/d/1pu6CpK6ja9kkhSB7LGgl6Pl5fE7jDQ9-a4RTlTPovrs/edit)

**Comment by amy-jung** [comment]
Closed - See Issue #1133 for all the good stuff
