### ISSUE TITLE
CDIP 22 - Contributor Welcome Package Program

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#690]
Title: Contributor Welcome Package Program

Lead name/handle:
Rocketchat: @saint.burban

Advisor:
@Davidutro

Links:
[CDIP 22 Google Doc](https://docs.google.com/document/d/1O8fT-P_JhNXm_SKsAb_MZM_uM5CXy8JHfCLv9lfU0X4/edit#)

Proposal Abstract:

Joining the Maker community can be intimidating. Receiving a welcome package elicits excitement, raises morale, spreads positivity, and helps newcomers feel welcome. New members that feel positive vibes are more likely to be engaged, and bring others on board with them.

**Full proposal in google doc**
The spec is still being worked out, so I won't post here until it's close to final.

**Comment by aburban90** [comment]
Woo

**Comment by Davidutro** [comment]
This CDIP is currently waiting on the launch of the Maker Foundation's swag store.

**Comment by Davidutro** [comment]
@aburban90 Can you give an update on this CDIP?

1. How much swag do you have left?
2. Are you still sending it to contributors?

**Comment by amy-jung** [comment]
@aburban90 has submitted a final invoice for last pieces of swag - this is officially closed.
