### ISSUE TITLE
CDIP 09 - Reddit Moderator for r/MakerDAO

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#695]
**Title:** 
Reddit Moderator for r/MakerDAO

**Lead:** 
None

**Advisor:**
@David.utro

**[Google Doc for CDIP 09](https://docs.google.com/document/d/1C7S4P2eRns5ncUYH07MqmKZ7yTOEnZwwc657OFu0mJk/edit#)**

**[Forum Help Wanted Post](https://forum.makerdao.com/t/taken-reddit-moderator-for-r-makerdao/3486)**

**Proposal abstract:** 

This proposal is for a 1hr-a-day Reddit Moderator role.

1. Optional: A stand-alone Reddit account could be created just for this whose activity will be visible and auditable.
2. Success can be measured by the quality of the answers and the level of cross-linking to resources.

List of resources to cross-link(_can be expanded_):

- Awesome MakerDAO
- Community Development Portal
- FAQs
- Docs.makerdao.com
- Meetup Grants Program
- Governance Call summaries
- Relevant Forum Threads to bridge conversations about the same things
- Meeting Calendar links
- Governance Portal
- Etc.

On improving the subreddit:
- Discoverability and bridging conversations between the Maker Forums and Reddit is valuable.
- What distinct qualities are we trying to foster in the subreddit vs. the maker forums?
- Is the subreddit just more accessible to people outside of the community?
- Feel free to add more ideas as comments in this issue

On keeping things civil:
_Here are the famous, highly specific guidelines written up by Richard Brown(previous r/MakerDAO mod)_
- “Please keep the debate in r/MakerDAO civil. Personal attacks, insults, low effort posts, trolling, memes, speculation, factually incorrect and/or misleading statements will be removed.
Toxic interactions lower the tone of the discussion, incite escalated responses and reduce the community's expectations of acceptable behavior.”_

Cost | Resources: Total: 
30 Dai per hour
5 days per week
150 Dai per week

Estimated time to completion:
Continuous 
5-days a week, 1 hour a day,

Availability status: 
Taken

**Comment by twblack88** [comment]
@Davidutro thar be an exciting update on this CDIP correct?

**Comment by Davidutro** [comment]
u/repotactics1 is our newest Reddit Mod!

**Comment by Davidutro** [comment]
Funding the reddit mod will be an expense of a Core Unit in the coming months. Not clear which one yet so I am keeping this open.

**Comment by patrick-j-govalpha** [comment]
Closing legacy issues

**Comment by skinfinite7250-del** [comment]
- 000
