### ISSUE TITLE
CDIP 27- Community Portal - Marketing Strategy - Phase 1

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#720]
# Community-Development Initiative Proposal (CDIP [27] [@annaalexak @TomDeMichele @goldfarbas ])

**Title**: *Community Portal - Marketing Strategy*

**Your name/handle**: @TomDeMichele 

**Links to Github issue/forum post/ or discussion thread**: delivers framework from #538 and delivers a Go-to-market plan for the portal. [CDIP details here](https://docs.google.com/document/d/1Ei1n4mq4lLScwCweQ6Ybt5JrpO5F_7i5wiBNrnQEfO8/edit#heading=h.ktbfbk9aggt4)

**Proposal abstract**: Once the Portal is ”hard launched” it will be time to promote it to the public. To promote the Community Portal we will form a comm-dev marketing team to plan and launch a Portal Marketing campaign. This campaign will consist of five phases (see details below).

The first phase, and the phase being proposed in this CDIP, is the Go-to-Market plan phase. The Go-to-Market plan created by phase 1 will not only help to launch the campaign but will provide a framework for how we can work as a team to promote other projects in the future. 

**Proposal**: We will create a Go-to-Market plan to define our target audience and the deliverables that will best reach them.

**Estimated time to completion**: Aug 15th presentation to Community Development

**Comment by Davidutro** [comment]
Closed #216 

This Issue covers the same topic. If we want to reopen that general issue in the future we can do so. In the meantime I closed it to reduce noise.

**Comment by goldfarbas** [comment]
Here's a public [Drive Folder](https://drive.google.com/drive/u/0/folders/1y2priugZDEFPjzCdERV9keqZLEykCNNR) and [Marketing Docs Overview](https://docs.google.com/spreadsheets/d/1WE810eSXVgJ9E6TfrfTfLqSreCawuGeLz5DAd_lTB8g/edit#gid=0) spreadsheet that should each contain all of the documents relating to Comms Portal marketing.

**Comment by twblack88** [comment]
[Video of the community call](https://www.youtube.com/watch?v=vkPaT_7EEbs) demo-ing the portal 
[Forum post announcing portal](https://forum.makerdao.com/t/community-development-team-launches-community-development-portal/5020)
