### ISSUE TITLE
CDIP 30- Voices of MakerDAO Podcast - finding ways to speak as a DAO

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#753]
# Community-Development Initiative Proposal (CDIP [30] [@Jerry.G])

**Title**:
*Voices of MakerDAO - finding ways to speak as a DAO*

**Your name/handle**: 
@Jerry.G

**Advisor:**
@Davidutro 

**Links to Github issue/forum post/or discussion thread**: 
[Initial CDIP Google Doc](https://docs.google.com/document/d/1LUxb4dEUojeoIHCclEHcVQkXDk0UXCwIpp9LIXeH5VU/edit?pli=1#heading=h.ktbfbk9aggt4)

**Proposal abstract**: 
MakerDAO, and the Comm Dev team specifically, have been striving to find efficient and useful ways to distribute information and updates about governance and other aspects of the project. In today’s world (as well as the world of tech in particular), it is especially common for people to prefer and search for ways to take in some of this information auditorily.

To help expand the distribution of Maker Relay and the efforts of GovComms, I propose we figure out a way to distribute the content that goes into Maker Relay in a podcast format and find a way to incorporate voter education into the content. It is entirely possible to presume that this could include; an updated version of the community calls, onboarding info, foundational/community updates.. The ideas are only limited by the bandwidth! 

This can potentially be a good platform for all types of education, onboarding, updates, and presentations. In the future this could expand to include graphical/video content of various types & formats.

_This proposal is to perform research and create a plan for making that happen._

**Proposal**: 

_Research:_

![image](https://user-images.githubusercontent.com/40721951/92127400-43d0ec00-edcf-11ea-8c9a-4b3e3ef41388.png)

_Deliverables:_

![image](https://user-images.githubusercontent.com/40721951/92127436-4df2ea80-edcf-11ea-9142-22626c06930a.png)

**Cost | Resources:**
4 hours researching solutions and coordinating with potential teammates/contributors
3 hours writing the proposal (/organizing options, research and ideas)
5 hours working on audio branding
6 hours finding/cutting and editing an example(s)
_Total: $720 for 18 hours at $40/hour_

**Estimated time to completion**:
Approx ~1week

**Comment by Davidutro** [comment]
Updated after some further iteration.

**Comment by Davidutro** [comment]
Status update:

Waiting to be presented to CDIP approval committee

**Comment by Davidutro** [comment]
Status update:

Met with Jerry, did some suggested edits, he will look over and talk with me about them.

Once that's settled, and Jerry selects the revised complete-by dates we can begin the execution component of this CDIP.

**Comment by Davidutro** [comment]
Jerry set to present progress on this CDIP on next Wednesday's(OCT 28) comdev standup call.

**Comment by jerrygoldfarb** [comment]
**Relevant Links:** 
[CDIP Google Doc](https://docs.google.com/document/d/1LUxb4dEUojeoIHCclEHcVQkXDk0UXCwIpp9LIXeH5VU/edit#heading=h.ktbfbk9aggt4)
[Post-CDIP Proposal](https://docs.google.com/document/d/1dTCPCrABSr9PnheEQd348_Gq1c1wrmo_F9GXcXIQ0Ow/edit#)
[Research](https://docs.google.com/document/d/1s7rhHgSSxudAeo6jNSksNrGjPH5uvfK6MeWtI2yq5cc/edit)
[Commercial for Presentation](https://drive.google.com/file/d/1PKsgvtSD1Y6dg4iZJZu5IB1Knlo5Fhwu/view?usp=sharing)

**Comment by Davidutro** [comment]
Note:

Jerry completed this CDIP under budget! $640/720

**Comment by jerrygoldfarb** [comment]
Example episodes:

[Example1 v1](https://drive.google.com/file/d/105Z_-wVpf21lHsjJUtmkLoClHHTI2xlK/view?usp=sharing)

[Example1 v2](https://drive.google.com/file/d/1QJgw_NITXQPfYK0Lex_a2Tvjw7_378SR/view?usp=sharing)

[Example1 v3](https://drive.google.com/file/d/1k1vuD5Wy2YevtcUnwPQCwL9qEaI5Nuh_/view?usp=sharing)

**Comment by jerrygoldfarb** [comment]
Flash Loan Call Podcast Version:
https://drive.google.com/file/d/1QU3_--RFSy-Yo0orasHEPk7XFXkG1-fA/view?usp=sharing

**Comment by Davidutro** [comment]
https://forum.makerdao.com/t/poll-included-cdip30-voices-of-makerdao-podcast-updates-and-deliverables/4999
