### ISSUE TITLE
Governance "Learn" Section Improvements

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#761]
## Description

Governance Pages are important and need to be polished and improved.

See [this range](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0&range=66:80) in the Portal Content Sprint Spreadsheet
[LongForWisdom's recent Feedback Doc](https://docs.google.com/document/d/1ALWUoJ05J9nx_6FmbIaj7pPQUkK_N3I5vwhUhy_JK9o/edit#heading=h.a9w2bjyimtq)

**Acceptance Criteria**

- [x]  No missing content (these pages should include all necessary content from the existing site)
    - Reviewers should note that if content appears missing it has probably been left out deliberately. Consider what the user is trying to do an ask yourself whether it's needed or whether it just adds clutter to the page.
    - Any missing content should be turned into a new GitHub issue under this EPIC.
- [x]  Information is accurate
- [x]  Language/terminology meets expectations
- [x]  Links are correct
- [ ] Add MIPs page

**Comment by Davidutro** [comment]
Old Similar Issue:
#125

**Comment by twblack88** [comment]
I believe that for launch these pages are in good shape. @Davidutro and I will review today again. 9-16. 

We took @LongForWisdom's feedback and turned it into action items and did a full overhaul.

**Comment by Davidutro** [comment]
I converted this "epic" back into an issue, and nested it under the 2020 maintenance plan.

Any and all improvements to the Governance Learn section can be referenced here in this issue. Otherwise they will be covered by the general maintenance plan that is being set up.

**Comment by Davidutro** [comment]
Add a MIPs page

Charles already working on documentation.
We will have to adapt the documentation to the .mdx portal format.

Ideal: 
mips.makerdao.com explainer page will have the source material that can live on the mips page in Learn>Governance

**Comment by twblack88** [comment]
Mips has all the love it needs thanks to @juan-fintech closing this up.
