### ISSUE TITLE
Reestablishing the Maintenance Plan

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#762]
## Description

The original Maintenance Plan project was put on hold due to a new Community Development Portal. This issue to reestablish the Maintenance Plan once the V1 fully launches.

### Subtasks

- Integrate [Hypothesis](https://web.hypothes.is) into the process. It's free, open-source, feature complete.
- Create Step by Step workflow process(SOP).
- Decide on a 2-week time period to do a maintenance sprint during these next couple of months.
- Potentially do a test-sprint with only one person, Hayden.

### Roles

Lead - Responsible for executing the Maintenance Plan, setting up the excel sheet, assigning reviewers, reviewing PRs, and more.

Reviewer - Submits PRs based on Hypothesis suggestions and their own suggestions.

Casual Contributor - Uses [Hypothesis private group(group invite link)](https://hypothes.is/groups/Q4QYmy5D/portal-suggestions) to leave suggestions and corrections.

### Suggestions

In perpetuity, people will be able to leave feedback on pages using the [Hypothesis extension.](https://web.hypothes.is)

- Download extension
- Join the [Portal Suggestions](https://hypothes.is/groups/Q4QYmy5D/portal-suggestions) group.
- Leave any feedback and suggestions in the group space.

### Initial Pull Request

At the end of each quarter, the Maintenance Plan Lead will find and assign one or two contributors to help look through Hypothesis suggestions and create pull requests with changes.

### Review of Pull Requests

The Maintenance Plan Lead will do final reviews of Pull Requests, marking them reviewed, and ready to be merged.

### Merge of Pull Requests

Amy Jung will merge all PRs that are marked reviewed because she has access to merging changes into the master branch of the community repository. Alternatively, it can be LFW or someone from commdev who has merge rights.

## Workflow

1. A week before a maintenance cycle begins a spreadsheet must be set up that lists the grouped sections or individual pages that need to be reviewed, along with special notes if they are necessary.
   - This is to be done by the Lead of the Maintenance Plan by duplicating the previous quarter’s sheet and updating it for the new cycle.
   - Special notes contain improvement requests, special considerations, “do not change” requests, and virtually anything the person needs to keep in mind when reviewing that row item.
2. The Lead is responsible for assigning spots for PR writers of each item on the spreadsheet.
   - This gives the PM one week to fill all the spots.
   - Pages can be assigned by section, to make it easier if you are only working with one or two PR writers.
   - The maintenance plan is outlined and shared with the contributor community on the weekly contributor standup call.
   - This is a good opportunity to recruit people into the portal maintenance team.
3. Assigned contributors are given access to the spreadsheet by the PM prior to the start of the maintenance cycle sprint.
4. Week one.
   -  Contributors are asked to complete their Pull Requests by the end of the week and to post the link to them in the spreadsheet.
5. Week two.
   - The Lead goes through all Pull Requests and requests changes or marks them reviewed.
Amy can then merge all the ready Pull Requests.

## Update Sitmap URLs Process

Go to this link: 
https://github.com/makerdao/community/blob/gh-pages/sitemap.xml

**Comment by Davidutro** [comment]
Met with Hayden

- Usability focused
- Flow focused
- Crowdsourcing maintenance with Hypothesis.

We will focus on this End of October. Will reconnect with Hayden about helping me with this sometime then.

**Comment by Davidutro** [comment]
@HaydenSander Adding you to assignees soon

**Comment by Davidutro** [comment]
Updated Roles and potential workflow for the new maintenance plan. 
Next step. set up a cleaned-up excel sheet for the coming first sprint.

**Comment by Davidutro** [comment]
Notes to keep in mind:

Next meeting, invite Tim. He has some thoughts on page architecture and how content overlaps with technical content.

Tim mentioned that Shea volunteered to do a design audit at a certain point.

**Comment by Davidutro** [comment]
/makerdao-mcd-faqs/faqs

add status banners giving notice about old non-maintained content that is being deprecated over time.
<>

**Comment by Davidutro** [comment]
Update: Hayden might not be taking a co-leading role in this plan

**Comment by twblack88** [comment]
Just a heads up, since the redirects are awaiting a merge to prod ill clan up the FAQ pages which need status banner and link fixes.

**Comment by Davidutro** [comment]
maintenance plan was reestablished and documented. 

Not currently running at any regular cadence. We're waiting to hand this off to the right Core Unit that will do this for the portal
