### ISSUE TITLE
V2 Analytics - Epic

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#800]
Some of these got closed in makerdao/community-portal#95 

But for posterity/organization/and planning here are my notes from previous syncs and conversations. 

Will convert to issues or next inside of open ones like makerdao/community-portal#96 
- GA Optimize (and what we need from it; guessing a couple of pages to test would be the best)
- GA tags and can they go to frontmatter?
- GA goal architecture
- GA campaign linking?

**Comment by patrick-j-govalpha** [comment]
Closing legacy issues
