### ISSUE TITLE
CDIP 35 MakerDAO Three Walkthrough Videos Translation and Dubbing in Bahasa Indonesia  [@madmaker]

### ISSUE THREAD

**Issue by hungkymonkey** [makerdao/community#816]
Title Proposal: 
MakerDAO Three Walkthrough Videos Translation and Dubbing in Bahasa Indonesia 
-DAI introduction
-How to open a vault
-DSR 

Lead:
Muhammad Faqih Mubarok ( Ambassador MakerDAO Indonesia )
madmaker (on rocketchat)
@hungkymonkey (on GitHub)

Adviser:
Jocelyn Chang, APAC community lead 

Proposal: 
Problem: Indonesian users are not fluent in English. 
Solution: Therefore I decided to translate and dub the videos in Bahasa for easier delivery of information. 
List of Cost | Resources: (If you would prefer to keep costs discussion private, find a MakerDAO team member in the #Community-Development chat to DM)

450 DAI for three videos.

Estimated timeline: 
5-7 days.

Availability status: 

I am good at dubbing and translating. I’d like to do more graphic designs and video creation. 

Notes:
These are the two links to the videos, have completed two videos 
-DAI introduction ( Finished )
-How to open a vault ( Finished )
-DSR Video ( Finished )

1.DAI Introduction & How to open a vault Video Link 
https://drive.google.com/drive/folders/1bG015traD-lKDxgMEcvd6HCHUlFa67Yw?usp=sharing 

2. DSR Video

https://drive.google.com/file/d/1pPxPlp4iXD2qAg1tSh0lF1Q-n2bhC8aN/view?usp=sharing

[Google Doc](https://docs.google.com/document/d/1JfJNYMUWzoUazeoVlFhpITiaYewHNc0Bar0FwaOVBWc/edit#)

P/s: Both Jocelyn and David are aware of this CDIP.

**Comment by Davidutro** [comment]
Revision requested:

Jocelyn mentioned that these two videos are part of a larger video translation project.
If that's right, please resubmit CDIP with plans for future work as well as the two videos already created.

**Comment by jocy854** [comment]
Have informed @hungkymonkey . He will make the amendments in the google doc. The larger video translation is to translate all 3 videos which he has completed 2 (Intro to maker protocol & how to open a maker vault). And he is working on the 3rd one (DSR).

**Comment by Davidutro** [comment]
As an archival side-note: 

We do not fund work retroactively. We will be making an exception for this CDIP.
In the future please make sure to make the proposal before work is done :))

Assuming this Proposal is updated; 3 videos total, I will be giving a status update about this soon.

**Comment by hungkymonkey** [comment]
> As an archival side-note:
> 
> We do not fund work retroactively. We will be making an exception for this CDIP.
> In the future please make sure to make the proposal before work is done :))
> 
> Assuming this Proposal is updated; 3 videos total, I will be giving a status update about this soon, just need to touch base with the rest of the approval committee.

Thankyou so much David ;) and for my best advisor @jocy854  ;)

**Comment by hungkymonkey** [comment]
Hi @jocy854 @Davidutro please take a look i have finished dubbing video for DSR and all of threes video is has finished and please check it thankyou

**Comment by Davidutro** [comment]
Sounds like our team approved it. Feel free to send the invoice at the end of the month.

I will send you the invoice guide on rocketchat @hungkymonkey :)

**Comment by patrick-j-govalpha** [comment]
closing legacy issues
