### ISSUE TITLE
`Create-Redirect` in gatsby is not behaving

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#847]
**Describe the bug**
Despite testing localy, in another repo, copying content in two places (root and in content), and _specifically_ setting up locales to function the portal still won't redirect users politely.  

**To Reproduce**
1. links from [this older blog post](https://blog.makerdao.com/maker-foundation-community-grants-provide-funding-for-blockchain-projects/) and they didn't spit you out where users should be in the content folder 
2. `/contibuting` `/meetups` `/onboarding` all don't path....to... their path.  

**Expected behavior**
Links would function like links, the old content would build (which we tested and confirmed), and users would be in static but old content pages. 

**Desktop (please complete the following information):**
 - OS: Mac OS and PC
 - Browser: all

**Smartphone (please complete the following information):**
 - Device: I tested on iPhone X pro
 - OS: 13 
 - Browser: Chrome

**Additional context**
I tried to edit `gatsby-node.js` with more redirects based on simple pathing or even URLs. Despite building just fine I couldn't get the path to follow the right structure. it's really weird.

Is adding custom redirects the correct idea here? E.g based on possible link paths like https://community-development.makerdao.com/contributing make it 
```
frompath: '/contributing/'
topath: '/contribute` 
```

**Comment by MaximumCrash** [comment]
Closed by #867
