### ISSUE TITLE
Feature - API Embed

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#855]
Meetups, grants, translations, and some Contributor Teams Use air table for applications. It would be super snazzy to have embed form.

Beyond just form embed, It would be nice to explore "write to an air table database." ( I think they're called blocks) The example were thinking of for governance communicationsIs to collect emails In an air table for eventual email distribution. We need to keep special consideration for privacy. And we should look at this one next week to decide before implementing anything more advanced than just forms (at least).

**Comment by twblack88** [comment]
Revisiting this now that we have the site in the wild. A sitewide supported iframe (`full width` and whatever height ) is still the best option. 

Priority platforms to test: 
Figma
Airtable
Google (forms, docs,  and/or sheets)

**Comment by patrick-j-govalpha** [comment]
Closing legacy issues
