### ISSUE TITLE
Feature - Inline Emoji Support

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#856]
![Screen Shot 2020-07-02 at 5 32 46 PM](https://user-images.githubusercontent.com/8991325/86420045-1611de80-bc8a-11ea-89b5-1241cabbb53f.png)
Wrote out a fun doc for content creators (#89 ) that I'll strip down into a troubleshooting guide. On the way I discovered emoji inline support doesn't work, the PM 👷 inside me dies 🗡️  a little 🔻  without my 💯

**Comment by patrick-j-govalpha** [comment]
Closing legacy issues
