### ISSUE TITLE
Feature - Anchor ID's

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#857]
One continuous issue we had with gitbooks was anchor ID's in HTML (looked terrible and would break IIRC). Especially for content that becomes technical, like keepers guides, it's helpful to point to and review ideas/concepts within one file. We had to remove anchor ID's altogether but getting the convo going on how we would use them as a component, or the best decision(s) to evaluate. 

I assume it would be straightforward to make a component for these that is easier to use.

**Comment by twblack88** [comment]
Discovered this: https://theme-ui.com/guides/linked-headings/ so adding the details to the roadmap. 🕺

**Comment by MaximumCrash** [comment]
Closed by @ofqwx  on #1040
