### ISSUE TITLE
Spacing Around Column and Callout frames Increases When Type Size Is Increased

### ISSUE THREAD

**Issue by eringeorgen** [makerdao/community#859]
**Describe the bug**
Issue occurs several different browser windows, when the Type size is increased. The spacing around the column (top, bottom, left, right) also increases causing the Column to become very narrow. It does not occur on mobile device using Chrome. The issue is also seen with Callout content except that it appears to perform as expected on Chrome on my desktop (instead of just on mobile in Chrome).

**To Reproduce**
1. Go to [resources/technical-content/palette-recipes](https://community-portal-staging.makerfoundation.com/en/resources/technical-content/palette-recipes) using a mobile device or a narrow desktop browser window. (Not Chrome on mobile).
2. Scroll down to the examples below the "Column" heading and adjust the type size in the browser
3. See Error
4. Repeat on mobile using Chrome for a comparison

**Expected behavior**
The spacing around Column content should not increase when users increase the size of the type in the browser. The Column width should remain constant regardless of type size.

**Screenshots**
On mobile Safari (default type vs increased type size)
![IMG_4652](https://user-images.githubusercontent.com/70353047/93290470-a8a82100-f795-11ea-943d-0d7201a4593e.PNG)
![IMG_4651](https://user-images.githubusercontent.com/70353047/93290481-af369880-f795-11ea-82bc-065764a839c0.PNG)

Desktop, minimized Browser window
<img width="507" alt="Screen Shot 2020-09-15 at 7 12 19 PM" src="https://user-images.githubusercontent.com/70353047/93290815-6fbc7c00-f796-11ea-805a-37fa7cc91818.png">
<img width="497" alt="Screen Shot 2020-09-15 at 7 13 43 PM" src="https://user-images.githubusercontent.com/70353047/93290810-6cc18b80-f796-11ea-8858-255b87489a1b.png">
<img width="463" alt="Screen Shot 2020-09-15 at 9 07 57 PM" src="https://user-images.githubusercontent.com/70353047/93291454-f9207e00-f797-11ea-9467-8aa9faf36e03.png">
<img width="456" alt="Screen Shot 2020-09-15 at 9 07 20 PM" src="https://user-images.githubusercontent.com/70353047/93291472-089fc700-f798-11ea-8aa1-b29d4fa11702.png">

Desktop, full width Browser window
Chrome (default vs enlarged type)
<img width="1398" alt="Screen Shot 2020-09-15 at 7 02 57 PM" src="https://user-images.githubusercontent.com/70353047/93290818-70eda900-f796-11ea-9762-f0b9f5a229df.png">
<img width="1386" alt="Screen Shot 2020-09-15 at 7 03 46 PM" src="https://user-images.githubusercontent.com/70353047/93290816-70551280-f796-11ea-9a1f-31dc9896adf3.png">
Firefox (default and two different increases in type)
<img width="1437" alt="Screen Shot 2020-09-15 at 9 09 14 PM" src="https://user-images.githubusercontent.com/70353047/93291571-43a1fa80-f798-11ea-9af0-7e7d48338191.png">
<img width="1434" alt="Screen Shot 2020-09-15 at 9 15 12 PM" src="https://user-images.githubusercontent.com/70353047/93291709-aabfaf00-f798-11ea-9292-2a2a83db142e.png">
<img width="1433" alt="Screen Shot 2020-09-15 at 9 10 27 PM" src="https://user-images.githubusercontent.com/70353047/93291566-40a70a00-f798-11ea-8c5b-32538f6fffbb.png">

Chrome on mobile (example of what is expected)
![IMG_4648](https://user-images.githubusercontent.com/70353047/93290571-e2792780-f795-11ea-867e-533eb2a9de38.PNG)
![IMG_4649](https://user-images.githubusercontent.com/70353047/93290583-e86f0880-f795-11ea-83f4-4b6d863b651b.PNG)

**Desktop (please complete the following information):**
 - OS: Catalina version 10.15.6
 - Browsers: Chrome, Firefox

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - Browsers: Safari, Chrome

**Additional context**
The issue can be seen on all pages with Column content in use and to all types of columns (Full Width, Sibling, with Header). The issue is also seen with Callout content except that Callout content appears to perform as expected on Chrome on my desktop (in addition to Chrome on my mobile device).

**Comment by patrick-j-govalpha** [comment]
closing legacy issues
