### ISSUE TITLE
Portal FAQS Governance - 404 Page Not Found

### ISSUE THREAD

**Issue by mliendro** [makerdao/community#860]
**Describe the bug**

**To Reproduce**
1. Go to 'https://makerdao.com/es/governance'
2. Scroll down to 'FAQ'
3. Click on 'See the FAQ' 
4. See error "404"

**Expected behavior**
https://community-development.makerdao.com/governance/governance
Show questions related to Makerdao governance

**Screenshots**
![imagen](https://user-images.githubusercontent.com/33443324/95001004-4a07e300-059c-11eb-91a5-a9c63db75af0.png)
![imagen](https://user-images.githubusercontent.com/33443324/95001027-80ddf900-059c-11eb-99e8-76ea4518deb7.png)
![imagen](https://user-images.githubusercontent.com/33443324/95001103-44f76380-059d-11eb-8f66-a517d7c9eed0.png)

**Comment by twblack88** [comment]
Slightly related to #847 we've made a redirect plan and will execute this over the coming week. Old links should be working by then. Thanks for flagging @mliendro !

**Comment by twblack88** [comment]
fixed up on commit #a05522a will push to website once we sort out the build check issue.
