### ISSUE TITLE
Adding to Writing Style Guide: Avoid using SLASHES to create lists.

### ISSUE THREAD

**Issue by eringeorgen** [makerdao/community#861]
**Is your feature request related to a problem? Please describe.**
Slashes are being used to create long lists in the content. This can cause a variety of issues when the content field is narrow and it can be confusing in context (mistaken for a broken URL).

**Describe the solution you'd like**
Add to the Writing Style guide that slashes shouldn't be used when some other form of list would be appropriate (bullets or commas for examples).

**Describe alternatives you've considered**
It could also continue to be handled on an as needed basis through the editing process (when specific uses are causing an issue).

**Screenshots and Additional context**
On mobile device the words following development are a list created using slashes:
![](https://user-images.githubusercontent.com/70353047/93246835-365a2100-f742-11ea-87ff-76247592fdfb.png)
same content on desktop for reference:
<img width="475" alt="Screen Shot 2020-09-15 at 12 26 53 PM" src="https://user-images.githubusercontent.com/70353047/93255425-c2724580-f74e-11ea-8906-ce3ba38ff67e.png">
An example of it's use can also be found on the [Writing Style Guide](https://community-portal-staging.makerfoundation.com/en/work_with_us/content/writing-style-guide) page, but this example does not run into as many issues because it remains short (character wise). Perhaps the writing style guide could reference character limits or limits on the number of slashes when they are used for creating a type of list:
<img width="571" alt="Screen Shot 2020-09-15 at 12 13 09 PM" src="https://user-images.githubusercontent.com/70353047/93255640-0c5b2b80-f74f-11ea-996f-e0601219fafb.png">

**Comment by patrick-j-govalpha** [comment]
closing legacy issues
