### ISSUE TITLE
Proposal Framework - Significant and Formal Decisions

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#893]
# Proposal Framework

**Reasons for this process:**

1. Decisions are time-bound to move forward.
2. More significant a decision it is, the more process is involved
3. Proposal must include the implications of the decision
4. Collectively get to the best decision

## Process for *Significant* Proposals

1. **Submission:** Submit a proposal that outlines the following
    a. What is the proposal (must include a plan for execution)
    b. What’s the decision that needs to be made
    c. Who is proposing (lead/team)
    d. Who is being impacted (i.e people it affects, people who are responsible for maintaining or approving)
    e. What is the impact (size) of the outcome
    f. What are the implications of the proposal/decision
2. **RFC:** Feedback, comments, revisions
    a. RFC lasts one week with a max of four rounds.
    b. At the end of the week, a vote happens.
    c. If a proposal keeps being prolonged, the proposer should reach out to the most active commenter.
3. **Voting / Decision:** Yes, No, Abstain, Block
    a. If after 1 month there is no movement, there must be a final decision made.
    b. Final decision

| Vote Condition   | Outcome|
| ----- | ----- |
| When there’s no block, and 51% yes | Proposal Passes|
| By round 4 there is still at least 1 block (but not majority block)| Decision is on Majority (Pass/Fail) |
| Minority Block / Majority No | Proposal Resubmits |
|All blocks | Proposal Fails, no resubmission

*Be willing to block or say no for a specific reason(s), ie. “not enough clarity on x”*

### Documentation

- Proposer documents the decision

### People

- Proposer(s) *proposer can ask for an experienced mentor to help w the process

### Voters
- Anyone who has contributed to at least one Comm-Dev project is allowed to opt-in to vote. They get to vote on all significant proposals, but they must vote.
- Even if you are a proposer, you can vote.

## Process for *Formal* Proposals

1. **Submission**: Submit a proposal that outlines the following
    a. What is the proposal (must include a plan for execution)
    b. What’s the decision that needs to be made
    c. Who is proposing (lead/team)
    d. Who is being impacted
    e. What is the impact (size) of the outcome
    f. What are the implications of the proposal/decision

2. **RFC:** Feedback, comments, revisions
    a. RFC is up to the proposer, 2 days recommended
    b. At the end of the RFC, comments are integrated. 
    c. After integration, a vote happens after a delay.

3. **Voting / Decision**: Yes, No, Abstain, Block
    a. Use a vote and reveal platform (suggested: Typeform or google forms)
    b. Proposer determines the minimum number of voters for success
    c. Final decision

| Vote Condition | Outcome | 
| -------- | -------- | 
| When there’s no block, and 51% yes| Proposal Passes| 
|Minority Block / Majority No | Proposal Resubmits|
| All blocks | Proposal Fails, no resubmission|

Be willing to block or say no for a specific reason(s), “not enough clarity”

### Documentation

- Proposer documents the decision

### People

- Proposer(s) can ask for an experienced mentor to help w/the process

### Voters

- Up to proposers to determine a minimum number for quorum.
- Even if you are a proposer, you can vote.

**Comment by amy-jung** [comment]
Processes to answer:

1. Who is responsible for calling the vote?
2. How should votes be done?
3. How much time is there for RFC? When does the voting period start and end?

**Comment by patrick-j-govalpha** [comment]
Closing legacy issues
