### ISSUE TITLE
CDIP 31- POAP

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#907]
**Title**: POAP for comm-dev
Quarterly POAP for Contributors of the Comm-Dev Team

**Lead**:
@juan-fintech 

**Adviser**:
@twblack88 

**Proposal abstract**: 
### Why?
Reward contributors for their work and to solidify the team. Try to improve retention of people involved.

### How?

By giving a badge (which is basically high-tech merchandise) that shows that they contributed in a way or another. This is to be awarded quarterly.

### What?

A POAP token (NFT), to be sent to all the people contributing to Comm-Dev.

**Listy of Cost | Resources**: 
| Item | Cost |
| -------- | -------- |
| Product Management     | 350 Dai     |
| Designer | 400 Dai|
| POAP Costs | 30 Dai|
| **TOTAL** | *780 Dai*|

**Estimated time to completion**: 
*The MVP (first iteration) should take less than two weeks (from approval to send POAP).
Documenting it should take another 2 or 3, based on iterations.
What cadence would be best to share updates? Weekly.*

**Availability status**: 
*Now! Now! Now!*

**Relevant Skills/Qualifications**:
*I’ve heard great things about the designer, so I’m quite bullish on this.
I’ve spoken with Patricio from POAP. It doesn’t look that complicated.
I’ve also spent a lot of hours documenting stuff, so I’m confident that it should be doable.*

**Comment by twblack88** [comment]
Approval: [✅  Approved 3 of 3, Tim Black (+Amy Jung, David Utrobin), 10-19-2020

Short evaluation Write-up: POAP is a quick and easy badge we can provide contributors. Juan will get this started and work on everyone who contributed in Q3 2020.

**Comment by twblack88** [comment]
@juan-fintech when you can add the documentation notion page you made and we can close this thang out. 👍

**Comment by juan-fintech** [comment]
@twblack88 

https://definotes.com/Create-a-POAP-for-your-Event-5af06cdfb7c24286ac3d31b0f0a47c40

Also DeFiNotes.com under the section "Tutorials".

PS, Q4 image looks awesome. : )

**Comment by patrick-j-govalpha** [comment]
Closing legacy issues, really wish this had kicked on more though, love a good POAP
