### ISSUE TITLE
404's

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#908]
A working list of 404's we find or any misused links. 

### Blocked

- [ ] /governance/governance-and-risk-meetings
- [ ] https://community-development.makerdao.com/en/resources/technical-content/publishing-to-repo-process/  

### Incorrect path
- [x] https://community-development.makerdao.com/en/learn/governance/mkr-token.mdx/ <-- governance page

## Fixed
- [x] https://community-development.makerdao.com/governance/governance-tools
- [x] https://community-development.makerdao.com/en/collateral-and-risk/dai-credit-system.mdx
- [x] https://community-development.makerdao.com/en/collateral-and-risk/types-of-risk.mdx  
- [x] https://community-development.makerdao.com/en/collateral-and-risk/risk-teams.mdx
- [x] https://community-development.makerdao.com/en/contribute/bounties/index.mdx
- [x] https://community-development.makerdao.com/en/learn/governance
- [x] https://community-development.makerdao.com/en/funding/development-grants/
- [x]  /governance/governance-faqs
- [x]  /FAQs
- [x]  /contributing
- [x]  /grants
- [x] scientific governance (governance/governance-risk-framework/part-one)
- [x] /governance/governance
- [x] /onboarding/voter-onboarding
- [x] /onboarding/vault-onboarding 
- [x] /makerdao-mcd-faqs/faqs/dsr 
- [x] /makerdao-mcd-faqs/faqs/vault 
- [x] /makerdao-scd-faqs/scd-faqs/stability-fee
- [x] /makerdao-mcd-faqs/faqs/liquidation
- [x] /makerdao-mcd-faqs/faqs/stability-fee
- [x] /makerdao-mcd-faqs/faqs/dai
- [x] /makerdao-mcd-faqs/faqs/mkr-token
- [x] /makerdao-scd-faqs/scd-faqs/liquidation 
- [x] /makerdao-mcd-faqs/faqs (https://community-development.makerdao.com/makerdao-mcd-faqs/)
- [x] /makerdao-mcd-faqs/faqs/oracles 
- [x] /governance/governance-risk-framework/part-one 
- [x] /makerdao-mcd-faqs/faqs/emergency-shutdown 
- [x] /makerdao-mcd-faqs/faqs/glossary
go to the long form guide.

**Comment by wschwab** [comment]
https://community-development.makerdao.com/en/contribute/bounties/index.mdx

**Comment by mrosendin** [comment]
https://community-development.makerdao.com/en/collateral-and-risk/dai-credit-system.mdx
https://community-development.makerdao.com/en/collateral-and-risk/types-of-risk.mdx
https://community-development.makerdao.com/en/collateral-and-risk/risk-teams.mdx

Linked from https://community-development.makerdao.com/en/learn/collateral-and-risk

**Comment by ianaz** [comment]
https://community-development.makerdao.com/en/funding/ 
https://community-development.makerdao.com/en/contribute/

(both from home page)

I'd gladly open a PR...
Should these two links point to:

https://community-development.makerdao.com/en/programs/development-grants and https://community-development.makerdao.com/en/programs/content/ respectively?

**Comment by sarc-cell** [comment]
broken link 
https://makerdao.world/en/contribute/governance_and_risk_meetings/summaries

**Comment by patrick-j-govalpha** [comment]
Closing legacy issues - makerdao.world and comdev sites no longer supported
