### ISSUE TITLE
Can we remove makerdao/community/tree/master/faqs? Since the old faqs are archived elseware in the repo.

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#962]
The FAQs are archived under `/community/tree/master/content/en/faqs`, is there a reason to have a double taking up space in the repository?

Proposal: remove `makerdao/community/tree/master/faqs`

**Comment by twblack88** [comment]
if the plan was to deprecate them, I think this would be the other way around yeah? They live on ` master` in Github but don't display on the content folder (the website).

**Comment by Davidutro** [comment]
The pages displayed here(https://community-development.makerdao.com/en/faqs/) are from `/community/tree/master/content/en/faqs` correct?

So if we want to keep those there, is there any reason we are keeping a second set in `makerdao/community/tree/master/faqs` ?

>if the plan was to deprecate them, I think this would be the other way around yeah?
The plan is to not deprecate them for the foreseeable future but to have them available as archive.

>They live on master in Github but don't display on the content folder (the website).
Don't they display on the content folder [here](https://community-development.makerdao.com/en/faqs/)?

**Comment by twblack88** [comment]
> The pages displayed here(https://community-development.makerdao.com/en/faqs/) are from /community/tree/master/content/en/faqs correct?

Correct

> So if we want to keep those there, is there any reason we are keeping a second set in /community/tree/master/faqs ?

Reason: perhaps there is one but it's not documented. Probably a migration artifact.
Good reason: no

**Comment by twblack88** [comment]
@Davidutro I think we can keep these top-level folders for now. When we rewrite the readme they should make more sense and we can prune there. By rounding out the archive tag and where the front page links go, it should help us understand what needs to stay.
